/**
 * Extended word pairs — 50 additional pairs per category per locale.
 * Added on top of the base 50 in seed.ts, bringing every pack to 100 pairs/category.
 *
 * Structure:
 *  - PROPER_*: proper-noun categories (mangas, celebrities, movies, music, history).
 *    Same pairs across all 8 locales — only the `locale` field differs.
 *  - TR_*:   translatable categories (food, animals, places, jobs, sports, variety).
 *    One array per locale with index-aligned translations.
 */

type Diff = 'easy' | 'medium' | 'hard'
type Triple = [string, string, Diff]

type PairData = {
  wordA: string
  wordB: string
  difficulty: Diff
  category: string
  locale: string
}

const LOCALES = ['en', 'fr', 'es', 'de', 'ar', 'it', 'pt', 'zh'] as const

function expandProper(category: string, triples: Triple[]): PairData[] {
  const out: PairData[] = []
  for (const locale of LOCALES) {
    for (const [a, b, d] of triples) {
      out.push({ wordA: a, wordB: b, difficulty: d, category, locale })
    }
  }
  return out
}

function expandLocale(category: string, locale: string, triples: Triple[]): PairData[] {
  return triples.map(([a, b, d]) => ({ wordA: a, wordB: b, difficulty: d, category, locale }))
}

// ═════════════════════════════════════════════════════════════════════════
// PROPER-NOUN CATEGORIES (identical across all 8 locales)
// ═════════════════════════════════════════════════════════════════════════

const PROPER_MANGAS: Triple[] = [
  // Easy (15) — signature techniques, iconic characters, famous places
  ['Rasengan', 'Chidori', 'easy'],
  ['Kamehameha', 'Galick Gun', 'easy'],
  ['Sharingan', 'Byakugan', 'easy'],
  ['Super Saiyan', 'Ultra Instinct', 'easy'],
  ['Devil Fruit', 'Quirk', 'easy'],
  ['Konoha', 'Amegakure', 'easy'],
  ['Marineford', 'Enies Lobby', 'easy'],
  ['Bankai', 'Shikai', 'easy'],
  ['All Might', 'Endeavor', 'easy'],
  ['Jiraiya', 'Tsunade', 'easy'],
  ['Madara', 'Hashirama', 'easy'],
  ['Shanks', 'Mihawk', 'easy'],
  ['Dragon Balls', 'Shikon Jewel', 'easy'],
  ['Straw Hats', 'Survey Corps', 'easy'],
  ['Akatsuki', 'Espada', 'easy'],
  // Medium (25) — sub-category overlap, trickier pairings
  ['Gear Second', 'Gear Fourth', 'medium'],
  ['Titan Shift', 'Tailed Beast Mode', 'medium'],
  ['Nen', 'Haki', 'medium'],
  ['Stand', 'Alchemy', 'medium'],
  ['Soul Society', 'Hueco Mundo', 'medium'],
  ['UA High', 'Shiketsu', 'medium'],
  ['Wano', 'Alabasta', 'medium'],
  ['Hidden Sand', 'Hidden Mist', 'medium'],
  ['Buggy', 'Hisoka', 'medium'],
  ['Zoro', 'Kenpachi', 'medium'],
  ['Orochimaru', 'Kabuto', 'medium'],
  ['Erza', 'Mirajane', 'medium'],
  ['Rock Lee', 'Might Guy', 'medium'],
  ['Boruto', 'Kawaki', 'medium'],
  ['Broly', 'Jiren', 'medium'],
  ['Pain', 'Konan', 'medium'],
  ['Big Mom', 'Kaido', 'medium'],
  ['Yoruichi', 'Soifon', 'medium'],
  ['Aizen', 'Yhwach', 'medium'],
  ['Armin', 'Jean', 'medium'],
  ['Midoriya', 'Uraraka', 'medium'],
  ['Whitebeard', 'Roger', 'medium'],
  ['Beerus', 'Whis', 'medium'],
  ['Itachi', 'Shisui', 'medium'],
  ['Getsuga Tensho', 'Rasenshuriken', 'medium'],
  // Hard (10) — deep cuts, niche but iconic
  ['Asauchi', 'Zanpakuto', 'hard'],
  ['Yamcha', 'Krillin', 'hard'],
  ['Meliodas', 'Escanor', 'hard'],
  ['Gowther', 'Merlin', 'hard'],
  ['Dabi', 'Shigaraki', 'hard'],
  ['Nobara', 'Maki', 'hard'],
  ['Satoru', 'Geto', 'hard'],
  ['Faye', 'Spike', 'hard'],
  ['Ikkaku', 'Yumichika', 'hard'],
  ['Jotaro', 'Josuke', 'hard'],
]
const PROPER_CELEBRITIES: Triple[] = [
  // Easy (15)
  ['Haaland', 'Mbappe', 'easy'],
  ['Tom Holland', 'Zendaya', 'easy'],
  ['Dua Lipa', 'Doja Cat', 'easy'],
  ['The Weeknd', 'Bruno Mars', 'easy'],
  ['Chris Hemsworth', 'Chris Evans', 'easy'],
  ['Gigi Hadid', 'Bella Hadid', 'easy'],
  ['Jennifer Lopez', 'Shakira', 'easy'],
  ['Kevin Hart', 'Jimmy Fallon', 'easy'],
  ['Jackie Chan', 'Jet Li', 'easy'],
  ['Karim Benzema', 'Luka Modric', 'easy'],
  ['Serena Williams', 'Naomi Osaka', 'easy'],
  ['Novak Djokovic', 'Carlos Alcaraz', 'easy'],
  ['Conor McGregor', 'Khabib', 'easy'],
  ['Mark Zuckerberg', 'Bill Gates', 'easy'],
  ['Pedro Pascal', 'Oscar Isaac', 'easy'],
  // Medium (25)
  ['Timothée Chalamet', 'Austin Butler', 'medium'],
  ['Anya Taylor Joy', 'Florence Pugh', 'medium'],
  ['Daniel Radcliffe', 'Rupert Grint', 'medium'],
  ['Millie Bobby Brown', 'Finn Wolfhard', 'medium'],
  ['Henry Cavill', 'Jason Momoa', 'medium'],
  ['Gal Gadot', 'Brie Larson', 'medium'],
  ['Tom Hardy', 'Cillian Murphy', 'medium'],
  ['Joaquin Phoenix', 'Jared Leto', 'medium'],
  ['Rami Malek', 'Remi Malek', 'medium'],
  ['Kendall Jenner', 'Hailey Bieber', 'medium'],
  ['Zlatan', 'Cantona', 'medium'],
  ['Iniesta', 'Xavi', 'medium'],
  ['Gerrard', 'Lampard', 'medium'],
  ['Kobe Bryant', 'Shaq', 'medium'],
  ['Tom Brady', 'Peyton Manning', 'medium'],
  ['Usain Bolt', 'Michael Phelps', 'medium'],
  ['Lewis Hamilton', 'Max Verstappen', 'medium'],
  ['Mike Tyson', 'Muhammad Ali', 'medium'],
  ['Floyd Mayweather', 'Manny Pacquiao', 'medium'],
  ['Gordon Ramsay', 'Jamie Oliver', 'medium'],
  ['Simone Biles', 'Nadia Comaneci', 'medium'],
  ['Tiger Woods', 'Rory McIlroy', 'medium'],
  ['Jay Z', 'Diddy', 'medium'],
  ['Cardi B', 'Nicki Minaj', 'medium'],
  ['Harry Styles', 'Niall Horan', 'medium'],
  // Hard (10)
  ['Quentin Tarantino', 'Wes Anderson', 'hard'],
  ['Christopher Nolan', 'Denis Villeneuve', 'hard'],
  ['Hayao Miyazaki', 'Makoto Shinkai', 'hard'],
  ['Anna Wintour', 'Tom Ford', 'hard'],
  ['Greta Thunberg', 'Malala', 'hard'],
  ['Stephen Hawking', 'Richard Feynman', 'hard'],
  ['Warren Buffett', 'Charlie Munger', 'hard'],
  ['Zaha Hadid', 'Frank Gehry', 'hard'],
  ['Banksy', 'KAWS', 'hard'],
  ['Ai Weiwei', 'Damien Hirst', 'hard'],
]
const PROPER_MOVIES: Triple[] = [
  // Easy (15)
  ['Barbie', 'Oppenheimer', 'easy'],
  ['Shrek', 'Madagascar', 'easy'],
  ['Cars', 'Planes', 'easy'],
  ['Ratatouille', 'Up', 'easy'],
  ['Toy Story', 'Cars', 'easy'],
  ['Frozen', 'Tangled', 'easy'],
  ['Moana', 'Brave', 'easy'],
  ['Deadpool', 'Wolverine', 'easy'],
  ['Thor', 'Loki', 'easy'],
  ['Doctor Strange', 'Scarlet Witch', 'easy'],
  ['Aquaman', 'Black Adam', 'easy'],
  ['Fast and Furious', 'Gone in 60 Seconds', 'easy'],
  ['Jurassic Park', 'King Kong', 'easy'],
  ['Home Alone', 'Elf', 'easy'],
  ['Mean Girls', 'Clueless', 'easy'],
  // Medium (25)
  ['Lord of the Rings', 'Hobbit', 'medium'],
  ['Harry Potter', 'Fantastic Beasts', 'medium'],
  ['Star Wars', 'Mandalorian', 'medium'],
  ['Alien', 'Predator', 'medium'],
  ['Saw', 'Hostel', 'medium'],
  ['Scream', 'Halloween', 'medium'],
  ['Conjuring', 'Insidious', 'medium'],
  ['It', 'Annabelle', 'medium'],
  ['Hunger Games', 'Divergent', 'medium'],
  ['Twilight', 'Vampire Diaries', 'medium'],
  ['Pirates of the Caribbean', 'Treasure Planet', 'medium'],
  ['Mission Impossible', 'James Bond', 'medium'],
  ['Taken', 'John Wick', 'medium'],
  ['Rocky', 'Creed', 'medium'],
  ['Top Gun', 'Maverick', 'medium'],
  ['Blade Runner', 'Ghost in the Shell', 'medium'],
  ['Tron', 'Ready Player One', 'medium'],
  ['Back to the Future', 'Bill and Ted', 'medium'],
  ['Ghostbusters', 'Men in Black', 'medium'],
  ['Indiana Jones', 'Tomb Raider', 'medium'],
  ['Mad Max', 'Waterworld', 'medium'],
  ['Bourne', 'Mission Impossible', 'medium'],
  ['Goodfellas', 'Casino', 'medium'],
  ['Godfather', 'Scarface', 'medium'],
  ['Pulp Fiction', 'Reservoir Dogs', 'medium'],
  // Hard (10)
  ['Parasite', 'Squid Game', 'hard'],
  ['Whiplash', 'Birdman', 'hard'],
  ['La La Land', 'Moulin Rouge', 'hard'],
  ['Eternal Sunshine', 'Being John Malkovich', 'hard'],
  ['Amelie', 'Delicatessen', 'hard'],
  ['Akira', 'Ghost in the Shell', 'hard'],
  ['Spirited Away', 'Princess Mononoke', 'hard'],
  ['Seven Samurai', 'Ran', 'hard'],
  ['City of God', 'Elite Squad', 'hard'],
  ['The Intouchables', 'Amelie', 'hard'],
]
const PROPER_MUSIC: Triple[] = [
  // Easy (15)
  ['Pop', 'Rock', 'easy'],
  ['Hip Hop', 'Rap', 'easy'],
  ['Jazz', 'Blues', 'easy'],
  ['Classical', 'Opera', 'easy'],
  ['Country', 'Folk', 'easy'],
  ['Reggae', 'Ska', 'easy'],
  ['House', 'Techno', 'easy'],
  ['Guitar', 'Bass', 'easy'],
  ['Piano', 'Keyboard', 'easy'],
  ['Drums', 'Percussion', 'easy'],
  ['Violin', 'Viola', 'easy'],
  ['Flute', 'Clarinet', 'easy'],
  ['Trumpet', 'Trombone', 'easy'],
  ['Saxophone', 'Oboe', 'easy'],
  ['Microphone', 'Headphones', 'easy'],
  // Medium (25)
  ['Eminem', 'Jay Z', 'medium'],
  ['Kendrick Lamar', 'J Cole', 'medium'],
  ['Tupac', 'Biggie', 'medium'],
  ['Snoop Dogg', 'Dr Dre', 'medium'],
  ['Pink Floyd', 'Led Zeppelin', 'medium'],
  ['Rolling Stones', 'The Who', 'medium'],
  ['AC DC', 'Aerosmith', 'medium'],
  ['Guns N Roses', 'Van Halen', 'medium'],
  ['Foo Fighters', 'Green Day', 'medium'],
  ['Linkin Park', 'System of a Down', 'medium'],
  ['Imagine Dragons', 'OneRepublic', 'medium'],
  ['Maroon 5', 'The Script', 'medium'],
  ['Ed Sheeran', 'James Arthur', 'medium'],
  ['Bruno Mars', 'John Legend', 'medium'],
  ['Sam Smith', 'Adele', 'medium'],
  ['Dua Lipa', 'Rita Ora', 'medium'],
  ['Shakira', 'Jennifer Lopez', 'medium'],
  ['Daddy Yankee', 'Don Omar', 'medium'],
  ['Bad Bunny', 'J Balvin', 'medium'],
  ['David Guetta', 'Calvin Harris', 'medium'],
  ['Martin Garrix', 'Tiesto', 'medium'],
  ['Daft Punk', 'Justice', 'medium'],
  ['Skrillex', 'Deadmau5', 'medium'],
  ['Kraftwerk', 'Tangerine Dream', 'medium'],
  ['Fleetwood Mac', 'Eagles', 'medium'],
  // Hard (10)
  ['Stravinsky', 'Debussy', 'hard'],
  ['Tchaikovsky', 'Rachmaninoff', 'hard'],
  ['Wagner', 'Verdi', 'hard'],
  ['Miles Davis', 'John Coltrane', 'hard'],
  ['Louis Armstrong', 'Duke Ellington', 'hard'],
  ['Ella Fitzgerald', 'Billie Holiday', 'hard'],
  ['Nina Simone', 'Aretha Franklin', 'hard'],
  ['Joni Mitchell', 'Carole King', 'hard'],
  ['Tom Waits', 'Leonard Cohen', 'hard'],
  ['Neil Young', 'Crosby Stills Nash', 'hard'],
]
const PROPER_HISTORY: Triple[] = [
  // Easy (15)
  ['Napoleon', 'Caesar', 'easy'],
  ['Hitler', 'Mussolini', 'easy'],
  ['Stalin', 'Lenin', 'easy'],
  ['Alexander the Great', 'Genghis Khan', 'easy'],
  ['Washington', 'Lincoln', 'easy'],
  ['Kennedy', 'Obama', 'easy'],
  ['Churchill', 'De Gaulle', 'easy'],
  ['Einstein', 'Newton', 'easy'],
  ['Galileo', 'Copernicus', 'easy'],
  ['Columbus', 'Magellan', 'easy'],
  ['Mozart', 'Beethoven', 'easy'],
  ['Da Vinci', 'Michelangelo', 'easy'],
  ['Gandhi', 'Mandela', 'easy'],
  ['Cleopatra', 'Nefertiti', 'easy'],
  ['Joan of Arc', 'Boudica', 'easy'],
  // Medium (25)
  ['Marco Polo', 'Ibn Battuta', 'medium'],
  ['Vasco da Gama', 'Ferdinand Magellan', 'medium'],
  ['Captain Cook', 'Henry Hudson', 'medium'],
  ['Neil Armstrong', 'Yuri Gagarin', 'medium'],
  ['Buzz Aldrin', 'Michael Collins', 'medium'],
  ['Marie Curie', 'Rosalind Franklin', 'medium'],
  ['Ada Lovelace', 'Grace Hopper', 'medium'],
  ['Tesla', 'Edison', 'medium'],
  ['Wright Brothers', 'Zeppelin', 'medium'],
  ['Darwin', 'Mendel', 'medium'],
  ['Pasteur', 'Fleming', 'medium'],
  ['Freud', 'Jung', 'medium'],
  ['Plato', 'Aristotle', 'medium'],
  ['Socrates', 'Confucius', 'medium'],
  ['Marcus Aurelius', 'Seneca', 'medium'],
  ['Augustus', 'Trajan', 'medium'],
  ['Hannibal', 'Scipio', 'medium'],
  ['Alaric', 'Attila', 'medium'],
  ['Charlemagne', 'Otto', 'medium'],
  ['Henry VIII', 'Elizabeth I', 'medium'],
  ['Louis XIV', 'Louis XVI', 'medium'],
  ['Marie Antoinette', 'Catherine the Great', 'medium'],
  ['Peter the Great', 'Ivan the Terrible', 'medium'],
  ['Bismarck', 'Metternich', 'medium'],
  ['Robespierre', 'Danton', 'medium'],
  // Hard (10)
  ['Saladin', 'Richard the Lionheart', 'hard'],
  ['Suleiman', 'Akbar', 'hard'],
  ['Zheng He', 'Kublai Khan', 'hard'],
  ['Sun Tzu', 'Machiavelli', 'hard'],
  ['Lao Tzu', 'Buddha', 'hard'],
  ['Pythagoras', 'Archimedes', 'hard'],
  ['Kepler', 'Tycho Brahe', 'hard'],
  ['Mendeleev', 'Lavoisier', 'hard'],
  ['Turing', 'Von Neumann', 'hard'],
  ['Nikola Tesla', 'Guglielmo Marconi', 'hard'],
]

// ═════════════════════════════════════════════════════════════════════════
// TRANSLATABLE CATEGORIES — one entry per locale, index-aligned
// ═════════════════════════════════════════════════════════════════════════

type TrPack = Record<string, Triple[]>

const TR_FOOD: TrPack = {
  en: [
    ['Espresso','Ristretto','easy'],['Latte','Cappuccino','easy'],['Pizza','Calzone','easy'],['Burger','Sandwich','easy'],['Hot Dog','Sausage','easy'],
    ['Sushi','Sashimi','easy'],['Ramen','Udon','easy'],['Fries','Chips','easy'],['Pasta','Noodles','easy'],['Cake','Pie','easy'],
    ['Ice Cream','Sorbet','easy'],['Pancake','Waffle','easy'],['Donut','Bagel','easy'],['Cookie','Biscuit','easy'],['Muffin','Cupcake','easy'],
    ['Brownie','Blondie','medium'],['Tiramisu','Cheesecake','medium'],['Croissant','Brioche','medium'],['Baguette','Ciabatta','medium'],['Sourdough','Rye Bread','medium'],
    ['Omelette','Frittata','medium'],['Scrambled Eggs','Poached Eggs','medium'],['Crepe','Galette','medium'],['Risotto','Paella','medium'],['Lasagna','Cannelloni','medium'],
    ['Spaghetti','Linguine','medium'],['Ravioli','Tortellini','medium'],['Pho','Laksa','medium'],['Dumpling','Gyoza','medium'],['Spring Roll','Egg Roll','medium'],
    ['Tempura','Katsu','medium'],['Burrito','Taco','medium'],['Quesadilla','Enchilada','medium'],['Guacamole','Salsa','medium'],['Hummus','Baba Ganoush','medium'],
    ['Kebab','Shawarma','medium'],['Falafel','Kofta','medium'],['Curry','Tikka Masala','medium'],['Biryani','Pilaf','medium'],['Peking Duck','Roast Chicken','medium'],
    ['Foie Gras','Pate','hard'],['Caviar','Roe','hard'],['Truffle','Porcini','hard'],['Lobster','Crayfish','hard'],['Oyster','Mussel','hard'],
    ['Prosciutto','Serrano','hard'],['Gruyere','Emmental','hard'],['Brie','Camembert','hard'],['Gouda','Edam','hard'],['Mozzarella','Burrata','hard'],
  ],
  fr: [
    ['Expresso','Ristretto','easy'],['Latte','Cappuccino','easy'],['Pizza','Calzone','easy'],['Burger','Sandwich','easy'],['Hot-Dog','Saucisse','easy'],
    ['Sushi','Sashimi','easy'],['Ramen','Udon','easy'],['Frites','Chips','easy'],['Pâtes','Nouilles','easy'],['Gâteau','Tarte','easy'],
    ['Glace','Sorbet','easy'],['Crêpe','Gaufre','easy'],['Beignet','Bagel','easy'],['Cookie','Biscuit','easy'],['Muffin','Cupcake','easy'],
    ['Brownie','Blondie','medium'],['Tiramisu','Cheesecake','medium'],['Croissant','Brioche','medium'],['Baguette','Ciabatta','medium'],['Pain au Levain','Pain de Seigle','medium'],
    ['Omelette','Frittata','medium'],['Œufs Brouillés','Œufs Pochés','medium'],['Crêpe','Galette','medium'],['Risotto','Paella','medium'],['Lasagne','Cannelloni','medium'],
    ['Spaghetti','Linguine','medium'],['Ravioli','Tortellini','medium'],['Pho','Laksa','medium'],['Raviole','Gyoza','medium'],['Nem','Rouleau de Printemps','medium'],
    ['Tempura','Katsu','medium'],['Burrito','Taco','medium'],['Quesadilla','Enchilada','medium'],['Guacamole','Salsa','medium'],['Houmous','Baba Ganoush','medium'],
    ['Kebab','Shawarma','medium'],['Falafel','Kofta','medium'],['Curry','Tikka Masala','medium'],['Biryani','Pilaf','medium'],['Canard Laqué','Poulet Rôti','medium'],
    ['Foie Gras','Pâté','hard'],['Caviar','Œufs de Poisson','hard'],['Truffe','Cèpe','hard'],['Homard','Écrevisse','hard'],['Huître','Moule','hard'],
    ['Jambon de Parme','Serrano','hard'],['Gruyère','Emmental','hard'],['Brie','Camembert','hard'],['Gouda','Edam','hard'],['Mozzarella','Burrata','hard'],
  ],
  es: [
    ['Espresso','Ristretto','easy'],['Latte','Capuchino','easy'],['Pizza','Calzone','easy'],['Hamburguesa','Sándwich','easy'],['Perrito Caliente','Salchicha','easy'],
    ['Sushi','Sashimi','easy'],['Ramen','Udon','easy'],['Papas Fritas','Patatas Fritas','easy'],['Pasta','Fideos','easy'],['Tarta','Pastel','easy'],
    ['Helado','Sorbete','easy'],['Panqueque','Gofre','easy'],['Donut','Bagel','easy'],['Galleta','Bizcocho','easy'],['Magdalena','Cupcake','easy'],
    ['Brownie','Blondie','medium'],['Tiramisú','Cheesecake','medium'],['Cruasán','Brioche','medium'],['Baguette','Ciabatta','medium'],['Pan de Masa Madre','Pan de Centeno','medium'],
    ['Tortilla','Frittata','medium'],['Huevos Revueltos','Huevos Escalfados','medium'],['Crepe','Galette','medium'],['Risotto','Paella','medium'],['Lasaña','Canelones','medium'],
    ['Espagueti','Linguine','medium'],['Ravioli','Tortellini','medium'],['Pho','Laksa','medium'],['Empanadilla','Gyoza','medium'],['Rollito de Primavera','Rollito de Huevo','medium'],
    ['Tempura','Katsu','medium'],['Burrito','Taco','medium'],['Quesadilla','Enchilada','medium'],['Guacamole','Salsa','medium'],['Hummus','Baba Ganoush','medium'],
    ['Kebab','Shawarma','medium'],['Falafel','Kofta','medium'],['Curry','Tikka Masala','medium'],['Biryani','Pilaf','medium'],['Pato Pekín','Pollo Asado','medium'],
    ['Foie Gras','Paté','hard'],['Caviar','Hueva','hard'],['Trufa','Porcini','hard'],['Langosta','Cangrejo de Río','hard'],['Ostra','Mejillón','hard'],
    ['Prosciutto','Serrano','hard'],['Gruyere','Emmental','hard'],['Brie','Camembert','hard'],['Gouda','Edam','hard'],['Mozzarella','Burrata','hard'],
  ],
  de: [
    ['Espresso','Ristretto','easy'],['Latte','Cappuccino','easy'],['Pizza','Calzone','easy'],['Burger','Sandwich','easy'],['Hot Dog','Wurst','easy'],
    ['Sushi','Sashimi','easy'],['Ramen','Udon','easy'],['Pommes','Chips','easy'],['Pasta','Nudeln','easy'],['Kuchen','Torte','easy'],
    ['Eis','Sorbet','easy'],['Pfannkuchen','Waffel','easy'],['Donut','Bagel','easy'],['Keks','Plätzchen','easy'],['Muffin','Cupcake','easy'],
    ['Brownie','Blondie','medium'],['Tiramisu','Käsekuchen','medium'],['Croissant','Brioche','medium'],['Baguette','Ciabatta','medium'],['Sauerteigbrot','Roggenbrot','medium'],
    ['Omelett','Frittata','medium'],['Rührei','Pochiertes Ei','medium'],['Crêpe','Galette','medium'],['Risotto','Paella','medium'],['Lasagne','Cannelloni','medium'],
    ['Spaghetti','Linguine','medium'],['Ravioli','Tortellini','medium'],['Pho','Laksa','medium'],['Maultasche','Gyoza','medium'],['Frühlingsrolle','Ei-Rolle','medium'],
    ['Tempura','Katsu','medium'],['Burrito','Taco','medium'],['Quesadilla','Enchilada','medium'],['Guacamole','Salsa','medium'],['Hummus','Baba Ganoush','medium'],
    ['Kebab','Schawarma','medium'],['Falafel','Kofta','medium'],['Curry','Tikka Masala','medium'],['Biryani','Pilaw','medium'],['Pekingente','Brathähnchen','medium'],
    ['Foie Gras','Pastete','hard'],['Kaviar','Fischrogen','hard'],['Trüffel','Steinpilz','hard'],['Hummer','Flusskrebs','hard'],['Auster','Muschel','hard'],
    ['Prosciutto','Serrano','hard'],['Gruyère','Emmentaler','hard'],['Brie','Camembert','hard'],['Gouda','Edamer','hard'],['Mozzarella','Burrata','hard'],
  ],
  ar: [
    ['إسبريسو','ريستريتو','easy'],['لاتيه','كابتشينو','easy'],['بيتزا','كالزوني','easy'],['برغر','ساندويتش','easy'],['هوت دوغ','سجق','easy'],
    ['سوشي','ساشيمي','easy'],['رامن','أودون','easy'],['بطاطس مقلية','رقائق البطاطس','easy'],['باستا','نودلز','easy'],['كعكة','فطيرة','easy'],
    ['آيس كريم','سوربيه','easy'],['بانكيك','وافل','easy'],['دوناتس','خبز الكعك','easy'],['كوكيز','بسكويت','easy'],['مافن','كب كيك','easy'],
    ['براوني','بلوندي','medium'],['تيراميسو','تشيز كيك','medium'],['كرواسون','بريوش','medium'],['باجيت','تشاباتا','medium'],['خبز العجين المخمر','خبز الجاودار','medium'],
    ['عجة','فريتاتا','medium'],['بيض مخفوق','بيض مسلوق','medium'],['كريب','جاليت','medium'],['ريزوتو','باييا','medium'],['لازانيا','كانيلوني','medium'],
    ['سباغيتي','لينغويني','medium'],['رافيولي','تورتيليني','medium'],['فو','لاكسا','medium'],['فطيرة صينية','جيوزا','medium'],['سبرينغ رول','إيغ رول','medium'],
    ['تيمبورا','كاتسو','medium'],['بوريتو','تاكو','medium'],['كيساديلا','إنشيلادا','medium'],['جواكامولي','صلصة','medium'],['حمص','بابا غنوج','medium'],
    ['كباب','شاورما','medium'],['فلافل','كفتة','medium'],['كاري','تيكا ماسالا','medium'],['برياني','بيلاف','medium'],['بط بكين','دجاج مشوي','medium'],
    ['كبد الإوز','باتيه','hard'],['كافيار','بيض السمك','hard'],['كمأة','فطر بورسيني','hard'],['كركند','سلطعون النهر','hard'],['محار','بلح البحر','hard'],
    ['بروشوتو','سيرانو','hard'],['جروير','إيمنتال','hard'],['بري','كامامبير','hard'],['غودا','إيدام','hard'],['موتزاريلا','بوراتا','hard'],
  ],
  it: [
    ['Espresso','Ristretto','easy'],['Latte','Cappuccino','easy'],['Pizza','Calzone','easy'],['Hamburger','Tramezzino','easy'],['Hot Dog','Salsiccia','easy'],
    ['Sushi','Sashimi','easy'],['Ramen','Udon','easy'],['Patatine Fritte','Patatine','easy'],['Pasta','Spaghetti','easy'],['Torta','Crostata','easy'],
    ['Gelato','Sorbetto','easy'],['Pancake','Waffle','easy'],['Ciambella','Bagel','easy'],['Biscotto','Frollino','easy'],['Muffin','Cupcake','easy'],
    ['Brownie','Blondie','medium'],['Tiramisù','Cheesecake','medium'],['Cornetto','Brioche','medium'],['Baguette','Ciabatta','medium'],['Pane a Lievito Madre','Pane di Segale','medium'],
    ['Omelette','Frittata','medium'],['Uova Strapazzate','Uova in Camicia','medium'],['Crêpe','Galette','medium'],['Risotto','Paella','medium'],['Lasagne','Cannelloni','medium'],
    ['Spaghetti','Linguine','medium'],['Ravioli','Tortellini','medium'],['Pho','Laksa','medium'],['Gnocco','Gyoza','medium'],['Involtino Primavera','Rotolo d\'Uovo','medium'],
    ['Tempura','Katsu','medium'],['Burrito','Taco','medium'],['Quesadilla','Enchilada','medium'],['Guacamole','Salsa','medium'],['Hummus','Baba Ganoush','medium'],
    ['Kebab','Shawarma','medium'],['Falafel','Kofta','medium'],['Curry','Tikka Masala','medium'],['Biryani','Pilaf','medium'],['Anatra alla Pechinese','Pollo Arrosto','medium'],
    ['Foie Gras','Paté','hard'],['Caviale','Uova di Pesce','hard'],['Tartufo','Porcino','hard'],['Aragosta','Gambero','hard'],['Ostrica','Cozza','hard'],
    ['Prosciutto','Serrano','hard'],['Gruyère','Emmental','hard'],['Brie','Camembert','hard'],['Gouda','Edam','hard'],['Mozzarella','Burrata','hard'],
  ],
  pt: [
    ['Expresso','Ristretto','easy'],['Latte','Cappuccino','easy'],['Pizza','Calzone','easy'],['Hambúrguer','Sanduíche','easy'],['Cachorro Quente','Salsicha','easy'],
    ['Sushi','Sashimi','easy'],['Lámen','Udon','easy'],['Batata Frita','Chips','easy'],['Macarrão','Talharim','easy'],['Bolo','Torta','easy'],
    ['Sorvete','Sorbet','easy'],['Panqueca','Waffle','easy'],['Rosquinha','Bagel','easy'],['Biscoito','Bolacha','easy'],['Muffin','Cupcake','easy'],
    ['Brownie','Blondie','medium'],['Tiramisu','Cheesecake','medium'],['Croissant','Brioche','medium'],['Baguete','Ciabatta','medium'],['Pão de Fermentação Natural','Pão de Centeio','medium'],
    ['Omelete','Frittata','medium'],['Ovos Mexidos','Ovos Pochê','medium'],['Crepe','Galette','medium'],['Risoto','Paella','medium'],['Lasanha','Canelone','medium'],
    ['Espaguete','Linguine','medium'],['Ravióli','Tortellini','medium'],['Pho','Laksa','medium'],['Pastel','Gyoza','medium'],['Rolinho Primavera','Rolinho de Ovo','medium'],
    ['Tempura','Katsu','medium'],['Burrito','Taco','medium'],['Quesadilla','Enchilada','medium'],['Guacamole','Salsa','medium'],['Homus','Baba Ganoush','medium'],
    ['Kebab','Shawarma','medium'],['Falafel','Kofta','medium'],['Curry','Tikka Masala','medium'],['Biryani','Pilaf','medium'],['Pato de Pequim','Frango Assado','medium'],
    ['Foie Gras','Patê','hard'],['Caviar','Ovas','hard'],['Trufa','Porcini','hard'],['Lagosta','Lagostim','hard'],['Ostra','Mexilhão','hard'],
    ['Presunto de Parma','Serrano','hard'],['Gruyère','Emmental','hard'],['Brie','Camembert','hard'],['Gouda','Edam','hard'],['Mussarela','Burrata','hard'],
  ],
  zh: [
    ['浓缩咖啡','瑞斯崔朵','easy'],['拿铁','卡布奇诺','easy'],['披萨','卡尔佐内','easy'],['汉堡','三明治','easy'],['热狗','香肠','easy'],
    ['寿司','刺身','easy'],['拉面','乌冬面','easy'],['薯条','薯片','easy'],['意大利面','面条','easy'],['蛋糕','派','easy'],
    ['冰淇淋','雪葩','easy'],['煎饼','华夫饼','easy'],['甜甜圈','贝果','easy'],['曲奇','饼干','easy'],['松饼','纸杯蛋糕','easy'],
    ['布朗尼','金发女郎蛋糕','medium'],['提拉米苏','芝士蛋糕','medium'],['牛角包','布里欧修','medium'],['法棍','恰巴塔','medium'],['酸面包','黑麦面包','medium'],
    ['煎蛋卷','意式烘蛋','medium'],['炒蛋','水波蛋','medium'],['可丽饼','加莱特','medium'],['烩饭','海鲜饭','medium'],['千层面','烤通心粉','medium'],
    ['意面','扁面条','medium'],['意式饺子','意式馄饨','medium'],['越南河粉','叻沙','medium'],['饺子','煎饺','medium'],['春卷','蛋卷','medium'],
    ['天妇罗','日式炸猪排','medium'],['卷饼','玉米饼','medium'],['墨西哥披萨','墨西哥卷饼','medium'],['鳄梨酱','莎莎酱','medium'],['鹰嘴豆泥','茄子酱','medium'],
    ['烤肉串','沙瓦玛','medium'],['炸鹰嘴豆','肉丸','medium'],['咖喱','马萨拉咖喱','medium'],['印度香饭','抓饭','medium'],['北京烤鸭','烤鸡','medium'],
    ['鹅肝','肉酱','hard'],['鱼子酱','鱼卵','hard'],['松露','牛肝菌','hard'],['龙虾','小龙虾','hard'],['牡蛎','贻贝','hard'],
    ['帕尔马火腿','塞拉诺火腿','hard'],['格鲁耶尔','埃门塔尔','hard'],['布里','卡芒贝尔','hard'],['高达','埃达姆','hard'],['马苏里拉','布拉塔','hard'],
  ],
}
const TR_ANIMALS: TrPack = {
  en: [
    ['Jaguar','Leopard','easy'],['Cheetah','Panther','easy'],['Alligator','Crocodile','easy'],['Dolphin','Whale','easy'],['Shark','Barracuda','easy'],
    ['Eagle','Hawk','easy'],['Owl','Falcon','easy'],['Raven','Crow','easy'],['Duck','Goose','easy'],['Swan','Pelican','easy'],
    ['Rabbit','Hare','easy'],['Squirrel','Chipmunk','easy'],['Mouse','Rat','easy'],['Hamster','Guinea Pig','easy'],['Ferret','Weasel','easy'],
    ['Wolf','Coyote','medium'],['Fox','Jackal','medium'],['Lynx','Bobcat','medium'],['Puma','Cougar','medium'],['Bison','Buffalo','medium'],
    ['Moose','Elk','medium'],['Reindeer','Caribou','medium'],['Goat','Sheep','medium'],['Llama','Alpaca','medium'],['Camel','Dromedary','medium'],
    ['Gorilla','Chimpanzee','medium'],['Orangutan','Baboon','medium'],['Lemur','Marmoset','medium'],['Koala','Sloth','medium'],['Kangaroo','Wallaby','medium'],
    ['Tortoise','Turtle','medium'],['Iguana','Gecko','medium'],['Cobra','Viper','medium'],['Python','Anaconda','medium'],['Salamander','Newt','medium'],
    ['Octopus','Squid','medium'],['Lobster','Crab','medium'],['Jellyfish','Sea Anemone','medium'],['Seahorse','Pipefish','medium'],['Starfish','Sea Urchin','medium'],
    ['Platypus','Echidna','hard'],['Aardvark','Armadillo','hard'],['Tapir','Capybara','hard'],['Meerkat','Mongoose','hard'],['Okapi','Giraffe','hard'],
    ['Narwhal','Beluga','hard'],['Manatee','Dugong','hard'],['Axolotl','Olm','hard'],['Tarsier','Loris','hard'],['Pangolin','Anteater','hard'],
  ],
  fr: [
    ['Jaguar','Léopard','easy'],['Guépard','Panthère','easy'],['Alligator','Crocodile','easy'],['Dauphin','Baleine','easy'],['Requin','Barracuda','easy'],
    ['Aigle','Faucon','easy'],['Hibou','Buse','easy'],['Corbeau','Corneille','easy'],['Canard','Oie','easy'],['Cygne','Pélican','easy'],
    ['Lapin','Lièvre','easy'],['Écureuil','Tamia','easy'],['Souris','Rat','easy'],['Hamster','Cochon d\'Inde','easy'],['Furet','Belette','easy'],
    ['Loup','Coyote','medium'],['Renard','Chacal','medium'],['Lynx','Bobcat','medium'],['Puma','Couguar','medium'],['Bison','Buffle','medium'],
    ['Orignal','Élan','medium'],['Renne','Caribou','medium'],['Chèvre','Mouton','medium'],['Lama','Alpaga','medium'],['Chameau','Dromadaire','medium'],
    ['Gorille','Chimpanzé','medium'],['Orang-outan','Babouin','medium'],['Lémurien','Ouistiti','medium'],['Koala','Paresseux','medium'],['Kangourou','Wallaby','medium'],
    ['Tortue terrestre','Tortue marine','medium'],['Iguane','Gecko','medium'],['Cobra','Vipère','medium'],['Python','Anaconda','medium'],['Salamandre','Triton','medium'],
    ['Pieuvre','Calamar','medium'],['Homard','Crabe','medium'],['Méduse','Anémone','medium'],['Hippocampe','Syngnathe','medium'],['Étoile de Mer','Oursin','medium'],
    ['Ornithorynque','Échidné','hard'],['Oryctérope','Tatou','hard'],['Tapir','Capybara','hard'],['Suricate','Mangouste','hard'],['Okapi','Girafe','hard'],
    ['Narval','Béluga','hard'],['Lamantin','Dugong','hard'],['Axolotl','Protée','hard'],['Tarsier','Loris','hard'],['Pangolin','Tamanoir','hard'],
  ],
  es: [
    ['Jaguar','Leopardo','easy'],['Guepardo','Pantera','easy'],['Aligátor','Cocodrilo','easy'],['Delfín','Ballena','easy'],['Tiburón','Barracuda','easy'],
    ['Águila','Halcón','easy'],['Búho','Lechuza','easy'],['Cuervo','Corneja','easy'],['Pato','Ganso','easy'],['Cisne','Pelícano','easy'],
    ['Conejo','Liebre','easy'],['Ardilla','Tamia','easy'],['Ratón','Rata','easy'],['Hámster','Cobaya','easy'],['Hurón','Comadreja','easy'],
    ['Lobo','Coyote','medium'],['Zorro','Chacal','medium'],['Lince','Gato Montés','medium'],['Puma','Jaguar','medium'],['Bisonte','Búfalo','medium'],
    ['Alce','Ciervo','medium'],['Reno','Caribú','medium'],['Cabra','Oveja','medium'],['Llama','Alpaca','medium'],['Camello','Dromedario','medium'],
    ['Gorila','Chimpancé','medium'],['Orangután','Babuino','medium'],['Lémur','Marmoseta','medium'],['Koala','Perezoso','medium'],['Canguro','Ualabí','medium'],
    ['Tortuga Terrestre','Tortuga Marina','medium'],['Iguana','Gecko','medium'],['Cobra','Víbora','medium'],['Pitón','Anaconda','medium'],['Salamandra','Tritón','medium'],
    ['Pulpo','Calamar','medium'],['Langosta','Cangrejo','medium'],['Medusa','Anémona','medium'],['Caballito de Mar','Pez Pipa','medium'],['Estrella de Mar','Erizo de Mar','medium'],
    ['Ornitorrinco','Equidna','hard'],['Oso Hormiguero','Armadillo','hard'],['Tapir','Capibara','hard'],['Suricata','Mangosta','hard'],['Okapi','Jirafa','hard'],
    ['Narval','Beluga','hard'],['Manatí','Dugón','hard'],['Ajolote','Proteo','hard'],['Tarsero','Loris','hard'],['Pangolín','Oso Hormiguero Gigante','hard'],
  ],
  de: [
    ['Jaguar','Leopard','easy'],['Gepard','Panther','easy'],['Alligator','Krokodil','easy'],['Delfin','Wal','easy'],['Hai','Barrakuda','easy'],
    ['Adler','Falke','easy'],['Eule','Bussard','easy'],['Rabe','Krähe','easy'],['Ente','Gans','easy'],['Schwan','Pelikan','easy'],
    ['Kaninchen','Hase','easy'],['Eichhörnchen','Streifenhörnchen','easy'],['Maus','Ratte','easy'],['Hamster','Meerschweinchen','easy'],['Frettchen','Wiesel','easy'],
    ['Wolf','Kojote','medium'],['Fuchs','Schakal','medium'],['Luchs','Rotluchs','medium'],['Puma','Berglöwe','medium'],['Bison','Büffel','medium'],
    ['Elch','Rothirsch','medium'],['Rentier','Karibu','medium'],['Ziege','Schaf','medium'],['Lama','Alpaka','medium'],['Kamel','Dromedar','medium'],
    ['Gorilla','Schimpanse','medium'],['Orang-Utan','Pavian','medium'],['Lemur','Marmoset','medium'],['Koala','Faultier','medium'],['Känguru','Wallaby','medium'],
    ['Landschildkröte','Meeresschildkröte','medium'],['Leguan','Gecko','medium'],['Kobra','Viper','medium'],['Python','Anakonda','medium'],['Salamander','Molch','medium'],
    ['Krake','Tintenfisch','medium'],['Hummer','Krabbe','medium'],['Qualle','Seeanemone','medium'],['Seepferdchen','Nadelfisch','medium'],['Seestern','Seeigel','medium'],
    ['Schnabeltier','Ameisenigel','hard'],['Erdferkel','Gürteltier','hard'],['Tapir','Wasserschwein','hard'],['Erdmännchen','Mungo','hard'],['Okapi','Giraffe','hard'],
    ['Narwal','Beluga','hard'],['Seekuh','Dugong','hard'],['Axolotl','Grottenolm','hard'],['Koboldmaki','Lori','hard'],['Schuppentier','Ameisenbär','hard'],
  ],
  ar: [
    ['جاغوار','فهد صياد','easy'],['فهد','نمر أسود','easy'],['تمساح أمريكي','تمساح','easy'],['دلفين','حوت','easy'],['قرش','باراكودا','easy'],
    ['نسر','صقر','easy'],['بومة','باشق','easy'],['غراب','غراب أسود','easy'],['بطة','إوزة','easy'],['بجعة','بجع','easy'],
    ['أرنب','أرنب بري','easy'],['سنجاب','سنجاب مخطط','easy'],['فأر','جرذ','easy'],['هامستر','خنزير غينيا','easy'],['ابن عرس','ابن مقرض','easy'],
    ['ذئب','ذئب البراري','medium'],['ثعلب','ابن آوى','medium'],['وشق','قط بري','medium'],['كوجر','أسد جبلي','medium'],['بيسون','جاموس','medium'],
    ['موس','أيل','medium'],['رنة','كاريبو','medium'],['ماعز','خروف','medium'],['لاما','ألبكة','medium'],['جمل','جمل وحيد السنام','medium'],
    ['غوريلا','شمبانزي','medium'],['إنسان الغاب','بابون','medium'],['ليمور','قرد مرموسيت','medium'],['كوالا','كسلان','medium'],['كنغر','ولب','medium'],
    ['سلحفاة برية','سلحفاة بحرية','medium'],['إغوانا','أبو بريص','medium'],['كوبرا','أفعى','medium'],['بايثون','أناكوندا','medium'],['سلمندر','نيوت','medium'],
    ['أخطبوط','حبار','medium'],['كركند','سرطان البحر','medium'],['قنديل البحر','شقائق البحر','medium'],['فرس البحر','سمك الأنبوب','medium'],['نجم البحر','قنفذ البحر','medium'],
    ['خلد الماء','إكيدنا','hard'],['خنزير الأرض','مدرع','hard'],['تابير','كابيبارا','hard'],['ميركات','نمس','hard'],['أوكابي','زرافة','hard'],
    ['نرفال','بيلوغا','hard'],['أطوم','دوغونغ','hard'],['أكسولوتل','أولم','hard'],['ترسير','لوريس','hard'],['بنغولين','آكل النمل','hard'],
  ],
  it: [
    ['Giaguaro','Leopardo','easy'],['Ghepardo','Pantera','easy'],['Alligatore','Coccodrillo','easy'],['Delfino','Balena','easy'],['Squalo','Barracuda','easy'],
    ['Aquila','Falco','easy'],['Gufo','Poiana','easy'],['Corvo','Cornacchia','easy'],['Anatra','Oca','easy'],['Cigno','Pellicano','easy'],
    ['Coniglio','Lepre','easy'],['Scoiattolo','Tamia','easy'],['Topo','Ratto','easy'],['Criceto','Porcellino d\'India','easy'],['Furetto','Donnola','easy'],
    ['Lupo','Coyote','medium'],['Volpe','Sciacallo','medium'],['Lince','Gatto Selvatico','medium'],['Puma','Coguaro','medium'],['Bisonte','Bufalo','medium'],
    ['Alce','Cervo','medium'],['Renna','Caribù','medium'],['Capra','Pecora','medium'],['Lama','Alpaca','medium'],['Cammello','Dromedario','medium'],
    ['Gorilla','Scimpanzé','medium'],['Orango','Babbuino','medium'],['Lemure','Marmoset','medium'],['Koala','Bradipo','medium'],['Canguro','Wallaby','medium'],
    ['Tartaruga di Terra','Tartaruga Marina','medium'],['Iguana','Geco','medium'],['Cobra','Vipera','medium'],['Pitone','Anaconda','medium'],['Salamandra','Tritone','medium'],
    ['Polpo','Calamaro','medium'],['Aragosta','Granchio','medium'],['Medusa','Anemone','medium'],['Cavalluccio Marino','Pesce Ago','medium'],['Stella Marina','Riccio di Mare','medium'],
    ['Ornitorinco','Echidna','hard'],['Oritteropo','Armadillo','hard'],['Tapiro','Capibara','hard'],['Suricata','Mangusta','hard'],['Okapi','Giraffa','hard'],
    ['Narvalo','Beluga','hard'],['Lamantino','Dugongo','hard'],['Axolotl','Proteo','hard'],['Tarsio','Lori','hard'],['Pangolino','Formichiere','hard'],
  ],
  pt: [
    ['Jaguar','Leopardo','easy'],['Chita','Pantera','easy'],['Jacaré','Crocodilo','easy'],['Golfinho','Baleia','easy'],['Tubarão','Barracuda','easy'],
    ['Águia','Falcão','easy'],['Coruja','Gavião','easy'],['Corvo','Gralha','easy'],['Pato','Ganso','easy'],['Cisne','Pelicano','easy'],
    ['Coelho','Lebre','easy'],['Esquilo','Tâmia','easy'],['Rato','Ratazana','easy'],['Hamster','Porquinho-da-índia','easy'],['Furão','Doninha','easy'],
    ['Lobo','Coiote','medium'],['Raposa','Chacal','medium'],['Lince','Gato Selvagem','medium'],['Puma','Suçuarana','medium'],['Bisão','Búfalo','medium'],
    ['Alce','Cervo','medium'],['Rena','Caribu','medium'],['Cabra','Ovelha','medium'],['Lhama','Alpaca','medium'],['Camelo','Dromedário','medium'],
    ['Gorila','Chimpanzé','medium'],['Orangotango','Babuíno','medium'],['Lêmure','Sagui','medium'],['Coala','Bicho-preguiça','medium'],['Canguru','Ualabi','medium'],
    ['Tartaruga Terrestre','Tartaruga Marinha','medium'],['Iguana','Lagartixa','medium'],['Cobra','Víbora','medium'],['Píton','Anaconda','medium'],['Salamandra','Tritão','medium'],
    ['Polvo','Lula','medium'],['Lagosta','Caranguejo','medium'],['Água-viva','Anémona','medium'],['Cavalo-marinho','Peixe-cachimbo','medium'],['Estrela-do-mar','Ouriço-do-mar','medium'],
    ['Ornitorrinco','Equidna','hard'],['Porco-da-terra','Tatu','hard'],['Tapir','Capivara','hard'],['Suricato','Mangusto','hard'],['Okapi','Girafa','hard'],
    ['Narval','Beluga','hard'],['Peixe-boi','Dugongo','hard'],['Axolote','Próteo','hard'],['Társio','Lóris','hard'],['Pangolim','Tamanduá','hard'],
  ],
  zh: [
    ['美洲豹','豹','easy'],['猎豹','黑豹','easy'],['短吻鳄','鳄鱼','easy'],['海豚','鲸鱼','easy'],['鲨鱼','梭鱼','easy'],
    ['鹰','隼','easy'],['猫头鹰','鵟','easy'],['乌鸦','渡鸦','easy'],['鸭子','鹅','easy'],['天鹅','鹈鹕','easy'],
    ['兔子','野兔','easy'],['松鼠','花栗鼠','easy'],['老鼠','大鼠','easy'],['仓鼠','豚鼠','easy'],['雪貂','黄鼠狼','easy'],
    ['狼','郊狼','medium'],['狐狸','豺','medium'],['猞猁','山猫','medium'],['美洲狮','美洲山狮','medium'],['野牛','水牛','medium'],
    ['驼鹿','麋鹿','medium'],['驯鹿','加拿大驯鹿','medium'],['山羊','绵羊','medium'],['美洲驼','羊驼','medium'],['骆驼','单峰骆驼','medium'],
    ['大猩猩','黑猩猩','medium'],['猩猩','狒狒','medium'],['狐猴','狨猴','medium'],['考拉','树懒','medium'],['袋鼠','沙袋鼠','medium'],
    ['陆龟','海龟','medium'],['鬣蜥','壁虎','medium'],['眼镜蛇','蝰蛇','medium'],['蟒蛇','森蚺','medium'],['火蜥蜴','蝾螈','medium'],
    ['章鱼','鱿鱼','medium'],['龙虾','螃蟹','medium'],['水母','海葵','medium'],['海马','海龙','medium'],['海星','海胆','medium'],
    ['鸭嘴兽','针鼹','hard'],['土豚','犰狳','hard'],['貘','水豚','hard'],['猫鼬','獴','hard'],['霍加狓','长颈鹿','hard'],
    ['独角鲸','白鲸','hard'],['海牛','儒艮','hard'],['蝾螈','洞螈','hard'],['眼镜猴','懒猴','hard'],['穿山甲','食蚁兽','hard'],
  ],
}
const TR_PLACES: TrPack = {
  en: [
    ['Paris','London','easy'],['Tokyo','Kyoto','easy'],['Rome','Athens','easy'],['Madrid','Barcelona','easy'],['Berlin','Munich','easy'],
    ['New York','Los Angeles','easy'],['Chicago','Boston','easy'],['Dubai','Abu Dhabi','easy'],['Moscow','Saint Petersburg','easy'],['Beijing','Shanghai','easy'],
    ['Egypt','Morocco','easy'],['Brazil','Argentina','easy'],['Japan','Korea','easy'],['Italy','Greece','easy'],['Spain','Portugal','easy'],
    ['Eiffel Tower','Big Ben','medium'],['Statue of Liberty','Christ the Redeemer','medium'],['Colosseum','Parthenon','medium'],['Taj Mahal','Pyramids','medium'],['Great Wall','Terracotta Army','medium'],
    ['Louvre','British Museum','medium'],['MoMA','Tate Modern','medium'],['Notre Dame','Sacre Coeur','medium'],['Sagrada Familia','Alhambra','medium'],['Hagia Sophia','Blue Mosque','medium'],
    ['Mount Everest','K2','medium'],['Kilimanjaro','Mont Blanc','medium'],['Sahara','Gobi','medium'],['Amazon','Congo','medium'],['Nile','Mississippi','medium'],
    ['Grand Canyon','Yosemite','medium'],['Niagara Falls','Victoria Falls','medium'],['Great Barrier Reef','Galapagos','medium'],['Serengeti','Kruger','medium'],['Patagonia','Fjords','medium'],
    ['Venice','Amsterdam','medium'],['Prague','Vienna','medium'],['Stockholm','Helsinki','medium'],['Copenhagen','Oslo','medium'],['Budapest','Warsaw','medium'],
    ['Reykjavik','Lofoten','hard'],['Santorini','Mykonos','hard'],['Maldives','Seychelles','hard'],['Zanzibar','Mauritius','hard'],['Petra','Palmyra','hard'],
    ['Machu Picchu','Chichen Itza','hard'],['Angkor Wat','Borobudur','hard'],['Easter Island','Stonehenge','hard'],['Timbuktu','Samarkand','hard'],['Bhutan','Nepal','hard'],
  ],
  fr: [
    ['Paris','Londres','easy'],['Tokyo','Kyoto','easy'],['Rome','Athènes','easy'],['Madrid','Barcelone','easy'],['Berlin','Munich','easy'],
    ['New York','Los Angeles','easy'],['Chicago','Boston','easy'],['Dubaï','Abu Dhabi','easy'],['Moscou','Saint-Pétersbourg','easy'],['Pékin','Shanghai','easy'],
    ['Égypte','Maroc','easy'],['Brésil','Argentine','easy'],['Japon','Corée','easy'],['Italie','Grèce','easy'],['Espagne','Portugal','easy'],
    ['Tour Eiffel','Big Ben','medium'],['Statue de la Liberté','Christ Rédempteur','medium'],['Colisée','Parthénon','medium'],['Taj Mahal','Pyramides','medium'],['Grande Muraille','Armée de Terre Cuite','medium'],
    ['Louvre','British Museum','medium'],['MoMA','Tate Modern','medium'],['Notre-Dame','Sacré-Cœur','medium'],['Sagrada Familia','Alhambra','medium'],['Sainte-Sophie','Mosquée Bleue','medium'],
    ['Everest','K2','medium'],['Kilimandjaro','Mont Blanc','medium'],['Sahara','Gobi','medium'],['Amazone','Congo','medium'],['Nil','Mississippi','medium'],
    ['Grand Canyon','Yosemite','medium'],['Chutes du Niagara','Chutes Victoria','medium'],['Grande Barrière','Galapagos','medium'],['Serengeti','Kruger','medium'],['Patagonie','Fjords','medium'],
    ['Venise','Amsterdam','medium'],['Prague','Vienne','medium'],['Stockholm','Helsinki','medium'],['Copenhague','Oslo','medium'],['Budapest','Varsovie','medium'],
    ['Reykjavik','Lofoten','hard'],['Santorin','Mykonos','hard'],['Maldives','Seychelles','hard'],['Zanzibar','Maurice','hard'],['Petra','Palmyre','hard'],
    ['Machu Picchu','Chichen Itza','hard'],['Angkor Vat','Borobudur','hard'],['Île de Pâques','Stonehenge','hard'],['Tombouctou','Samarcande','hard'],['Bhoutan','Népal','hard'],
  ],
  es: [
    ['París','Londres','easy'],['Tokio','Kioto','easy'],['Roma','Atenas','easy'],['Madrid','Barcelona','easy'],['Berlín','Múnich','easy'],
    ['Nueva York','Los Ángeles','easy'],['Chicago','Boston','easy'],['Dubái','Abu Dabi','easy'],['Moscú','San Petersburgo','easy'],['Pekín','Shanghái','easy'],
    ['Egipto','Marruecos','easy'],['Brasil','Argentina','easy'],['Japón','Corea','easy'],['Italia','Grecia','easy'],['España','Portugal','easy'],
    ['Torre Eiffel','Big Ben','medium'],['Estatua de la Libertad','Cristo Redentor','medium'],['Coliseo','Partenón','medium'],['Taj Mahal','Pirámides','medium'],['Gran Muralla','Ejército de Terracota','medium'],
    ['Louvre','Museo Británico','medium'],['MoMA','Tate Modern','medium'],['Notre Dame','Sacré-Cœur','medium'],['Sagrada Familia','Alhambra','medium'],['Santa Sofía','Mezquita Azul','medium'],
    ['Everest','K2','medium'],['Kilimanjaro','Mont Blanc','medium'],['Sahara','Gobi','medium'],['Amazonas','Congo','medium'],['Nilo','Misisipi','medium'],
    ['Gran Cañón','Yosemite','medium'],['Cataratas del Niágara','Cataratas Victoria','medium'],['Gran Barrera','Galápagos','medium'],['Serengeti','Kruger','medium'],['Patagonia','Fiordos','medium'],
    ['Venecia','Ámsterdam','medium'],['Praga','Viena','medium'],['Estocolmo','Helsinki','medium'],['Copenhague','Oslo','medium'],['Budapest','Varsovia','medium'],
    ['Reikiavik','Lofoten','hard'],['Santorini','Míkonos','hard'],['Maldivas','Seychelles','hard'],['Zanzíbar','Mauricio','hard'],['Petra','Palmira','hard'],
    ['Machu Picchu','Chichén Itzá','hard'],['Angkor Wat','Borobudur','hard'],['Isla de Pascua','Stonehenge','hard'],['Tombuctú','Samarcanda','hard'],['Bután','Nepal','hard'],
  ],
  de: [
    ['Paris','London','easy'],['Tokio','Kyoto','easy'],['Rom','Athen','easy'],['Madrid','Barcelona','easy'],['Berlin','München','easy'],
    ['New York','Los Angeles','easy'],['Chicago','Boston','easy'],['Dubai','Abu Dhabi','easy'],['Moskau','Sankt Petersburg','easy'],['Peking','Shanghai','easy'],
    ['Ägypten','Marokko','easy'],['Brasilien','Argentinien','easy'],['Japan','Korea','easy'],['Italien','Griechenland','easy'],['Spanien','Portugal','easy'],
    ['Eiffelturm','Big Ben','medium'],['Freiheitsstatue','Christus-Statue','medium'],['Kolosseum','Parthenon','medium'],['Taj Mahal','Pyramiden','medium'],['Chinesische Mauer','Terrakotta-Armee','medium'],
    ['Louvre','British Museum','medium'],['MoMA','Tate Modern','medium'],['Notre Dame','Sacré-Cœur','medium'],['Sagrada Familia','Alhambra','medium'],['Hagia Sophia','Blaue Moschee','medium'],
    ['Everest','K2','medium'],['Kilimandscharo','Mont Blanc','medium'],['Sahara','Gobi','medium'],['Amazonas','Kongo','medium'],['Nil','Mississippi','medium'],
    ['Grand Canyon','Yosemite','medium'],['Niagarafälle','Viktoriafälle','medium'],['Great Barrier Reef','Galapagos','medium'],['Serengeti','Kruger','medium'],['Patagonien','Fjorde','medium'],
    ['Venedig','Amsterdam','medium'],['Prag','Wien','medium'],['Stockholm','Helsinki','medium'],['Kopenhagen','Oslo','medium'],['Budapest','Warschau','medium'],
    ['Reykjavik','Lofoten','hard'],['Santorin','Mykonos','hard'],['Malediven','Seychellen','hard'],['Sansibar','Mauritius','hard'],['Petra','Palmyra','hard'],
    ['Machu Picchu','Chichén Itzá','hard'],['Angkor Wat','Borobudur','hard'],['Osterinsel','Stonehenge','hard'],['Timbuktu','Samarkand','hard'],['Bhutan','Nepal','hard'],
  ],
  ar: [
    ['باريس','لندن','easy'],['طوكيو','كيوتو','easy'],['روما','أثينا','easy'],['مدريد','برشلونة','easy'],['برلين','ميونخ','easy'],
    ['نيويورك','لوس أنجلوس','easy'],['شيكاغو','بوسطن','easy'],['دبي','أبوظبي','easy'],['موسكو','سانت بطرسبرغ','easy'],['بكين','شنغهاي','easy'],
    ['مصر','المغرب','easy'],['البرازيل','الأرجنتين','easy'],['اليابان','كوريا','easy'],['إيطاليا','اليونان','easy'],['إسبانيا','البرتغال','easy'],
    ['برج إيفل','بيغ بن','medium'],['تمثال الحرية','المسيح الفادي','medium'],['الكولوسيوم','البارثينون','medium'],['تاج محل','الأهرامات','medium'],['سور الصين العظيم','جيش الطين','medium'],
    ['اللوفر','المتحف البريطاني','medium'],['موما','تيت مودرن','medium'],['نوتردام','القلب المقدس','medium'],['ساغرادا فاميليا','قصر الحمراء','medium'],['آيا صوفيا','المسجد الأزرق','medium'],
    ['إيفرست','كي 2','medium'],['كليمنجارو','مون بلان','medium'],['الصحراء الكبرى','جوبي','medium'],['الأمازون','الكونغو','medium'],['النيل','المسيسيبي','medium'],
    ['الجراند كانيون','يوسمايت','medium'],['شلالات نياجرا','شلالات فيكتوريا','medium'],['الحاجز المرجاني العظيم','غالاباغوس','medium'],['سيرينجيتي','كروجر','medium'],['باتاغونيا','المضائق','medium'],
    ['البندقية','أمستردام','medium'],['براغ','فيينا','medium'],['ستوكهولم','هلسنكي','medium'],['كوبنهاغن','أوسلو','medium'],['بودابست','وارسو','medium'],
    ['ريكيافيك','لوفوتن','hard'],['سانتوريني','ميكونوس','hard'],['المالديف','سيشل','hard'],['زنجبار','موريشيوس','hard'],['البتراء','تدمر','hard'],
    ['ماتشو بيتشو','تشيتشن إيتزا','hard'],['أنغكور وات','بوروبودور','hard'],['جزيرة الفصح','ستونهنج','hard'],['تمبكتو','سمرقند','hard'],['بوتان','نيبال','hard'],
  ],
  it: [
    ['Parigi','Londra','easy'],['Tokyo','Kyoto','easy'],['Roma','Atene','easy'],['Madrid','Barcellona','easy'],['Berlino','Monaco','easy'],
    ['New York','Los Angeles','easy'],['Chicago','Boston','easy'],['Dubai','Abu Dhabi','easy'],['Mosca','San Pietroburgo','easy'],['Pechino','Shanghai','easy'],
    ['Egitto','Marocco','easy'],['Brasile','Argentina','easy'],['Giappone','Corea','easy'],['Italia','Grecia','easy'],['Spagna','Portogallo','easy'],
    ['Torre Eiffel','Big Ben','medium'],['Statua della Libertà','Cristo Redentore','medium'],['Colosseo','Partenone','medium'],['Taj Mahal','Piramidi','medium'],['Grande Muraglia','Esercito di Terracotta','medium'],
    ['Louvre','British Museum','medium'],['MoMA','Tate Modern','medium'],['Notre Dame','Sacré-Cœur','medium'],['Sagrada Familia','Alhambra','medium'],['Santa Sofia','Moschea Blu','medium'],
    ['Everest','K2','medium'],['Kilimangiaro','Monte Bianco','medium'],['Sahara','Gobi','medium'],['Rio delle Amazzoni','Congo','medium'],['Nilo','Mississippi','medium'],
    ['Grand Canyon','Yosemite','medium'],['Cascate del Niagara','Cascate Vittoria','medium'],['Grande Barriera','Galapagos','medium'],['Serengeti','Kruger','medium'],['Patagonia','Fiordi','medium'],
    ['Venezia','Amsterdam','medium'],['Praga','Vienna','medium'],['Stoccolma','Helsinki','medium'],['Copenaghen','Oslo','medium'],['Budapest','Varsavia','medium'],
    ['Reykjavik','Lofoten','hard'],['Santorini','Mykonos','hard'],['Maldive','Seychelles','hard'],['Zanzibar','Mauritius','hard'],['Petra','Palmira','hard'],
    ['Machu Picchu','Chichen Itza','hard'],['Angkor Wat','Borobudur','hard'],['Isola di Pasqua','Stonehenge','hard'],['Timbuctu','Samarcanda','hard'],['Bhutan','Nepal','hard'],
  ],
  pt: [
    ['Paris','Londres','easy'],['Tóquio','Quioto','easy'],['Roma','Atenas','easy'],['Madri','Barcelona','easy'],['Berlim','Munique','easy'],
    ['Nova York','Los Angeles','easy'],['Chicago','Boston','easy'],['Dubai','Abu Dhabi','easy'],['Moscou','São Petersburgo','easy'],['Pequim','Xangai','easy'],
    ['Egito','Marrocos','easy'],['Brasil','Argentina','easy'],['Japão','Coreia','easy'],['Itália','Grécia','easy'],['Espanha','Portugal','easy'],
    ['Torre Eiffel','Big Ben','medium'],['Estátua da Liberdade','Cristo Redentor','medium'],['Coliseu','Partenon','medium'],['Taj Mahal','Pirâmides','medium'],['Grande Muralha','Exército de Terracota','medium'],
    ['Louvre','Museu Britânico','medium'],['MoMA','Tate Modern','medium'],['Notre Dame','Sacré-Cœur','medium'],['Sagrada Família','Alhambra','medium'],['Santa Sofia','Mesquita Azul','medium'],
    ['Everest','K2','medium'],['Kilimanjaro','Mont Blanc','medium'],['Saara','Gobi','medium'],['Amazônia','Congo','medium'],['Nilo','Mississippi','medium'],
    ['Grand Canyon','Yosemite','medium'],['Cataratas do Niágara','Cataratas Vitória','medium'],['Grande Barreira de Corais','Galápagos','medium'],['Serengeti','Kruger','medium'],['Patagônia','Fiordes','medium'],
    ['Veneza','Amsterdã','medium'],['Praga','Viena','medium'],['Estocolmo','Helsinque','medium'],['Copenhague','Oslo','medium'],['Budapeste','Varsóvia','medium'],
    ['Reykjavik','Lofoten','hard'],['Santorini','Mykonos','hard'],['Maldivas','Seychelles','hard'],['Zanzibar','Maurício','hard'],['Petra','Palmira','hard'],
    ['Machu Picchu','Chichén Itzá','hard'],['Angkor Wat','Borobudur','hard'],['Ilha de Páscoa','Stonehenge','hard'],['Tombuctu','Samarcanda','hard'],['Butão','Nepal','hard'],
  ],
  zh: [
    ['巴黎','伦敦','easy'],['东京','京都','easy'],['罗马','雅典','easy'],['马德里','巴塞罗那','easy'],['柏林','慕尼黑','easy'],
    ['纽约','洛杉矶','easy'],['芝加哥','波士顿','easy'],['迪拜','阿布扎比','easy'],['莫斯科','圣彼得堡','easy'],['北京','上海','easy'],
    ['埃及','摩洛哥','easy'],['巴西','阿根廷','easy'],['日本','韩国','easy'],['意大利','希腊','easy'],['西班牙','葡萄牙','easy'],
    ['埃菲尔铁塔','大本钟','medium'],['自由女神像','救世基督像','medium'],['斗兽场','帕特农神庙','medium'],['泰姬陵','金字塔','medium'],['长城','兵马俑','medium'],
    ['卢浮宫','大英博物馆','medium'],['现代艺术博物馆','泰特现代美术馆','medium'],['巴黎圣母院','圣心大教堂','medium'],['圣家堂','阿尔罕布拉宫','medium'],['圣索菲亚','蓝色清真寺','medium'],
    ['珠穆朗玛峰','乔戈里峰','medium'],['乞力马扎罗','勃朗峰','medium'],['撒哈拉','戈壁','medium'],['亚马逊','刚果','medium'],['尼罗河','密西西比河','medium'],
    ['大峡谷','约塞米蒂','medium'],['尼亚加拉瀑布','维多利亚瀑布','medium'],['大堡礁','加拉帕戈斯','medium'],['塞伦盖蒂','克鲁格','medium'],['巴塔哥尼亚','峡湾','medium'],
    ['威尼斯','阿姆斯特丹','medium'],['布拉格','维也纳','medium'],['斯德哥尔摩','赫尔辛基','medium'],['哥本哈根','奥斯陆','medium'],['布达佩斯','华沙','medium'],
    ['雷克雅未克','罗弗敦','hard'],['圣托里尼','米科诺斯','hard'],['马尔代夫','塞舌尔','hard'],['桑给巴尔','毛里求斯','hard'],['佩特拉','帕尔米拉','hard'],
    ['马丘比丘','奇琴伊察','hard'],['吴哥窟','婆罗浮屠','hard'],['复活节岛','巨石阵','hard'],['廷巴克图','撒马尔罕','hard'],['不丹','尼泊尔','hard'],
  ],
}
const TR_JOBS: TrPack = {
  en: [
    ['Surgeon','Dentist','easy'],['Pilot','Stewardess','easy'],['Firefighter','Police Officer','easy'],['Judge','Lawyer','easy'],['Chef','Baker','easy'],
    ['Teacher','Professor','easy'],['Nurse','Doctor','easy'],['Carpenter','Mason','easy'],['Plumber','Electrician','easy'],['Driver','Mechanic','easy'],
    ['Farmer','Rancher','easy'],['Fisherman','Sailor','easy'],['Butcher','Grocer','easy'],['Waiter','Bartender','easy'],['Barber','Hairdresser','easy'],
    ['Psychiatrist','Psychologist','medium'],['Pediatrician','Pediatric Nurse','medium'],['Radiologist','Oncologist','medium'],['Paramedic','EMT','medium'],['Veterinarian','Zoologist','medium'],
    ['Civil Engineer','Architect','medium'],['Software Engineer','Data Scientist','medium'],['Frontend Dev','Backend Dev','medium'],['UX Designer','Graphic Designer','medium'],['Product Manager','Project Manager','medium'],
    ['Accountant','Auditor','medium'],['Banker','Broker','medium'],['Trader','Analyst','medium'],['Economist','Statistician','medium'],['Actuary','Risk Manager','medium'],
    ['Reporter','Editor','medium'],['Author','Screenwriter','medium'],['Photographer','Videographer','medium'],['Painter','Sculptor','medium'],['Musician','Composer','medium'],
    ['Actor','Stuntman','medium'],['Comedian','Magician','medium'],['Director','Producer','medium'],['Novelist','Poet','medium'],['Librarian','Archivist','medium'],
    ['Astronaut','Cosmonaut','hard'],['Marine Biologist','Oceanographer','hard'],['Archaeologist','Paleontologist','hard'],['Meteorologist','Climatologist','hard'],['Geologist','Seismologist','hard'],
    ['Diplomat','Ambassador','hard'],['Cartographer','Surveyor','hard'],['Sommelier','Mixologist','hard'],['Luthier','Piano Tuner','hard'],['Falconer','Blacksmith','hard'],
  ],
  fr: [
    ['Chirurgien','Dentiste','easy'],['Pilote','Hôtesse','easy'],['Pompier','Policier','easy'],['Juge','Avocat','easy'],['Chef','Boulanger','easy'],
    ['Professeur','Enseignant','easy'],['Infirmier','Médecin','easy'],['Menuisier','Maçon','easy'],['Plombier','Électricien','easy'],['Chauffeur','Mécanicien','easy'],
    ['Agriculteur','Éleveur','easy'],['Pêcheur','Marin','easy'],['Boucher','Épicier','easy'],['Serveur','Barman','easy'],['Barbier','Coiffeur','easy'],
    ['Psychiatre','Psychologue','medium'],['Pédiatre','Infirmier Pédiatrique','medium'],['Radiologue','Oncologue','medium'],['Ambulancier','Secouriste','medium'],['Vétérinaire','Zoologiste','medium'],
    ['Ingénieur Civil','Architecte','medium'],['Ingénieur Logiciel','Data Scientist','medium'],['Dev Frontend','Dev Backend','medium'],['Designer UX','Graphiste','medium'],['Chef de Produit','Chef de Projet','medium'],
    ['Comptable','Auditeur','medium'],['Banquier','Courtier','medium'],['Trader','Analyste','medium'],['Économiste','Statisticien','medium'],['Actuaire','Gestionnaire de Risque','medium'],
    ['Journaliste','Rédacteur','medium'],['Auteur','Scénariste','medium'],['Photographe','Vidéaste','medium'],['Peintre','Sculpteur','medium'],['Musicien','Compositeur','medium'],
    ['Acteur','Cascadeur','medium'],['Humoriste','Magicien','medium'],['Réalisateur','Producteur','medium'],['Romancier','Poète','medium'],['Bibliothécaire','Archiviste','medium'],
    ['Astronaute','Cosmonaute','hard'],['Biologiste Marin','Océanographe','hard'],['Archéologue','Paléontologue','hard'],['Météorologue','Climatologue','hard'],['Géologue','Sismologue','hard'],
    ['Diplomate','Ambassadeur','hard'],['Cartographe','Géomètre','hard'],['Sommelier','Mixologue','hard'],['Luthier','Accordeur','hard'],['Fauconnier','Forgeron','hard'],
  ],
  es: [
    ['Cirujano','Dentista','easy'],['Piloto','Azafata','easy'],['Bombero','Policía','easy'],['Juez','Abogado','easy'],['Chef','Panadero','easy'],
    ['Maestro','Profesor','easy'],['Enfermero','Médico','easy'],['Carpintero','Albañil','easy'],['Fontanero','Electricista','easy'],['Conductor','Mecánico','easy'],
    ['Agricultor','Ganadero','easy'],['Pescador','Marinero','easy'],['Carnicero','Tendero','easy'],['Camarero','Barman','easy'],['Barbero','Peluquero','easy'],
    ['Psiquiatra','Psicólogo','medium'],['Pediatra','Enfermera Pediátrica','medium'],['Radiólogo','Oncólogo','medium'],['Paramédico','Socorrista','medium'],['Veterinario','Zoólogo','medium'],
    ['Ingeniero Civil','Arquitecto','medium'],['Ingeniero de Software','Científico de Datos','medium'],['Dev Frontend','Dev Backend','medium'],['Diseñador UX','Diseñador Gráfico','medium'],['Gerente de Producto','Gerente de Proyecto','medium'],
    ['Contador','Auditor','medium'],['Banquero','Corredor','medium'],['Trader','Analista','medium'],['Economista','Estadístico','medium'],['Actuario','Gestor de Riesgos','medium'],
    ['Reportero','Editor','medium'],['Autor','Guionista','medium'],['Fotógrafo','Videógrafo','medium'],['Pintor','Escultor','medium'],['Músico','Compositor','medium'],
    ['Actor','Doble','medium'],['Comediante','Mago','medium'],['Director','Productor','medium'],['Novelista','Poeta','medium'],['Bibliotecario','Archivista','medium'],
    ['Astronauta','Cosmonauta','hard'],['Biólogo Marino','Oceanógrafo','hard'],['Arqueólogo','Paleontólogo','hard'],['Meteorólogo','Climatólogo','hard'],['Geólogo','Sismólogo','hard'],
    ['Diplomático','Embajador','hard'],['Cartógrafo','Topógrafo','hard'],['Sumiller','Mixólogo','hard'],['Luthier','Afinador','hard'],['Halconero','Herrero','hard'],
  ],
  de: [
    ['Chirurg','Zahnarzt','easy'],['Pilot','Flugbegleiterin','easy'],['Feuerwehrmann','Polizist','easy'],['Richter','Anwalt','easy'],['Koch','Bäcker','easy'],
    ['Lehrer','Professor','easy'],['Krankenpfleger','Arzt','easy'],['Zimmermann','Maurer','easy'],['Klempner','Elektriker','easy'],['Fahrer','Mechaniker','easy'],
    ['Bauer','Viehzüchter','easy'],['Fischer','Seemann','easy'],['Metzger','Lebensmittelhändler','easy'],['Kellner','Barkeeper','easy'],['Barbier','Friseur','easy'],
    ['Psychiater','Psychologe','medium'],['Kinderarzt','Kinderkrankenschwester','medium'],['Radiologe','Onkologe','medium'],['Rettungssanitäter','Notfallsanitäter','medium'],['Tierarzt','Zoologe','medium'],
    ['Bauingenieur','Architekt','medium'],['Softwareingenieur','Datenwissenschaftler','medium'],['Frontend-Dev','Backend-Dev','medium'],['UX-Designer','Grafikdesigner','medium'],['Produktmanager','Projektmanager','medium'],
    ['Buchhalter','Wirtschaftsprüfer','medium'],['Banker','Makler','medium'],['Händler','Analyst','medium'],['Ökonom','Statistiker','medium'],['Aktuar','Risikomanager','medium'],
    ['Reporter','Redakteur','medium'],['Autor','Drehbuchautor','medium'],['Fotograf','Videograf','medium'],['Maler','Bildhauer','medium'],['Musiker','Komponist','medium'],
    ['Schauspieler','Stuntman','medium'],['Komiker','Zauberer','medium'],['Regisseur','Produzent','medium'],['Romanautor','Dichter','medium'],['Bibliothekar','Archivar','medium'],
    ['Astronaut','Kosmonaut','hard'],['Meeresbiologe','Ozeanograph','hard'],['Archäologe','Paläontologe','hard'],['Meteorologe','Klimatologe','hard'],['Geologe','Seismologe','hard'],
    ['Diplomat','Botschafter','hard'],['Kartograph','Vermesser','hard'],['Sommelier','Mixologe','hard'],['Geigenbauer','Klavierstimmer','hard'],['Falkner','Schmied','hard'],
  ],
  ar: [
    ['جراح','طبيب أسنان','easy'],['طيار','مضيفة طيران','easy'],['إطفائي','شرطي','easy'],['قاضي','محامي','easy'],['طاهي','خباز','easy'],
    ['معلم','أستاذ','easy'],['ممرض','طبيب','easy'],['نجار','بناء','easy'],['سباك','كهربائي','easy'],['سائق','ميكانيكي','easy'],
    ['مزارع','مربي ماشية','easy'],['صياد','بحار','easy'],['جزار','بقال','easy'],['نادل','نادل بار','easy'],['حلاق','مصفف شعر','easy'],
    ['طبيب نفسي','عالم نفس','medium'],['طبيب أطفال','ممرضة أطفال','medium'],['أخصائي أشعة','أخصائي أورام','medium'],['مسعف','فني طوارئ','medium'],['طبيب بيطري','عالم حيوان','medium'],
    ['مهندس مدني','معماري','medium'],['مهندس برمجيات','عالم بيانات','medium'],['مطور واجهة أمامية','مطور خلفية','medium'],['مصمم تجربة المستخدم','مصمم جرافيك','medium'],['مدير منتج','مدير مشروع','medium'],
    ['محاسب','مدقق حسابات','medium'],['مصرفي','وسيط','medium'],['متداول','محلل','medium'],['اقتصادي','إحصائي','medium'],['خبير اكتواري','مدير مخاطر','medium'],
    ['صحفي','محرر','medium'],['مؤلف','كاتب سيناريو','medium'],['مصور','مصور فيديو','medium'],['رسام','نحات','medium'],['موسيقي','ملحن','medium'],
    ['ممثل','بديل مشاهد خطرة','medium'],['كوميدي','ساحر','medium'],['مخرج','منتج','medium'],['روائي','شاعر','medium'],['أمين مكتبة','أمين محفوظات','medium'],
    ['رائد فضاء','كوزمونوت','hard'],['عالم أحياء بحرية','عالم محيطات','hard'],['عالم آثار','عالم حفريات','hard'],['أخصائي أرصاد','أخصائي مناخ','hard'],['جيولوجي','عالم زلازل','hard'],
    ['دبلوماسي','سفير','hard'],['رسام خرائط','مساح','hard'],['خبير نبيذ','خبير كوكتيلات','hard'],['صانع كمان','مضبط بيانو','hard'],['مروض صقور','حداد','hard'],
  ],
  it: [
    ['Chirurgo','Dentista','easy'],['Pilota','Assistente di Volo','easy'],['Pompiere','Poliziotto','easy'],['Giudice','Avvocato','easy'],['Chef','Fornaio','easy'],
    ['Insegnante','Professore','easy'],['Infermiere','Medico','easy'],['Falegname','Muratore','easy'],['Idraulico','Elettricista','easy'],['Autista','Meccanico','easy'],
    ['Agricoltore','Allevatore','easy'],['Pescatore','Marinaio','easy'],['Macellaio','Droghiere','easy'],['Cameriere','Barista','easy'],['Barbiere','Parrucchiere','easy'],
    ['Psichiatra','Psicologo','medium'],['Pediatra','Infermiere Pediatrico','medium'],['Radiologo','Oncologo','medium'],['Paramedico','Soccorritore','medium'],['Veterinario','Zoologo','medium'],
    ['Ingegnere Civile','Architetto','medium'],['Ingegnere del Software','Data Scientist','medium'],['Dev Frontend','Dev Backend','medium'],['Designer UX','Grafico','medium'],['Product Manager','Project Manager','medium'],
    ['Contabile','Revisore','medium'],['Banchiere','Intermediario','medium'],['Trader','Analista','medium'],['Economista','Statistico','medium'],['Attuario','Risk Manager','medium'],
    ['Reporter','Redattore','medium'],['Autore','Sceneggiatore','medium'],['Fotografo','Videografo','medium'],['Pittore','Scultore','medium'],['Musicista','Compositore','medium'],
    ['Attore','Stuntman','medium'],['Comico','Mago','medium'],['Regista','Produttore','medium'],['Romanziere','Poeta','medium'],['Bibliotecario','Archivista','medium'],
    ['Astronauta','Cosmonauta','hard'],['Biologo Marino','Oceanografo','hard'],['Archeologo','Paleontologo','hard'],['Meteorologo','Climatologo','hard'],['Geologo','Sismologo','hard'],
    ['Diplomatico','Ambasciatore','hard'],['Cartografo','Topografo','hard'],['Sommelier','Mixologo','hard'],['Liutaio','Accordatore','hard'],['Falconiere','Fabbro','hard'],
  ],
  pt: [
    ['Cirurgião','Dentista','easy'],['Piloto','Comissária','easy'],['Bombeiro','Policial','easy'],['Juiz','Advogado','easy'],['Chef','Padeiro','easy'],
    ['Professor','Catedrático','easy'],['Enfermeiro','Médico','easy'],['Carpinteiro','Pedreiro','easy'],['Encanador','Eletricista','easy'],['Motorista','Mecânico','easy'],
    ['Agricultor','Fazendeiro','easy'],['Pescador','Marinheiro','easy'],['Açougueiro','Quitandeiro','easy'],['Garçom','Barman','easy'],['Barbeiro','Cabeleireiro','easy'],
    ['Psiquiatra','Psicólogo','medium'],['Pediatra','Enfermeira Pediátrica','medium'],['Radiologista','Oncologista','medium'],['Paramédico','Socorrista','medium'],['Veterinário','Zoólogo','medium'],
    ['Engenheiro Civil','Arquiteto','medium'],['Engenheiro de Software','Cientista de Dados','medium'],['Dev Frontend','Dev Backend','medium'],['Designer UX','Designer Gráfico','medium'],['Product Manager','Project Manager','medium'],
    ['Contador','Auditor','medium'],['Banqueiro','Corretor','medium'],['Trader','Analista','medium'],['Economista','Estatístico','medium'],['Atuário','Gestor de Risco','medium'],
    ['Repórter','Editor','medium'],['Autor','Roteirista','medium'],['Fotógrafo','Videógrafo','medium'],['Pintor','Escultor','medium'],['Músico','Compositor','medium'],
    ['Ator','Dublê','medium'],['Comediante','Mágico','medium'],['Diretor','Produtor','medium'],['Romancista','Poeta','medium'],['Bibliotecário','Arquivista','medium'],
    ['Astronauta','Cosmonauta','hard'],['Biólogo Marinho','Oceanógrafo','hard'],['Arqueólogo','Paleontólogo','hard'],['Meteorologista','Climatologista','hard'],['Geólogo','Sismólogo','hard'],
    ['Diplomata','Embaixador','hard'],['Cartógrafo','Agrimensor','hard'],['Sommelier','Mixologista','hard'],['Luthier','Afinador','hard'],['Falcoeiro','Ferreiro','hard'],
  ],
  zh: [
    ['外科医生','牙医','easy'],['飞行员','空乘','easy'],['消防员','警察','easy'],['法官','律师','easy'],['厨师','面包师','easy'],
    ['教师','教授','easy'],['护士','医生','easy'],['木匠','泥瓦匠','easy'],['水管工','电工','easy'],['司机','机械师','easy'],
    ['农民','牧场主','easy'],['渔民','水手','easy'],['屠夫','杂货商','easy'],['服务员','调酒师','easy'],['理发师','美发师','easy'],
    ['精神科医生','心理学家','medium'],['儿科医生','儿科护士','medium'],['放射科医生','肿瘤学家','medium'],['急救员','医疗技术员','medium'],['兽医','动物学家','medium'],
    ['土木工程师','建筑师','medium'],['软件工程师','数据科学家','medium'],['前端开发','后端开发','medium'],['UX设计师','平面设计师','medium'],['产品经理','项目经理','medium'],
    ['会计','审计员','medium'],['银行家','经纪人','medium'],['交易员','分析师','medium'],['经济学家','统计学家','medium'],['精算师','风险经理','medium'],
    ['记者','编辑','medium'],['作家','编剧','medium'],['摄影师','摄像师','medium'],['画家','雕塑家','medium'],['音乐家','作曲家','medium'],
    ['演员','特技演员','medium'],['喜剧演员','魔术师','medium'],['导演','制片人','medium'],['小说家','诗人','medium'],['图书馆员','档案管理员','medium'],
    ['宇航员','航天员','hard'],['海洋生物学家','海洋学家','hard'],['考古学家','古生物学家','hard'],['气象学家','气候学家','hard'],['地质学家','地震学家','hard'],
    ['外交官','大使','hard'],['制图师','测量员','hard'],['侍酒师','调酒大师','hard'],['制琴师','调音师','hard'],['驯鹰人','铁匠','hard'],
  ],
}
const TR_SPORTS: TrPack = {
  en: [
    ['Soccer','Futsal','easy'],['Basketball','Netball','easy'],['Tennis','Badminton','easy'],['Baseball','Softball','easy'],['Volleyball','Beach Volleyball','easy'],
    ['Swimming','Diving','easy'],['Running','Jogging','easy'],['Cycling','Mountain Biking','easy'],['Skiing','Snowboarding','easy'],['Surfing','Kitesurfing','easy'],
    ['Golf','Mini Golf','easy'],['Bowling','Curling','easy'],['Boxing','Kickboxing','easy'],['Karate','Taekwondo','easy'],['Judo','Jiu Jitsu','easy'],
    ['Marathon','Triathlon','medium'],['Sprint','Hurdles','medium'],['Long Jump','High Jump','medium'],['Shot Put','Discus','medium'],['Javelin','Hammer Throw','medium'],
    ['Pole Vault','Trampoline','medium'],['Gymnastics','Acrobatics','medium'],['Figure Skating','Ice Dancing','medium'],['Speed Skating','Short Track','medium'],['Bobsled','Luge','medium'],
    ['Skateboarding','BMX','medium'],['Parkour','Free Running','medium'],['Rock Climbing','Bouldering','medium'],['Kayaking','Canoeing','medium'],['Rowing','Sculling','medium'],
    ['Sailing','Windsurfing','medium'],['Scuba Diving','Snorkeling','medium'],['Water Polo','Synchronized Swimming','medium'],['Rugby','American Football','medium'],['Cricket','Baseball','medium'],
    ['Hockey','Field Hockey','medium'],['Lacrosse','Polo','medium'],['Archery','Darts','medium'],['Shooting','Fencing','medium'],['Equestrian','Show Jumping','medium'],
    ['Pentathlon','Decathlon','hard'],['Biathlon','Nordic Combined','hard'],['Dressage','Eventing','hard'],['Paragliding','Hang Gliding','hard'],['Kendo','Aikido','hard'],
    ['Sumo','Muay Thai','hard'],['Wushu','Capoeira','hard'],['Pelota','Squash','hard'],['Pickleball','Padel','hard'],['Hurling','Shinty','hard'],
  ],
  fr: [
    ['Football','Futsal','easy'],['Basket','Netball','easy'],['Tennis','Badminton','easy'],['Baseball','Softball','easy'],['Volley','Beach Volley','easy'],
    ['Natation','Plongeon','easy'],['Course','Jogging','easy'],['Cyclisme','VTT','easy'],['Ski','Snowboard','easy'],['Surf','Kitesurf','easy'],
    ['Golf','Mini Golf','easy'],['Bowling','Curling','easy'],['Boxe','Kickboxing','easy'],['Karaté','Taekwondo','easy'],['Judo','Jiu Jitsu','easy'],
    ['Marathon','Triathlon','medium'],['Sprint','Haies','medium'],['Saut en Longueur','Saut en Hauteur','medium'],['Lancer du Poids','Disque','medium'],['Javelot','Lancer du Marteau','medium'],
    ['Saut à la Perche','Trampoline','medium'],['Gymnastique','Acrobatie','medium'],['Patinage Artistique','Danse sur Glace','medium'],['Patinage de Vitesse','Short Track','medium'],['Bobsleigh','Luge','medium'],
    ['Skateboard','BMX','medium'],['Parkour','Free Running','medium'],['Escalade','Bloc','medium'],['Kayak','Canoë','medium'],['Aviron','Godille','medium'],
    ['Voile','Planche à Voile','medium'],['Plongée','Snorkeling','medium'],['Water-Polo','Natation Synchronisée','medium'],['Rugby','Football Américain','medium'],['Cricket','Baseball','medium'],
    ['Hockey sur Glace','Hockey sur Gazon','medium'],['Crosse','Polo','medium'],['Tir à l\'Arc','Fléchettes','medium'],['Tir','Escrime','medium'],['Équitation','Saut d\'Obstacles','medium'],
    ['Pentathlon','Décathlon','hard'],['Biathlon','Combiné Nordique','hard'],['Dressage','Concours Complet','hard'],['Parapente','Deltaplane','hard'],['Kendo','Aïkido','hard'],
    ['Sumo','Muay Thai','hard'],['Wushu','Capoeira','hard'],['Pelote','Squash','hard'],['Pickleball','Padel','hard'],['Hurling','Shinty','hard'],
  ],
  es: [
    ['Fútbol','Futsal','easy'],['Baloncesto','Netball','easy'],['Tenis','Bádminton','easy'],['Béisbol','Softbol','easy'],['Voleibol','Voley Playa','easy'],
    ['Natación','Clavados','easy'],['Correr','Trotar','easy'],['Ciclismo','Ciclismo de Montaña','easy'],['Esquí','Snowboard','easy'],['Surf','Kitesurf','easy'],
    ['Golf','Minigolf','easy'],['Bolos','Curling','easy'],['Boxeo','Kickboxing','easy'],['Karate','Taekwondo','easy'],['Judo','Jiu-jitsu','easy'],
    ['Maratón','Triatlón','medium'],['Sprint','Vallas','medium'],['Salto de Longitud','Salto de Altura','medium'],['Lanzamiento de Peso','Disco','medium'],['Jabalina','Martillo','medium'],
    ['Salto con Pértiga','Trampolín','medium'],['Gimnasia','Acrobacia','medium'],['Patinaje Artístico','Danza sobre Hielo','medium'],['Patinaje de Velocidad','Pista Corta','medium'],['Bobsleigh','Luge','medium'],
    ['Skate','BMX','medium'],['Parkour','Free Running','medium'],['Escalada','Boulder','medium'],['Kayak','Canoa','medium'],['Remo','Remo de Puntos','medium'],
    ['Vela','Windsurf','medium'],['Buceo','Snorkel','medium'],['Waterpolo','Natación Sincronizada','medium'],['Rugby','Fútbol Americano','medium'],['Críquet','Béisbol','medium'],
    ['Hockey Hielo','Hockey Hierba','medium'],['Lacrosse','Polo','medium'],['Tiro con Arco','Dardos','medium'],['Tiro','Esgrima','medium'],['Equitación','Salto Ecuestre','medium'],
    ['Pentatlón','Decatlón','hard'],['Biatlón','Combinado Nórdico','hard'],['Doma Clásica','Concurso Completo','hard'],['Parapente','Ala Delta','hard'],['Kendo','Aikido','hard'],
    ['Sumo','Muay Thai','hard'],['Wushu','Capoeira','hard'],['Pelota Vasca','Squash','hard'],['Pickleball','Pádel','hard'],['Hurling','Shinty','hard'],
  ],
  de: [
    ['Fußball','Futsal','easy'],['Basketball','Netball','easy'],['Tennis','Badminton','easy'],['Baseball','Softball','easy'],['Volleyball','Beachvolleyball','easy'],
    ['Schwimmen','Wasserspringen','easy'],['Laufen','Joggen','easy'],['Radfahren','Mountainbike','easy'],['Skifahren','Snowboard','easy'],['Surfen','Kitesurfen','easy'],
    ['Golf','Minigolf','easy'],['Bowling','Curling','easy'],['Boxen','Kickboxen','easy'],['Karate','Taekwondo','easy'],['Judo','Jiu-Jitsu','easy'],
    ['Marathon','Triathlon','medium'],['Sprint','Hürdenlauf','medium'],['Weitsprung','Hochsprung','medium'],['Kugelstoßen','Diskus','medium'],['Speer','Hammerwurf','medium'],
    ['Stabhochsprung','Trampolin','medium'],['Turnen','Akrobatik','medium'],['Eiskunstlauf','Eistanzen','medium'],['Eisschnelllauf','Shorttrack','medium'],['Bob','Rodeln','medium'],
    ['Skateboarden','BMX','medium'],['Parkour','Free Running','medium'],['Klettern','Bouldern','medium'],['Kajak','Kanu','medium'],['Rudern','Skullen','medium'],
    ['Segeln','Windsurfen','medium'],['Tauchen','Schnorcheln','medium'],['Wasserball','Synchronschwimmen','medium'],['Rugby','American Football','medium'],['Cricket','Baseball','medium'],
    ['Eishockey','Hockey','medium'],['Lacrosse','Polo','medium'],['Bogenschießen','Darts','medium'],['Schießen','Fechten','medium'],['Reiten','Springreiten','medium'],
    ['Pentathlon','Dekathlon','hard'],['Biathlon','Nordische Kombination','hard'],['Dressur','Vielseitigkeit','hard'],['Paragliding','Drachenfliegen','hard'],['Kendo','Aikido','hard'],
    ['Sumo','Muay Thai','hard'],['Wushu','Capoeira','hard'],['Pelota','Squash','hard'],['Pickleball','Padel','hard'],['Hurling','Shinty','hard'],
  ],
  ar: [
    ['كرة القدم','فوتسال','easy'],['كرة السلة','نتبول','easy'],['تنس','ريشة طائرة','easy'],['بيسبول','سوفتبول','easy'],['كرة الطائرة','طائرة شاطئية','easy'],
    ['سباحة','غطس','easy'],['جري','هرولة','easy'],['دراجات','دراجات جبلية','easy'],['تزلج','سنوبورد','easy'],['ركوب الأمواج','كايت سيرف','easy'],
    ['غولف','ميني غولف','easy'],['بولينغ','كيرلينغ','easy'],['ملاكمة','كيك بوكسينغ','easy'],['كاراتيه','تايكوندو','easy'],['جودو','جوجيتسو','easy'],
    ['ماراثون','ترياثلون','medium'],['عدو','حواجز','medium'],['وثب طويل','وثب عالي','medium'],['دفع الجلة','رمي القرص','medium'],['رمح','مطرقة','medium'],
    ['قفز بالزانة','ترامبولين','medium'],['جمباز','أكروبات','medium'],['تزلج فني','رقص على الجليد','medium'],['تزلج سرعة','مسار قصير','medium'],['بوبسليد','لوج','medium'],
    ['تزلج لوح','بي إم إكس','medium'],['باركور','فري رانينغ','medium'],['تسلق صخور','بولدرينغ','medium'],['كاياك','كانوي','medium'],['تجديف','سكلينغ','medium'],
    ['إبحار','ويندسيرف','medium'],['غوص','سنوركلينغ','medium'],['كرة الماء','سباحة إيقاعية','medium'],['رغبي','كرة قدم أمريكية','medium'],['كريكيت','بيسبول','medium'],
    ['هوكي الجليد','هوكي الميدان','medium'],['لاكروس','بولو','medium'],['رماية','سهام','medium'],['رماية','مبارزة','medium'],['فروسية','قفز الحواجز','medium'],
    ['خماسي','عشاري','hard'],['ثنائي','مزج شمالي','hard'],['ترويض','حدث ثلاثي','hard'],['طيران شراعي','دلتا','hard'],['كندو','أيكيدو','hard'],
    ['سومو','مواي تاي','hard'],['ووشو','كابويرا','hard'],['بيلوتا','إسكواش','hard'],['بيكل بول','بادل','hard'],['هورلينغ','شينتي','hard'],
  ],
  it: [
    ['Calcio','Futsal','easy'],['Pallacanestro','Netball','easy'],['Tennis','Badminton','easy'],['Baseball','Softball','easy'],['Pallavolo','Beach Volley','easy'],
    ['Nuoto','Tuffi','easy'],['Corsa','Jogging','easy'],['Ciclismo','Mountain Bike','easy'],['Sci','Snowboard','easy'],['Surf','Kitesurf','easy'],
    ['Golf','Minigolf','easy'],['Bowling','Curling','easy'],['Pugilato','Kickboxing','easy'],['Karate','Taekwondo','easy'],['Judo','Jiu Jitsu','easy'],
    ['Maratona','Triathlon','medium'],['Sprint','Ostacoli','medium'],['Salto in Lungo','Salto in Alto','medium'],['Getto del Peso','Disco','medium'],['Giavellotto','Martello','medium'],
    ['Salto con l\'Asta','Trampolino','medium'],['Ginnastica','Acrobatica','medium'],['Pattinaggio Artistico','Danza sul Ghiaccio','medium'],['Pattinaggio di Velocità','Short Track','medium'],['Bob','Slittino','medium'],
    ['Skateboard','BMX','medium'],['Parkour','Free Running','medium'],['Arrampicata','Boulder','medium'],['Kayak','Canoa','medium'],['Canottaggio','Voga','medium'],
    ['Vela','Windsurf','medium'],['Immersioni','Snorkeling','medium'],['Pallanuoto','Nuoto Sincronizzato','medium'],['Rugby','Football Americano','medium'],['Cricket','Baseball','medium'],
    ['Hockey Ghiaccio','Hockey Prato','medium'],['Lacrosse','Polo','medium'],['Tiro con l\'Arco','Freccette','medium'],['Tiro','Scherma','medium'],['Equitazione','Salto Ostacoli','medium'],
    ['Pentathlon','Decathlon','hard'],['Biathlon','Combinata Nordica','hard'],['Dressage','Completo','hard'],['Parapendio','Deltaplano','hard'],['Kendo','Aikido','hard'],
    ['Sumo','Muay Thai','hard'],['Wushu','Capoeira','hard'],['Pelota','Squash','hard'],['Pickleball','Padel','hard'],['Hurling','Shinty','hard'],
  ],
  pt: [
    ['Futebol','Futsal','easy'],['Basquete','Netball','easy'],['Tênis','Badminton','easy'],['Beisebol','Softbol','easy'],['Vôlei','Vôlei de Praia','easy'],
    ['Natação','Saltos Ornamentais','easy'],['Corrida','Jogging','easy'],['Ciclismo','Mountain Bike','easy'],['Esqui','Snowboard','easy'],['Surfe','Kitesurfe','easy'],
    ['Golfe','Minigolfe','easy'],['Boliche','Curling','easy'],['Boxe','Kickboxing','easy'],['Caratê','Taekwondo','easy'],['Judô','Jiu-jitsu','easy'],
    ['Maratona','Triatlo','medium'],['Sprint','Barreiras','medium'],['Salto em Distância','Salto em Altura','medium'],['Arremesso de Peso','Disco','medium'],['Dardo','Martelo','medium'],
    ['Salto com Vara','Trampolim','medium'],['Ginástica','Acrobacia','medium'],['Patinação Artística','Dança no Gelo','medium'],['Patinação de Velocidade','Short Track','medium'],['Bobsled','Luge','medium'],
    ['Skate','BMX','medium'],['Parkour','Free Running','medium'],['Escalada','Boulder','medium'],['Caiaque','Canoa','medium'],['Remo','Skiff','medium'],
    ['Vela','Windsurfe','medium'],['Mergulho','Snorkeling','medium'],['Polo Aquático','Nado Sincronizado','medium'],['Rúgbi','Futebol Americano','medium'],['Críquete','Beisebol','medium'],
    ['Hóquei no Gelo','Hóquei na Grama','medium'],['Lacrosse','Polo','medium'],['Tiro com Arco','Dardos','medium'],['Tiro','Esgrima','medium'],['Hipismo','Salto Hípico','medium'],
    ['Pentatlo','Decatlo','hard'],['Biatlo','Combinado Nórdico','hard'],['Adestramento','CCE','hard'],['Parapente','Asa Delta','hard'],['Kendo','Aikido','hard'],
    ['Sumô','Muay Thai','hard'],['Wushu','Capoeira','hard'],['Pelota','Squash','hard'],['Pickleball','Padel','hard'],['Hurling','Shinty','hard'],
  ],
  zh: [
    ['足球','五人制足球','easy'],['篮球','无篮板篮球','easy'],['网球','羽毛球','easy'],['棒球','垒球','easy'],['排球','沙滩排球','easy'],
    ['游泳','跳水','easy'],['跑步','慢跑','easy'],['自行车','山地车','easy'],['滑雪','单板滑雪','easy'],['冲浪','风筝冲浪','easy'],
    ['高尔夫','迷你高尔夫','easy'],['保龄球','冰壶','easy'],['拳击','踢拳','easy'],['空手道','跆拳道','easy'],['柔道','柔术','easy'],
    ['马拉松','铁人三项','medium'],['短跑','跨栏','medium'],['跳远','跳高','medium'],['铅球','铁饼','medium'],['标枪','链球','medium'],
    ['撑杆跳','蹦床','medium'],['体操','杂技','medium'],['花样滑冰','冰舞','medium'],['速度滑冰','短道速滑','medium'],['雪橇','无舵雪橇','medium'],
    ['滑板','小轮车','medium'],['跑酷','自由奔跑','medium'],['攀岩','抱石','medium'],['皮划艇','独木舟','medium'],['赛艇','双桨','medium'],
    ['帆船','帆板','medium'],['潜水','浮潜','medium'],['水球','花样游泳','medium'],['橄榄球','美式足球','medium'],['板球','棒球','medium'],
    ['冰球','曲棍球','medium'],['长曲棍球','马球','medium'],['射箭','飞镖','medium'],['射击','击剑','medium'],['马术','障碍赛','medium'],
    ['五项全能','十项全能','hard'],['冬季两项','北欧两项','hard'],['盛装舞步','三项赛','hard'],['滑翔伞','悬挂滑翔','hard'],['剑道','合气道','hard'],
    ['相扑','泰拳','hard'],['武术','卡波耶拉','hard'],['回力球','壁球','hard'],['匹克球','桨板球','hard'],['掷球','板曲棍球','hard'],
  ],
}
const TR_VARIETY: TrPack = {
  en: [
    ['SSD','HDD','easy'],['RAM','ROM','easy'],['CPU','GPU','easy'],['Router','Modem','easy'],['Bluetooth','Wi-Fi','easy'],
    ['Laptop','Tablet','easy'],['Smartphone','Smartwatch','easy'],['Printer','Scanner','easy'],['Keyboard','Mouse','easy'],['Monitor','Projector','easy'],
    ['USB','HDMI','easy'],['Ethernet','Fiber','easy'],['Hard Drive','Flash Drive','easy'],['Headphones','Earbuds','easy'],['Microphone','Speaker','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','Proxy','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['Quantum Computer','Supercomputer','hard'],['Neural Network','Decision Tree','hard'],['Blockchain','Distributed Ledger','hard'],['NFT','Cryptocurrency','hard'],['VR','AR','hard'],
    ['Drone','Satellite','hard'],['3D Printer','Laser Cutter','hard'],['Raspberry Pi','Arduino','hard'],['Telescope','Microscope','hard'],['Oscilloscope','Multimeter','hard'],
  ],
  fr: [
    ['SSD','HDD','easy'],['RAM','ROM','easy'],['CPU','GPU','easy'],['Routeur','Modem','easy'],['Bluetooth','Wi-Fi','easy'],
    ['Ordinateur Portable','Tablette','easy'],['Smartphone','Montre Connectée','easy'],['Imprimante','Scanner','easy'],['Clavier','Souris','easy'],['Écran','Projecteur','easy'],
    ['USB','HDMI','easy'],['Ethernet','Fibre','easy'],['Disque Dur','Clé USB','easy'],['Casque','Écouteurs','easy'],['Micro','Haut-parleur','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','Proxy','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['Ordinateur Quantique','Supercalculateur','hard'],['Réseau de Neurones','Arbre de Décision','hard'],['Blockchain','Registre Distribué','hard'],['NFT','Cryptomonnaie','hard'],['VR','AR','hard'],
    ['Drone','Satellite','hard'],['Imprimante 3D','Découpe Laser','hard'],['Raspberry Pi','Arduino','hard'],['Télescope','Microscope','hard'],['Oscilloscope','Multimètre','hard'],
  ],
  es: [
    ['SSD','HDD','easy'],['RAM','ROM','easy'],['CPU','GPU','easy'],['Router','Módem','easy'],['Bluetooth','Wi-Fi','easy'],
    ['Portátil','Tableta','easy'],['Smartphone','Reloj Inteligente','easy'],['Impresora','Escáner','easy'],['Teclado','Ratón','easy'],['Monitor','Proyector','easy'],
    ['USB','HDMI','easy'],['Ethernet','Fibra','easy'],['Disco Duro','Memoria USB','easy'],['Auriculares','Audífonos','easy'],['Micrófono','Altavoz','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','Proxy','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['Ordenador Cuántico','Supercomputadora','hard'],['Red Neuronal','Árbol de Decisión','hard'],['Blockchain','Registro Distribuido','hard'],['NFT','Criptomoneda','hard'],['VR','AR','hard'],
    ['Dron','Satélite','hard'],['Impresora 3D','Cortadora Láser','hard'],['Raspberry Pi','Arduino','hard'],['Telescopio','Microscopio','hard'],['Osciloscopio','Multímetro','hard'],
  ],
  de: [
    ['SSD','HDD','easy'],['RAM','ROM','easy'],['CPU','GPU','easy'],['Router','Modem','easy'],['Bluetooth','WLAN','easy'],
    ['Laptop','Tablet','easy'],['Smartphone','Smartwatch','easy'],['Drucker','Scanner','easy'],['Tastatur','Maus','easy'],['Monitor','Beamer','easy'],
    ['USB','HDMI','easy'],['Ethernet','Glasfaser','easy'],['Festplatte','USB-Stick','easy'],['Kopfhörer','Ohrhörer','easy'],['Mikrofon','Lautsprecher','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','Proxy','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['Quantencomputer','Supercomputer','hard'],['Neuronales Netz','Entscheidungsbaum','hard'],['Blockchain','Verteiltes Hauptbuch','hard'],['NFT','Kryptowährung','hard'],['VR','AR','hard'],
    ['Drohne','Satellit','hard'],['3D-Drucker','Laserschneider','hard'],['Raspberry Pi','Arduino','hard'],['Teleskop','Mikroskop','hard'],['Oszilloskop','Multimeter','hard'],
  ],
  ar: [
    ['قرص SSD','قرص HDD','easy'],['ذاكرة عشوائية','ذاكرة قراءة فقط','easy'],['معالج CPU','معالج GPU','easy'],['راوتر','مودم','easy'],['بلوتوث','واي فاي','easy'],
    ['حاسوب محمول','جهاز لوحي','easy'],['هاتف ذكي','ساعة ذكية','easy'],['طابعة','ماسح ضوئي','easy'],['لوحة مفاتيح','فأرة','easy'],['شاشة','بروجكتر','easy'],
    ['USB','HDMI','easy'],['إيثرنت','ألياف بصرية','easy'],['قرص صلب','فلاش USB','easy'],['سماعات رأس','سماعات أذن','easy'],['ميكروفون','مكبر صوت','easy'],
    ['بايثون','جافا سكريبت','medium'],['جافا','سي++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['لينكس','ويندوز','medium'],['ماك أو إس','آي أو إس','medium'],['أندرويد','كروم أو إس','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','بروكسي','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['حاسوب كمي','حاسوب عملاق','hard'],['شبكة عصبية','شجرة قرار','hard'],['بلوك تشين','دفتر موزع','hard'],['NFT','عملة مشفرة','hard'],['الواقع الافتراضي','الواقع المعزز','hard'],
    ['درون','قمر صناعي','hard'],['طابعة ثلاثية الأبعاد','قاطعة ليزر','hard'],['راسبيري باي','أردوينو','hard'],['تلسكوب','ميكروسكوب','hard'],['راسمة الذبذبات','متعدد القياسات','hard'],
  ],
  it: [
    ['SSD','HDD','easy'],['RAM','ROM','easy'],['CPU','GPU','easy'],['Router','Modem','easy'],['Bluetooth','Wi-Fi','easy'],
    ['Laptop','Tablet','easy'],['Smartphone','Smartwatch','easy'],['Stampante','Scanner','easy'],['Tastiera','Mouse','easy'],['Monitor','Proiettore','easy'],
    ['USB','HDMI','easy'],['Ethernet','Fibra','easy'],['Disco Rigido','Chiavetta USB','easy'],['Cuffie','Auricolari','easy'],['Microfono','Altoparlante','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','Proxy','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['Computer Quantistico','Supercomputer','hard'],['Rete Neurale','Albero Decisionale','hard'],['Blockchain','Registro Distribuito','hard'],['NFT','Criptovaluta','hard'],['VR','AR','hard'],
    ['Drone','Satellite','hard'],['Stampante 3D','Taglio Laser','hard'],['Raspberry Pi','Arduino','hard'],['Telescopio','Microscopio','hard'],['Oscilloscopio','Multimetro','hard'],
  ],
  pt: [
    ['SSD','HDD','easy'],['RAM','ROM','easy'],['CPU','GPU','easy'],['Roteador','Modem','easy'],['Bluetooth','Wi-Fi','easy'],
    ['Notebook','Tablet','easy'],['Smartphone','Smartwatch','easy'],['Impressora','Scanner','easy'],['Teclado','Mouse','easy'],['Monitor','Projetor','easy'],
    ['USB','HDMI','easy'],['Ethernet','Fibra','easy'],['Disco Rígido','Pen Drive','easy'],['Fones de Ouvido','Earbuds','easy'],['Microfone','Alto-falante','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','Proxy','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['Computador Quântico','Supercomputador','hard'],['Rede Neural','Árvore de Decisão','hard'],['Blockchain','Livro-Razão Distribuído','hard'],['NFT','Criptomoeda','hard'],['VR','AR','hard'],
    ['Drone','Satélite','hard'],['Impressora 3D','Cortadora a Laser','hard'],['Raspberry Pi','Arduino','hard'],['Telescópio','Microscópio','hard'],['Osciloscópio','Multímetro','hard'],
  ],
  zh: [
    ['固态硬盘','机械硬盘','easy'],['内存','只读存储器','easy'],['中央处理器','显卡','easy'],['路由器','调制解调器','easy'],['蓝牙','无线网络','easy'],
    ['笔记本电脑','平板电脑','easy'],['智能手机','智能手表','easy'],['打印机','扫描仪','easy'],['键盘','鼠标','easy'],['显示器','投影仪','easy'],
    ['USB','HDMI','easy'],['以太网','光纤','easy'],['硬盘','U盘','easy'],['头戴耳机','入耳式耳机','easy'],['麦克风','扬声器','easy'],
    ['Python','JavaScript','medium'],['Java','C++','medium'],['React','Vue','medium'],['Angular','Svelte','medium'],['Node','Deno','medium'],
    ['Docker','Kubernetes','medium'],['AWS','Azure','medium'],['Linux','Windows','medium'],['MacOS','iOS','medium'],['Android','Chrome OS','medium'],
    ['SQL','NoSQL','medium'],['MongoDB','PostgreSQL','medium'],['Redis','Memcached','medium'],['GraphQL','REST','medium'],['TCP','UDP','medium'],
    ['HTTPS','SSH','medium'],['VPN','代理','medium'],['Git','SVN','medium'],['GitHub','GitLab','medium'],['Slack','Discord','medium'],
    ['Zoom','Teams','medium'],['Figma','Sketch','medium'],['Notion','Obsidian','medium'],['VS Code','IntelliJ','medium'],['ChatGPT','Claude','medium'],
    ['量子计算机','超级计算机','hard'],['神经网络','决策树','hard'],['区块链','分布式账本','hard'],['NFT','加密货币','hard'],['虚拟现实','增强现实','hard'],
    ['无人机','卫星','hard'],['3D打印机','激光切割机','hard'],['树莓派','Arduino','hard'],['望远镜','显微镜','hard'],['示波器','万用表','hard'],
  ],
}

// ═════════════════════════════════════════════════════════════════════════
// EXPORT — flat array of all extended pairs for all locales
// ═════════════════════════════════════════════════════════════════════════

export const EXTENDED_PAIRS: PairData[] = [
  ...expandProper('mangas', PROPER_MANGAS),
  ...expandProper('celebrities', PROPER_CELEBRITIES),
  ...expandProper('movies', PROPER_MOVIES),
  ...expandProper('music', PROPER_MUSIC),
  ...expandProper('history', PROPER_HISTORY),
  ...Object.entries(TR_FOOD).flatMap(([loc, t]) => expandLocale('food', loc, t)),
  ...Object.entries(TR_ANIMALS).flatMap(([loc, t]) => expandLocale('animals', loc, t)),
  ...Object.entries(TR_PLACES).flatMap(([loc, t]) => expandLocale('places', loc, t)),
  ...Object.entries(TR_JOBS).flatMap(([loc, t]) => expandLocale('jobs', loc, t)),
  ...Object.entries(TR_SPORTS).flatMap(([loc, t]) => expandLocale('sports', loc, t)),
  ...Object.entries(TR_VARIETY).flatMap(([loc, t]) => expandLocale('variety', loc, t)),
]

export function extendedFor(locale: string): PairData[] {
  return EXTENDED_PAIRS.filter((p) => p.locale === locale)
}
