/**
 * V3 expansion — 20 additional tricky word pairs per category per locale.
 *
 * Follows the V2 convention: invariant pools (MANGAS, CELEBRITIES, MOVIES,
 * MUSIC, HISTORY, TECH) share pairs across all 10 locales; translatable
 * pools (FOOD, ANIMALS, PLACES, JOBS, SPORTS) are per-locale, index-aligned.
 *
 * Difficulty mix per pool: 4 easy, 12 medium, 4 hard.
 *
 * Imported by seed.ts (DB seeding) and scripts/generate-offline-words.mjs
 * (offline pass-and-play generation).
 */

type Diff = 'easy' | 'medium' | 'hard'
type V3Triple = [string, string, Diff]

export type V3PairData = {
  wordA: string
  wordB: string
  difficulty: Diff
  category: string
  locale: string
}

const V3_LOCALES = ['en', 'fr', 'es', 'de', 'ar', 'it', 'pt', 'zh', 'ru', 'hi'] as const

const v3p = (cat: string, loc: string, ts: V3Triple[]): V3PairData[] =>
  ts.map(([a, b, d]) => ({ wordA: a, wordB: b, difficulty: d, category: cat, locale: loc }))

// ── INVARIANT POOLS (same pairs across all 10 locales) ──────────────────────

const V3_MANGAS: V3Triple[] = [
  ['Vegito', 'Gogeta', 'easy'],
  ['Koro-sensei', 'All Might', 'easy'],
  ['Ino', 'TenTen', 'easy'],
  ['Shikamaru', 'Neji', 'easy'],
  ['Fire Force', 'Jujutsu Kaisen', 'medium'],
  ['Konoha', 'Suna', 'medium'],
  ['Wano', 'Dressrosa', 'medium'],
  ['Rasengan', 'Chidori', 'medium'],
  ['Bankai', 'Shikai', 'medium'],
  ['Devil Fruit', 'Quirk', 'medium'],
  ['Haki', 'Nen', 'medium'],
  ['Sharingan', 'Byakugan', 'medium'],
  ['Mecha', 'Magical Girl', 'medium'],
  ['Shonen Jump', 'Shonen Magazine', 'medium'],
  ['Spy x Family', 'Dandadan', 'medium'],
  ['Bounty Hunter', 'Marine', 'medium'],
  ['Near', 'Mello', 'hard'],
  ['Akatsuki', 'Espada', 'hard'],
  ['Hashira', 'Kage', 'hard'],
  ['Senjutsu', 'Ninjutsu', 'hard'],
]

const V3_CELEBRITIES: V3Triple[] = [
  ['Khloe Kardashian', 'Kourtney Kardashian', 'easy'],
  ['Ariana Grande', 'Selena Gomez', 'easy'],
  ['Kevin Hart', 'Kevin James', 'easy'],
  ['Nicole Kidman', 'Reese Witherspoon', 'easy'],
  ['Erling Haaland', 'Jude Bellingham', 'medium'],
  ['Nikola Jokic', 'Giannis Antetokounmpo', 'medium'],
  ['Joe Rogan', 'Tim Ferriss', 'medium'],
  ['Trevor Noah', 'Jon Stewart', 'medium'],
  ['Gordon Ramsay', 'Bobby Flay', 'medium'],
  ['Pedro Almodovar', 'Woody Allen', 'medium'],
  ['Mike Tyson', 'Muhammad Ali', 'medium'],
  ['Ronaldinho', 'Ronaldo Nazario', 'medium'],
  ['Kai Cenat', 'IShowSpeed', 'medium'],
  ['Pokimane', 'Valkyrae', 'medium'],
  ['Zoe Saldana', 'Lupita Nyongo', 'medium'],
  ['Lorde', 'Halsey', 'medium'],
  ['Saoirse Ronan', 'Florence Pugh', 'hard'],
  ['Lee Chang-dong', 'Kim Ki-duk', 'hard'],
  ['Taika Waititi', 'Yorgos Lanthimos', 'hard'],
  ['Haruki Murakami', 'Yoko Ogawa', 'hard'],
]

const V3_MOVIES: V3Triple[] = [
  ['Avengers Endgame', 'Infinity War', 'easy'],
  ['Shrek', 'Puss in Boots', 'easy'],
  ['How to Train Your Dragon', 'Brave', 'easy'],
  ['Harry Potter', 'Fantastic Beasts', 'easy'],
  ['Kill Bill', 'Once Upon a Time in Hollywood', 'medium'],
  ['1917', 'Dunkirk', 'medium'],
  ['Gone with the Wind', 'Casablanca', 'medium'],
  ['The Shining', 'Misery', 'medium'],
  ['Inglourious Basterds', 'Valkyrie', 'medium'],
  ['Bullet Train', 'The Gentlemen', 'medium'],
  ['Ready or Not', 'Bodies Bodies Bodies', 'medium'],
  ['Past Lives', 'Aftersun', 'medium'],
  ['The Banshees of Inisherin', 'In Bruges', 'medium'],
  ['Prisoners', 'The Vanishing', 'medium'],
  ['Lion', 'Brooklyn', 'medium'],
  ['Roma', 'Cold War', 'medium'],
  ['Andrei Rublev', 'Mirror', 'hard'],
  ['Wings of Desire', 'Paris Texas', 'hard'],
  ['The 400 Blows', 'Breathless', 'hard'],
  ['Rashomon', 'Ikiru', 'hard'],
]

const V3_MUSIC: V3Triple[] = [
  ['Coldplay', 'U2', 'easy'],
  ['Elvis Presley', 'Chuck Berry', 'easy'],
  ['Tidal', 'Deezer', 'easy'],
  ['Walkman', 'iPod', 'easy'],
  ['Daft Punk', 'Justice', 'medium'],
  ['Diplo', 'Skrillex', 'medium'],
  ['Weezer', 'Blink-182', 'medium'],
  ['Cool Jazz', 'Hard Bop', 'medium'],
  ['Gospel', 'Spiritual', 'medium'],
  ['Troubadour', 'Minstrel', 'medium'],
  ['Madrigal', 'Motet', 'medium'],
  ['Grimes', 'FKA Twigs', 'medium'],
  ['Lil Uzi Vert', 'Playboi Carti', 'medium'],
  ['Sade', 'Anita Baker', 'medium'],
  ['Beach Boys', 'Jan and Dean', 'medium'],
  ['Woodwind', 'Brass', 'medium'],
  ['Theremin', 'Ondes Martenot', 'hard'],
  ['Shamisen', 'Biwa', 'hard'],
  ['Piazzolla', 'Gardel', 'hard'],
  ['Mariachi', 'Banda', 'hard'],
]

const V3_HISTORY: V3Triple[] = [
  ['FDR', 'Truman', 'easy'],
  ['Ancient Egypt', 'Ancient Rome', 'easy'],
  ['Battle of Britain', 'The Blitz', 'easy'],
  ['Watergate', 'Iran-Contra', 'easy'],
  ['Vermeer', 'Rembrandt', 'medium'],
  ['Ming Dynasty', 'Qing Dynasty', 'medium'],
  ['Louis XIV', 'Louis XVI', 'medium'],
  ['Marie Antoinette', 'Catherine de Medici', 'medium'],
  ['Zheng He', 'Vasco da Gama', 'medium'],
  ['Treaty of Paris', 'Treaty of Ghent', 'medium'],
  ['Ellis Island', 'Angel Island', 'medium'],
  ['Reagan', 'Gorbachev', 'medium'],
  ['Mary Queen of Scots', 'Anne Boleyn', 'medium'],
  ['Habeas Corpus', 'Due Process', 'medium'],
  ['Apartheid', 'Jim Crow', 'medium'],
  ['Battle of Agincourt', 'Battle of Hastings', 'medium'],
  ['Battle of Tours', 'Battle of Poitiers', 'hard'],
  ['Warring States', 'Spring and Autumn', 'hard'],
  ['Safavid Empire', 'Timurid Empire', 'hard'],
  ['Treaty of Trianon', 'Treaty of Sevres', 'hard'],
]

const V3_TECH: V3Triple[] = [
  ['iPad', 'Surface', 'easy'],
  ['AirPods', 'Galaxy Buds', 'easy'],
  ['Discord', 'Slack', 'easy'],
  ['Netflix', 'Prime Video', 'easy'],
  ['Svelte', 'Solid', 'medium'],
  ['Rust', 'Go', 'medium'],
  ['Jupyter', 'Colab', 'medium'],
  ['Figma', 'Sketch', 'medium'],
  ['Notion', 'Obsidian', 'medium'],
  ['GitHub', 'GitLab', 'medium'],
  ['Blender', 'Maya', 'medium'],
  ['Swift', 'Kotlin', 'medium'],
  ['Stripe', 'PayPal', 'medium'],
  ['Roblox', 'Minecraft', 'medium'],
  ['Meta Quest', 'Vision Pro', 'medium'],
  ['Twitter', 'Threads', 'medium'],
  ['LSTM', 'Transformer', 'hard'],
  ['ZFS', 'Btrfs', 'hard'],
  ['Terraform', 'Pulumi', 'hard'],
  ['Grafana', 'Kibana', 'hard'],
]

// ── TRANSLATABLE POOLS (per-locale, index-aligned) ──────────────────────────
// EN
const V3_FOOD_EN: V3Triple[] = [
  ['Thyme', 'Rosemary', 'easy'],
  ['Allspice', 'Cloves', 'easy'],
  ['Pastrami', 'Brisket', 'easy'],
  ['Ribeye', 'Sirloin', 'easy'],
  ['Tonkotsu', 'Shoyu', 'medium'],
  ['Katsu', 'Schnitzel', 'medium'],
  ['Mezcal', 'Tequila', 'medium'],
  ['Gin', 'Vodka', 'medium'],
  ['Rooibos', 'Masala Chai', 'medium'],
  ['Port', 'Sherry', 'medium'],
  ['Jollof Rice', 'Benachin', 'medium'],
  ['Carnitas', 'Al Pastor', 'medium'],
  ['Kugel', 'Latke', 'medium'],
  ['Persimmon', 'Quince', 'medium'],
  ['Provolone', 'Mozzarella', 'medium'],
  ['Stir Fry', 'Saute', 'medium'],
  ['Poaching', 'Simmering', 'hard'],
  ['Laksa', 'Mee Goreng', 'hard'],
  ['Vol-au-vent', 'Bouchee', 'hard'],
  ['Agar', 'Pectin', 'hard'],
]
const V3_ANIMALS_EN: V3Triple[] = [
  ['Pony', 'Stallion', 'easy'],
  ['Grasshopper', 'Locust', 'easy'],
  ['Magpie', 'Jay', 'easy'],
  ['Cardinal', 'Blue Jay', 'easy'],
  ['Tuna', 'Swordfish', 'medium'],
  ['Mongoose', 'Meerkat', 'medium'],
  ['Sea Cucumber', 'Sea Urchin', 'medium'],
  ['Koala', 'Wallaby', 'medium'],
  ['Snow Leopard', 'Mountain Lion', 'medium'],
  ['Lynx', 'Bobcat', 'medium'],
  ['Nightingale', 'Swallow', 'medium'],
  ['Albatross', 'Pelican', 'medium'],
  ['Emperor Penguin', 'King Penguin', 'medium'],
  ['Sloth', 'Anteater', 'medium'],
  ['Kookaburra', 'Kingfisher', 'medium'],
  ['Wolverine', 'Fisher', 'medium'],
  ['Pufferfish', 'Blowfish', 'hard'],
  ['Thresher Shark', 'Mako Shark', 'hard'],
  ['Coelacanth', 'Lungfish', 'hard'],
  ['Saiga', 'Pronghorn', 'hard'],
]
const V3_PLACES_EN: V3Triple[] = [
  ['Manila', 'Jakarta', 'easy'],
  ['Warsaw', 'Budapest', 'easy'],
  ['Shanghai', 'Beijing', 'easy'],
  ['Montreal', 'Quebec City', 'easy'],
  ['Louvre', 'Hermitage', 'medium'],
  ['Times Square', 'Piccadilly Circus', 'medium'],
  ['Champs-Elysees', 'Fifth Avenue', 'medium'],
  ['Wall Street', 'Shibuya', 'medium'],
  ['Algiers', 'Tunis', 'medium'],
  ['Chicago', 'Detroit', 'medium'],
  ['Shangri-La', 'Camelot', 'medium'],
  ['Reims', 'Avignon', 'medium'],
  ['Bern', 'Zurich', 'medium'],
  ['Liverpool', 'Manchester', 'medium'],
  ['Valencia', 'Zaragoza', 'medium'],
  ['Angel Falls', 'Victoria Falls', 'medium'],
  ['Kamchatka', 'Kuril Islands', 'hard'],
  ['Lhasa', 'Dharamshala', 'hard'],
  ['Timbuktu', 'Gao', 'hard'],
  ['Baku', 'Tbilisi', 'hard'],
]
const V3_JOBS_EN: V3Triple[] = [
  ['Sous Chef', 'Line Cook', 'easy'],
  ['Waitress', 'Hostess', 'easy'],
  ['Delivery Driver', 'Truck Driver', 'easy'],
  ['Carpenter', 'Joiner', 'easy'],
  ['Investment Banker', 'Hedge Fund Manager', 'medium'],
  ['Plastic Surgeon', 'Dermatologist', 'medium'],
  ['Therapist', 'Life Coach', 'medium'],
  ['ML Engineer', 'Data Scientist', 'medium'],
  ['Social Worker', 'Case Manager', 'medium'],
  ['Nurse Practitioner', 'Physician Assistant', 'medium'],
  ['Copyeditor', 'Proofreader', 'medium'],
  ['Real Estate Agent', 'Mortgage Broker', 'medium'],
  ['Wealth Manager', 'Portfolio Manager', 'medium'],
  ['Biologist', 'Ecologist', 'medium'],
  ['Interior Designer', 'Set Designer', 'medium'],
  ['Physical Therapist', 'Chiropractor', 'medium'],
  ['Casting Director', 'Talent Agent', 'hard'],
  ['Sommelier', 'Cicerone', 'hard'],
  ['Goldsmith', 'Silversmith', 'hard'],
  ['Furrier', 'Milliner', 'hard'],
]
const V3_SPORTS_EN: V3Triple[] = [
  ['Tennis', 'Beach Tennis', 'easy'],
  ['Dodgeball', 'Kickball', 'easy'],
  ['Bowling', 'Candlepin', 'easy'],
  ['Sprint', 'Middle Distance', 'easy'],
  ['Yachting', 'Sailing', 'medium'],
  ['Eventing', 'Show Jumping', 'medium'],
  ['Yoga', 'Pilates', 'medium'],
  ['Spin Class', 'HIIT', 'medium'],
  ['Aikido', 'Hapkido', 'medium'],
  ['Drag Racing', 'NASCAR', 'medium'],
  ['Sumo', 'Mongolian Wrestling', 'medium'],
  ['Skydiving', 'BASE Jumping', 'medium'],
  ['Quidditch', 'Ultimate Frisbee', 'medium'],
  ['Individual Medley', 'Relay', 'medium'],
  ['Handball', 'Netball', 'medium'],
  ['Roller Derby', 'Bandy', 'medium'],
  ['Muay Boran', 'Kalaripayattu', 'hard'],
  ['Hurling', 'Gaelic Football', 'hard'],
  ['Pato', 'Horseball', 'hard'],
  ['Boccia', 'Bocce', 'hard'],
]

// FR
const V3_FOOD_FR: V3Triple[] = [
  ['Thym', 'Romarin', 'easy'],
  ['Quatre-epices', 'Clou de girofle', 'easy'],
  ['Pastrami', 'Poitrine', 'easy'],
  ['Entrecote', 'Bavette', 'easy'],
  ['Tonkotsu', 'Shoyu', 'medium'],
  ['Katsu', 'Escalope viennoise', 'medium'],
  ['Mezcal', 'Tequila', 'medium'],
  ['Gin', 'Vodka', 'medium'],
  ['Rooibos', 'Chai masala', 'medium'],
  ['Porto', 'Xeres', 'medium'],
  ['Riz Jollof', 'Benachin', 'medium'],
  ['Carnitas', 'Al Pastor', 'medium'],
  ['Kugel', 'Latke', 'medium'],
  ['Kaki', 'Coing', 'medium'],
  ['Provolone', 'Mozzarella', 'medium'],
  ['Saute', 'Saisi', 'medium'],
  ['Pocher', 'Mijoter', 'hard'],
  ['Laksa', 'Mee Goreng', 'hard'],
  ['Vol-au-vent', 'Bouchee', 'hard'],
  ['Agar-agar', 'Pectine', 'hard'],
]
const V3_ANIMALS_FR: V3Triple[] = [
  ['Poney', 'Etalon', 'easy'],
  ['Sauterelle', 'Criquet pelerin', 'easy'],
  ['Pie', 'Geai', 'easy'],
  ['Cardinal', 'Geai bleu', 'easy'],
  ['Thon', 'Espadon', 'medium'],
  ['Mangouste', 'Suricate', 'medium'],
  ['Concombre de mer', 'Oursin', 'medium'],
  ['Koala', 'Wallaby', 'medium'],
  ['Leopard des neiges', 'Puma', 'medium'],
  ['Lynx', 'Lynx roux', 'medium'],
  ['Rossignol', 'Hirondelle', 'medium'],
  ['Albatros', 'Pelican', 'medium'],
  ['Manchot empereur', 'Manchot royal', 'medium'],
  ['Paresseux', 'Fourmilier', 'medium'],
  ['Kookaburra', 'Martin-pecheur', 'medium'],
  ['Carcajou', 'Pekan', 'medium'],
  ['Poisson-globe', 'Tetrodon', 'hard'],
  ['Requin-renard', 'Requin-taupe', 'hard'],
  ['Coelacanthe', 'Dipneuste', 'hard'],
  ['Saiga', 'Antilocapre', 'hard'],
]
const V3_PLACES_FR: V3Triple[] = [
  ['Manille', 'Jakarta', 'easy'],
  ['Varsovie', 'Budapest', 'easy'],
  ['Shanghai', 'Pekin', 'easy'],
  ['Montreal', 'Quebec', 'easy'],
  ['Louvre', 'Ermitage', 'medium'],
  ['Times Square', 'Piccadilly Circus', 'medium'],
  ['Champs-Elysees', 'Cinquieme Avenue', 'medium'],
  ['Wall Street', 'Shibuya', 'medium'],
  ['Alger', 'Tunis', 'medium'],
  ['Chicago', 'Detroit', 'medium'],
  ['Shangri-La', 'Camelot', 'medium'],
  ['Reims', 'Avignon', 'medium'],
  ['Berne', 'Zurich', 'medium'],
  ['Liverpool', 'Manchester', 'medium'],
  ['Valence', 'Saragosse', 'medium'],
  ['Chutes Angel', 'Chutes Victoria', 'medium'],
  ['Kamtchatka', 'Iles Kouriles', 'hard'],
  ['Lhassa', 'Dharamsala', 'hard'],
  ['Tombouctou', 'Gao', 'hard'],
  ['Bakou', 'Tbilissi', 'hard'],
]
const V3_JOBS_FR: V3Triple[] = [
  ['Sous-chef', 'Commis', 'easy'],
  ['Serveuse', 'Hotesse', 'easy'],
  ['Livreur', 'Camionneur', 'easy'],
  ['Charpentier', 'Menuisier', 'easy'],
  ['Banquier d affaires', 'Gestionnaire de fonds', 'medium'],
  ['Chirurgien plasticien', 'Dermatologue', 'medium'],
  ['Therapeute', 'Coach de vie', 'medium'],
  ['Ingenieur ML', 'Data Scientist', 'medium'],
  ['Assistant social', 'Gestionnaire de cas', 'medium'],
  ['Infirmier praticien', 'Assistant medecin', 'medium'],
  ['Correcteur', 'Relecteur', 'medium'],
  ['Agent immobilier', 'Courtier hypothecaire', 'medium'],
  ['Gestionnaire de patrimoine', 'Gestionnaire de portefeuille', 'medium'],
  ['Biologiste', 'Ecologue', 'medium'],
  ['Architecte d interieur', 'Chef decorateur', 'medium'],
  ['Kinesitherapeute', 'Chiropracteur', 'medium'],
  ['Directeur de casting', 'Agent artistique', 'hard'],
  ['Sommelier', 'Cicerone', 'hard'],
  ['Orfevre', 'Argentier', 'hard'],
  ['Fourreur', 'Modiste', 'hard'],
]
const V3_SPORTS_FR: V3Triple[] = [
  ['Tennis', 'Beach tennis', 'easy'],
  ['Ballon prisonnier', 'Kickball', 'easy'],
  ['Bowling', 'Quilles de neuf', 'easy'],
  ['Sprint', 'Demi-fond', 'easy'],
  ['Yachting', 'Voile', 'medium'],
  ['Concours complet', 'Saut d obstacles', 'medium'],
  ['Yoga', 'Pilates', 'medium'],
  ['Spinning', 'HIIT', 'medium'],
  ['Aikido', 'Hapkido', 'medium'],
  ['Drag racing', 'NASCAR', 'medium'],
  ['Sumo', 'Lutte mongole', 'medium'],
  ['Parachutisme', 'Base jump', 'medium'],
  ['Quidditch', 'Ultimate', 'medium'],
  ['Quatre nages', 'Relais', 'medium'],
  ['Handball', 'Netball', 'medium'],
  ['Roller derby', 'Bandy', 'medium'],
  ['Muay Boran', 'Kalaripayattu', 'hard'],
  ['Hurling', 'Football gaelique', 'hard'],
  ['Pato', 'Horse-ball', 'hard'],
  ['Boccia', 'Petanque italienne', 'hard'],
]

// ES
const V3_FOOD_ES: V3Triple[] = [
  ['Tomillo', 'Romero', 'easy'],
  ['Pimienta de Jamaica', 'Clavo', 'easy'],
  ['Pastrami', 'Falda', 'easy'],
  ['Chuleton', 'Solomillo', 'easy'],
  ['Tonkotsu', 'Shoyu', 'medium'],
  ['Katsu', 'Milanesa', 'medium'],
  ['Mezcal', 'Tequila', 'medium'],
  ['Ginebra', 'Vodka', 'medium'],
  ['Rooibos', 'Chai masala', 'medium'],
  ['Oporto', 'Jerez', 'medium'],
  ['Arroz Jollof', 'Benachin', 'medium'],
  ['Carnitas', 'Al Pastor', 'medium'],
  ['Kugel', 'Latke', 'medium'],
  ['Caqui', 'Membrillo', 'medium'],
  ['Provolone', 'Mozzarella', 'medium'],
  ['Saltear', 'Rehogar', 'medium'],
  ['Escalfar', 'Hervir a fuego lento', 'hard'],
  ['Laksa', 'Mee Goreng', 'hard'],
  ['Volovan', 'Bocadito', 'hard'],
  ['Agar-agar', 'Pectina', 'hard'],
]
const V3_ANIMALS_ES: V3Triple[] = [
  ['Poni', 'Semental', 'easy'],
  ['Saltamontes', 'Langosta migratoria', 'easy'],
  ['Urraca', 'Arrendajo', 'easy'],
  ['Cardenal', 'Arrendajo azul', 'easy'],
  ['Atun', 'Pez espada', 'medium'],
  ['Mangosta', 'Suricata', 'medium'],
  ['Pepino de mar', 'Erizo de mar', 'medium'],
  ['Koala', 'Walabi', 'medium'],
  ['Leopardo de las nieves', 'Puma', 'medium'],
  ['Lince', 'Lince rojo', 'medium'],
  ['Ruisenor', 'Golondrina', 'medium'],
  ['Albatros', 'Pelicano', 'medium'],
  ['Pinguino emperador', 'Pinguino rey', 'medium'],
  ['Perezoso', 'Oso hormiguero', 'medium'],
  ['Cucaburra', 'Martin pescador', 'medium'],
  ['Gloton', 'Marta pescadora', 'medium'],
  ['Pez globo', 'Pez botete', 'hard'],
  ['Tiburon zorro', 'Tiburon mako', 'hard'],
  ['Celacanto', 'Pez pulmonado', 'hard'],
  ['Saiga', 'Berrendo', 'hard'],
]
const V3_PLACES_ES: V3Triple[] = [
  ['Manila', 'Yakarta', 'easy'],
  ['Varsovia', 'Budapest', 'easy'],
  ['Shanghai', 'Pekin', 'easy'],
  ['Montreal', 'Ciudad de Quebec', 'easy'],
  ['Louvre', 'Hermitage', 'medium'],
  ['Times Square', 'Piccadilly Circus', 'medium'],
  ['Campos Eliseos', 'Quinta Avenida', 'medium'],
  ['Wall Street', 'Shibuya', 'medium'],
  ['Argel', 'Tunez', 'medium'],
  ['Chicago', 'Detroit', 'medium'],
  ['Shangri-La', 'Camelot', 'medium'],
  ['Reims', 'Avinon', 'medium'],
  ['Berna', 'Zurich', 'medium'],
  ['Liverpool', 'Manchester', 'medium'],
  ['Valencia', 'Zaragoza', 'medium'],
  ['Salto Angel', 'Cataratas Victoria', 'medium'],
  ['Kamchatka', 'Islas Kuriles', 'hard'],
  ['Lhasa', 'Dharamsala', 'hard'],
  ['Tombuctu', 'Gao', 'hard'],
  ['Baku', 'Tiflis', 'hard'],
]
const V3_JOBS_ES: V3Triple[] = [
  ['Sous Chef', 'Cocinero de linea', 'easy'],
  ['Camarera', 'Anfitriona', 'easy'],
  ['Repartidor', 'Camionero', 'easy'],
  ['Carpintero', 'Ebanista', 'easy'],
  ['Banquero de inversion', 'Gestor de fondos', 'medium'],
  ['Cirujano plastico', 'Dermatologo', 'medium'],
  ['Terapeuta', 'Coach de vida', 'medium'],
  ['Ingeniero ML', 'Cientifico de datos', 'medium'],
  ['Trabajador social', 'Gestor de casos', 'medium'],
  ['Enfermero especialista', 'Asistente medico', 'medium'],
  ['Corrector de estilo', 'Revisor', 'medium'],
  ['Agente inmobiliario', 'Corredor hipotecario', 'medium'],
  ['Gestor patrimonial', 'Gestor de cartera', 'medium'],
  ['Biologo', 'Ecologo', 'medium'],
  ['Disenador de interiores', 'Escenografo', 'medium'],
  ['Fisioterapeuta', 'Quiropractico', 'medium'],
  ['Director de casting', 'Agente de talento', 'hard'],
  ['Sommelier', 'Ciceron', 'hard'],
  ['Orfebre', 'Platero', 'hard'],
  ['Peletero', 'Sombrerero', 'hard'],
]
const V3_SPORTS_ES: V3Triple[] = [
  ['Tenis', 'Tenis playa', 'easy'],
  ['Balon prisionero', 'Kickball', 'easy'],
  ['Bolos', 'Candlepin', 'easy'],
  ['Velocidad', 'Media distancia', 'easy'],
  ['Nautica', 'Vela', 'medium'],
  ['Concurso completo', 'Salto ecuestre', 'medium'],
  ['Yoga', 'Pilates', 'medium'],
  ['Spinning', 'HIIT', 'medium'],
  ['Aikido', 'Hapkido', 'medium'],
  ['Drag racing', 'NASCAR', 'medium'],
  ['Sumo', 'Lucha mongola', 'medium'],
  ['Paracaidismo', 'Salto BASE', 'medium'],
  ['Quidditch', 'Ultimate frisbee', 'medium'],
  ['Estilos individuales', 'Relevos', 'medium'],
  ['Balonmano', 'Netball', 'medium'],
  ['Roller derby', 'Bandy', 'medium'],
  ['Muay Boran', 'Kalaripayattu', 'hard'],
  ['Hurling', 'Futbol gaelico', 'hard'],
  ['Pato', 'Horseball', 'hard'],
  ['Boccia', 'Bocha', 'hard'],
]

// DE
const V3_FOOD_DE: V3Triple[] = [
  ['Thymian', 'Rosmarin', 'easy'],
  ['Piment', 'Gewuerznelken', 'easy'],
  ['Pastrami', 'Rinderbrust', 'easy'],
  ['Ribeye', 'Roastbeef', 'easy'],
  ['Tonkotsu', 'Shoyu', 'medium'],
  ['Katsu', 'Schnitzel', 'medium'],
  ['Mezcal', 'Tequila', 'medium'],
  ['Gin', 'Wodka', 'medium'],
  ['Rooibos', 'Masala Chai', 'medium'],
  ['Portwein', 'Sherry', 'medium'],
  ['Jollof-Reis', 'Benachin', 'medium'],
  ['Carnitas', 'Al Pastor', 'medium'],
  ['Kugel', 'Latke', 'medium'],
  ['Kaki', 'Quitte', 'medium'],
  ['Provolone', 'Mozzarella', 'medium'],
  ['Pfannenruehren', 'Sautieren', 'medium'],
  ['Pochieren', 'Koecheln', 'hard'],
  ['Laksa', 'Mee Goreng', 'hard'],
  ['Blaetterteigpastete', 'Bouchee', 'hard'],
  ['Agar', 'Pektin', 'hard'],
]
const V3_ANIMALS_DE: V3Triple[] = [
  ['Pony', 'Hengst', 'easy'],
  ['Heuschrecke', 'Wanderheuschrecke', 'easy'],
  ['Elster', 'Eichelhaeher', 'easy'],
  ['Kardinal', 'Blauhaeher', 'easy'],
  ['Thunfisch', 'Schwertfisch', 'medium'],
  ['Mungo', 'Erdmaennchen', 'medium'],
  ['Seegurke', 'Seeigel', 'medium'],
  ['Koala', 'Wallaby', 'medium'],
  ['Schneeleopard', 'Puma', 'medium'],
  ['Luchs', 'Rotluchs', 'medium'],
  ['Nachtigall', 'Schwalbe', 'medium'],
  ['Albatros', 'Pelikan', 'medium'],
  ['Kaiserpinguin', 'Koenigspinguin', 'medium'],
  ['Faultier', 'Ameisenbaer', 'medium'],
  ['Kookaburra', 'Eisvogel', 'medium'],
  ['Vielfrass', 'Fischermarder', 'medium'],
  ['Kugelfisch', 'Igelfisch', 'hard'],
  ['Fuchshai', 'Makohai', 'hard'],
  ['Quastenflosser', 'Lungenfisch', 'hard'],
  ['Saiga', 'Gabelbock', 'hard'],
]
const V3_PLACES_DE: V3Triple[] = [
  ['Manila', 'Jakarta', 'easy'],
  ['Warschau', 'Budapest', 'easy'],
  ['Shanghai', 'Peking', 'easy'],
  ['Montreal', 'Quebec', 'easy'],
  ['Louvre', 'Eremitage', 'medium'],
  ['Times Square', 'Piccadilly Circus', 'medium'],
  ['Champs-Elysees', 'Fifth Avenue', 'medium'],
  ['Wall Street', 'Shibuya', 'medium'],
  ['Algier', 'Tunis', 'medium'],
  ['Chicago', 'Detroit', 'medium'],
  ['Shangri-La', 'Camelot', 'medium'],
  ['Reims', 'Avignon', 'medium'],
  ['Bern', 'Zuerich', 'medium'],
  ['Liverpool', 'Manchester', 'medium'],
  ['Valencia', 'Saragossa', 'medium'],
  ['Angel-Faelle', 'Viktoriafaelle', 'medium'],
  ['Kamtschatka', 'Kurilen', 'hard'],
  ['Lhasa', 'Dharamsala', 'hard'],
  ['Timbuktu', 'Gao', 'hard'],
  ['Baku', 'Tiflis', 'hard'],
]
const V3_JOBS_DE: V3Triple[] = [
  ['Sous-Chef', 'Linienkoch', 'easy'],
  ['Kellnerin', 'Gastgeberin', 'easy'],
  ['Lieferfahrer', 'LKW-Fahrer', 'easy'],
  ['Zimmermann', 'Tischler', 'easy'],
  ['Investmentbanker', 'Hedgefonds-Manager', 'medium'],
  ['Plastischer Chirurg', 'Dermatologe', 'medium'],
  ['Therapeut', 'Lebensberater', 'medium'],
  ['ML-Ingenieur', 'Data Scientist', 'medium'],
  ['Sozialarbeiter', 'Fallmanager', 'medium'],
  ['Krankenpfleger', 'Arzthelfer', 'medium'],
  ['Lektor', 'Korrektor', 'medium'],
  ['Immobilienmakler', 'Hypothekenmakler', 'medium'],
  ['Vermoegensverwalter', 'Portfoliomanager', 'medium'],
  ['Biologe', 'Oekologe', 'medium'],
  ['Innenarchitekt', 'Buehnenbildner', 'medium'],
  ['Physiotherapeut', 'Chiropraktiker', 'medium'],
  ['Casting-Direktor', 'Talentagent', 'hard'],
  ['Sommelier', 'Cicerone', 'hard'],
  ['Goldschmied', 'Silberschmied', 'hard'],
  ['Kuerschner', 'Hutmacher', 'hard'],
]
const V3_SPORTS_DE: V3Triple[] = [
  ['Tennis', 'Beachtennis', 'easy'],
  ['Voelkerball', 'Kickball', 'easy'],
  ['Bowling', 'Kegeln', 'easy'],
  ['Sprint', 'Mittelstrecke', 'easy'],
  ['Yachting', 'Segeln', 'medium'],
  ['Vielseitigkeit', 'Springreiten', 'medium'],
  ['Yoga', 'Pilates', 'medium'],
  ['Spinning', 'HIIT', 'medium'],
  ['Aikido', 'Hapkido', 'medium'],
  ['Dragster', 'NASCAR', 'medium'],
  ['Sumo', 'Mongolisches Ringen', 'medium'],
  ['Fallschirmspringen', 'Base-Jumping', 'medium'],
  ['Quidditch', 'Ultimate Frisbee', 'medium'],
  ['Lagen', 'Staffel', 'medium'],
  ['Handball', 'Netball', 'medium'],
  ['Roller Derby', 'Bandy', 'medium'],
  ['Muay Boran', 'Kalaripayattu', 'hard'],
  ['Hurling', 'Gaelic Football', 'hard'],
  ['Pato', 'Horseball', 'hard'],
  ['Boccia', 'Boccia klassisch', 'hard'],
]

// AR
const V3_FOOD_AR: V3Triple[] = [
  ['زعتر','إكليل الجبل','easy'],
  ['بهار جامايكا','قرنفل','easy'],
  ['بسطرمة','صدر بقر','easy'],
  ['ريب آي','سيرلوين','easy'],
  ['تونكوتسو','شويو','medium'],
  ['كاتسو','شنيتزل','medium'],
  ['ميزكال','تيكيلا','medium'],
  ['جن','فودكا','medium'],
  ['شاي رويبوس','شاي ماسالا','medium'],
  ['بورتو','شيري','medium'],
  ['أرز جولوف','بيناشين','medium'],
  ['كارنيتاس','آل باستور','medium'],
  ['كوغل','لاتكي','medium'],
  ['كاكي','سفرجل','medium'],
  ['بروفولوني','موزاريلا','medium'],
  ['قلي سريع','سوتيه','medium'],
  ['سلق بطيء','طهي بطيء','hard'],
  ['لكسا','مي جورينج','hard'],
  ['فول أو فان','بوشيه','hard'],
  ['أجار','بكتين','hard'],
]
const V3_ANIMALS_AR: V3Triple[] = [
  ['مهر','فحل','easy'],
  ['جندب','جراد هاجر','easy'],
  ['عقعق','قيق','easy'],
  ['كاردينال','قيق أزرق','easy'],
  ['تونة','أبو سيف','medium'],
  ['نمس','سرقاط','medium'],
  ['خيار البحر','قنفذ البحر','medium'],
  ['كوالا','ولب','medium'],
  ['نمر الثلج','كوغار','medium'],
  ['وشق','بوبكات','medium'],
  ['عندليب','سنونو','medium'],
  ['طائر القطرس','بجع','medium'],
  ['بطريق إمبراطور','بطريق ملكي','medium'],
  ['كسلان','آكل النمل','medium'],
  ['كوكابورا','رفراف','medium'],
  ['ولفرين','فيشر','medium'],
  ['سمكة منتفخة','سمكة بلوفيش','hard'],
  ['قرش الدراس','قرش ماكو','hard'],
  ['سيلاكانث','سمك رئوي','hard'],
  ['ساغا','أنتيلوكابرا','hard'],
]
const V3_PLACES_AR: V3Triple[] = [
  ['مانيلا','جاكرتا','easy'],
  ['وارسو','بودابست','easy'],
  ['شنغهاي','بكين','easy'],
  ['مونتريال','مدينة كيبيك','easy'],
  ['متحف اللوفر','متحف الإرميتاج','medium'],
  ['تايمز سكوير','ساحة بيكاديللي','medium'],
  ['الشانزليزيه','الجادة الخامسة','medium'],
  ['وول ستريت','شيبويا','medium'],
  ['الجزائر','تونس','medium'],
  ['شيكاغو','ديترويت','medium'],
  ['شانغريلا','كاميلوت','medium'],
  ['ريمس','أفينيون','medium'],
  ['برن','زيورخ','medium'],
  ['ليفربول','مانشستر','medium'],
  ['فالنسيا','سرقسطة','medium'],
  ['شلالات أنجل','شلالات فيكتوريا','medium'],
  ['كامتشاتكا','جزر الكوريل','hard'],
  ['لاسا','دارامسالا','hard'],
  ['تمبكتو','جاو','hard'],
  ['باكو','تبليسي','hard'],
]
const V3_JOBS_AR: V3Triple[] = [
  ['سوشيف','طاهٍ خط','easy'],
  ['نادلة','مضيفة','easy'],
  ['سائق توصيل','سائق شاحنة','easy'],
  ['نجار إنشاءات','نجار موبيليا','easy'],
  ['مصرفي استثماري','مدير صناديق تحوط','medium'],
  ['جراح تجميل','طبيب أمراض جلدية','medium'],
  ['معالج نفسي','مدرب حياة','medium'],
  ['مهندس تعلم آلي','عالم بيانات','medium'],
  ['أخصائي اجتماعي','مدير حالات','medium'],
  ['ممرض ممارس','مساعد طبيب','medium'],
  ['محرر نسخ','مدقق لغوي','medium'],
  ['وكيل عقارات','وسيط رهن','medium'],
  ['مدير ثروات','مدير محفظة','medium'],
  ['عالم أحياء','عالم بيئة','medium'],
  ['مصمم داخلي','مصمم مناظر','medium'],
  ['معالج فيزيائي','مقوم عظام','medium'],
  ['مدير اختيار ممثلين','وكيل مواهب','hard'],
  ['خبير نبيذ','خبير بيرة','hard'],
  ['صائغ ذهب','صائغ فضة','hard'],
  ['صانع فراء','صانع قبعات','hard'],
]
const V3_SPORTS_AR: V3Triple[] = [
  ['تنس','تنس شاطئي','easy'],
  ['كرة الإخراج','كرة الركل','easy'],
  ['بولينغ','كاندلبين','easy'],
  ['عدو قصير','مسافة متوسطة','easy'],
  ['يخوت','إبحار','medium'],
  ['إيفنتينغ','قفز الحواجز','medium'],
  ['يوغا','بيلاتس','medium'],
  ['سبينينغ','تمارين مكثفة','medium'],
  ['آيكيدو','هابكيدو','medium'],
  ['سباق تسارع','ناسكار','medium'],
  ['سومو','مصارعة منغولية','medium'],
  ['قفز بالمظلات','قفز بيس','medium'],
  ['كويدتش','ألتيميت فريزبي','medium'],
  ['سباحة فردية متنوعة','تتابع','medium'],
  ['كرة اليد','كرة الشبكة','medium'],
  ['رولر ديربي','باندي','medium'],
  ['مواي بوران','كالاريبياتو','hard'],
  ['هورلينغ','كرة القدم الغيلية','hard'],
  ['باتو','هورس بول','hard'],
  ['بوتشا','بوتشي','hard'],
]

// IT
const V3_FOOD_IT: V3Triple[] = [
  ['Timo', 'Rosmarino', 'easy'],
  ['Pepe della Giamaica', 'Chiodi di garofano', 'easy'],
  ['Pastrami', 'Punta di petto', 'easy'],
  ['Costata', 'Controfiletto', 'easy'],
  ['Tonkotsu', 'Shoyu', 'medium'],
  ['Katsu', 'Cotoletta', 'medium'],
  ['Mezcal', 'Tequila', 'medium'],
  ['Gin', 'Vodka', 'medium'],
  ['Rooibos', 'Chai masala', 'medium'],
  ['Porto', 'Sherry', 'medium'],
  ['Riso Jollof', 'Benachin', 'medium'],
  ['Carnitas', 'Al Pastor', 'medium'],
  ['Kugel', 'Latke', 'medium'],
  ['Cachi', 'Cotogna', 'medium'],
  ['Provolone', 'Mozzarella', 'medium'],
  ['Saltare in padella', 'Soffriggere', 'medium'],
  ['Affogare', 'Sobbollire', 'hard'],
  ['Laksa', 'Mee Goreng', 'hard'],
  ['Vol-au-vent', 'Bouchee', 'hard'],
  ['Agar-agar', 'Pectina', 'hard'],
]
const V3_ANIMALS_IT: V3Triple[] = [
  ['Pony', 'Stallone', 'easy'],
  ['Cavalletta', 'Locusta migratoria', 'easy'],
  ['Gazza', 'Ghiandaia', 'easy'],
  ['Cardinale', 'Ghiandaia azzurra', 'easy'],
  ['Tonno', 'Pesce spada', 'medium'],
  ['Mangusta', 'Suricato', 'medium'],
  ['Cetriolo di mare', 'Riccio di mare', 'medium'],
  ['Koala', 'Wallaby', 'medium'],
  ['Leopardo delle nevi', 'Puma', 'medium'],
  ['Lince', 'Lince rossa', 'medium'],
  ['Usignolo', 'Rondine', 'medium'],
  ['Albatros', 'Pellicano', 'medium'],
  ['Pinguino imperatore', 'Pinguino reale', 'medium'],
  ['Bradipo', 'Formichiere', 'medium'],
  ['Kookaburra', 'Martin pescatore', 'medium'],
  ['Ghiottone', 'Martora pescatrice', 'medium'],
  ['Pesce palla', 'Pesce istrice', 'hard'],
  ['Squalo volpe', 'Squalo mako', 'hard'],
  ['Celacanto', 'Dipnoi', 'hard'],
  ['Saiga', 'Antilocapra', 'hard'],
]
const V3_PLACES_IT: V3Triple[] = [
  ['Manila', 'Giacarta', 'easy'],
  ['Varsavia', 'Budapest', 'easy'],
  ['Shanghai', 'Pechino', 'easy'],
  ['Montreal', 'Quebec', 'easy'],
  ['Louvre', 'Ermitage', 'medium'],
  ['Times Square', 'Piccadilly Circus', 'medium'],
  ['Campi Elisi', 'Quinta Strada', 'medium'],
  ['Wall Street', 'Shibuya', 'medium'],
  ['Algeri', 'Tunisi', 'medium'],
  ['Chicago', 'Detroit', 'medium'],
  ['Shangri-La', 'Camelot', 'medium'],
  ['Reims', 'Avignone', 'medium'],
  ['Berna', 'Zurigo', 'medium'],
  ['Liverpool', 'Manchester', 'medium'],
  ['Valencia', 'Saragozza', 'medium'],
  ['Cascate Angel', 'Cascate Vittoria', 'medium'],
  ['Kamchatka', 'Isole Curili', 'hard'],
  ['Lhasa', 'Dharamsala', 'hard'],
  ['Timbuktu', 'Gao', 'hard'],
  ['Baku', 'Tbilisi', 'hard'],
]
const V3_JOBS_IT: V3Triple[] = [
  ['Sous Chef', 'Cuoco di linea', 'easy'],
  ['Cameriera', 'Hostess di sala', 'easy'],
  ['Fattorino', 'Camionista', 'easy'],
  ['Carpentiere', 'Falegname', 'easy'],
  ['Banchiere d investimento', 'Gestore di hedge fund', 'medium'],
  ['Chirurgo plastico', 'Dermatologo', 'medium'],
  ['Terapeuta', 'Life Coach', 'medium'],
  ['Ingegnere ML', 'Data Scientist', 'medium'],
  ['Assistente sociale', 'Case Manager', 'medium'],
  ['Infermiere professionista', 'Assistente medico', 'medium'],
  ['Redattore', 'Correttore di bozze', 'medium'],
  ['Agente immobiliare', 'Mediatore creditizio', 'medium'],
  ['Gestore patrimoniale', 'Gestore di portafoglio', 'medium'],
  ['Biologo', 'Ecologo', 'medium'],
  ['Architetto d interni', 'Scenografo', 'medium'],
  ['Fisioterapista', 'Chiropratico', 'medium'],
  ['Direttore del casting', 'Agente dei talenti', 'hard'],
  ['Sommelier', 'Cicerone della birra', 'hard'],
  ['Orafo', 'Argentiere', 'hard'],
  ['Pellicciaio', 'Modista', 'hard'],
]
const V3_SPORTS_IT: V3Triple[] = [
  ['Tennis', 'Beach tennis', 'easy'],
  ['Palla avvelenata', 'Kickball', 'easy'],
  ['Bowling', 'Candlepin', 'easy'],
  ['Sprint', 'Mezzofondo', 'easy'],
  ['Yachting', 'Vela', 'medium'],
  ['Completo', 'Salto ostacoli', 'medium'],
  ['Yoga', 'Pilates', 'medium'],
  ['Spinning', 'HIIT', 'medium'],
  ['Aikido', 'Hapkido', 'medium'],
  ['Drag racing', 'NASCAR', 'medium'],
  ['Sumo', 'Lotta mongola', 'medium'],
  ['Paracadutismo', 'Base jumping', 'medium'],
  ['Quidditch', 'Ultimate frisbee', 'medium'],
  ['Misti', 'Staffetta', 'medium'],
  ['Pallamano', 'Netball', 'medium'],
  ['Roller derby', 'Bandy', 'medium'],
  ['Muay Boran', 'Kalaripayattu', 'hard'],
  ['Hurling', 'Calcio gaelico', 'hard'],
  ['Pato', 'Horseball', 'hard'],
  ['Boccia', 'Bocce classiche', 'hard'],
]

// PT
const V3_FOOD_PT: V3Triple[] = [
  ['Tomilho', 'Alecrim', 'easy'],
  ['Pimenta-da-jamaica', 'Cravo-da-india', 'easy'],
  ['Pastrami', 'Peito bovino', 'easy'],
  ['Entrecosto', 'Alcatra', 'easy'],
  ['Tonkotsu', 'Shoyu', 'medium'],
  ['Katsu', 'Milanesa', 'medium'],
  ['Mezcal', 'Tequila', 'medium'],
  ['Gin', 'Vodka', 'medium'],
  ['Rooibos', 'Chai masala', 'medium'],
  ['Vinho do Porto', 'Xerez', 'medium'],
  ['Arroz Jollof', 'Benachin', 'medium'],
  ['Carnitas', 'Al Pastor', 'medium'],
  ['Kugel', 'Latke', 'medium'],
  ['Caqui', 'Marmelo', 'medium'],
  ['Provolone', 'Mucarela', 'medium'],
  ['Salteado', 'Refogado', 'medium'],
  ['Escalfar', 'Fervura lenta', 'hard'],
  ['Laksa', 'Mee Goreng', 'hard'],
  ['Vol-au-vent', 'Bouchee', 'hard'],
  ['Agar', 'Pectina', 'hard'],
]
const V3_ANIMALS_PT: V3Triple[] = [
  ['Ponei', 'Garanhao', 'easy'],
  ['Gafanhoto', 'Locusta migratoria', 'easy'],
  ['Pega', 'Gaio', 'easy'],
  ['Cardeal', 'Gaio azul', 'easy'],
  ['Atum', 'Peixe-espada', 'medium'],
  ['Mangusto', 'Suricato', 'medium'],
  ['Pepino-do-mar', 'Ourico-do-mar', 'medium'],
  ['Coala', 'Wallaby', 'medium'],
  ['Leopardo-das-neves', 'Puma', 'medium'],
  ['Lince', 'Lince-pardo', 'medium'],
  ['Rouxinol', 'Andorinha', 'medium'],
  ['Albatroz', 'Pelicano', 'medium'],
  ['Pinguim-imperador', 'Pinguim-rei', 'medium'],
  ['Preguica', 'Tamandua', 'medium'],
  ['Kookaburra', 'Martim-pescador', 'medium'],
  ['Carcaju', 'Pekan', 'medium'],
  ['Baiacu', 'Peixe-balao', 'hard'],
  ['Tubarao-raposa', 'Tubarao-mako', 'hard'],
  ['Celacanto', 'Peixe pulmonado', 'hard'],
  ['Saiga', 'Pronghorn', 'hard'],
]
const V3_PLACES_PT: V3Triple[] = [
  ['Manila', 'Jacarta', 'easy'],
  ['Varsovia', 'Budapeste', 'easy'],
  ['Xangai', 'Pequim', 'easy'],
  ['Montreal', 'Quebec', 'easy'],
  ['Louvre', 'Hermitage', 'medium'],
  ['Times Square', 'Piccadilly Circus', 'medium'],
  ['Campos Eliseos', 'Quinta Avenida', 'medium'],
  ['Wall Street', 'Shibuya', 'medium'],
  ['Argel', 'Tunis', 'medium'],
  ['Chicago', 'Detroit', 'medium'],
  ['Shangri-La', 'Camelot', 'medium'],
  ['Reims', 'Avinhao', 'medium'],
  ['Berna', 'Zurique', 'medium'],
  ['Liverpool', 'Manchester', 'medium'],
  ['Valencia', 'Saragoca', 'medium'],
  ['Salto Angel', 'Cataratas Vitoria', 'medium'],
  ['Kamchatka', 'Ilhas Curilas', 'hard'],
  ['Lhasa', 'Dharamsala', 'hard'],
  ['Timbuktu', 'Gao', 'hard'],
  ['Baku', 'Tbilisi', 'hard'],
]
const V3_JOBS_PT: V3Triple[] = [
  ['Sous Chef', 'Cozinheiro de linha', 'easy'],
  ['Garconete', 'Anfitria', 'easy'],
  ['Entregador', 'Caminhoneiro', 'easy'],
  ['Carpinteiro', 'Marceneiro', 'easy'],
  ['Banqueiro de investimento', 'Gestor de fundos', 'medium'],
  ['Cirurgiao plastico', 'Dermatologista', 'medium'],
  ['Terapeuta', 'Coach de vida', 'medium'],
  ['Engenheiro ML', 'Cientista de dados', 'medium'],
  ['Assistente social', 'Gestor de casos', 'medium'],
  ['Enfermeiro especialista', 'Assistente medico', 'medium'],
  ['Copidesque', 'Revisor', 'medium'],
  ['Corretor imobiliario', 'Corretor hipotecario', 'medium'],
  ['Gestor patrimonial', 'Gestor de carteira', 'medium'],
  ['Biologo', 'Ecologo', 'medium'],
  ['Designer de interiores', 'Cenografo', 'medium'],
  ['Fisioterapeuta', 'Quiropratico', 'medium'],
  ['Diretor de elenco', 'Agente de talentos', 'hard'],
  ['Sommelier', 'Cicerone', 'hard'],
  ['Ourives', 'Prateiro', 'hard'],
  ['Peleiro', 'Chapeleiro', 'hard'],
]
const V3_SPORTS_PT: V3Triple[] = [
  ['Tenis', 'Beach tennis', 'easy'],
  ['Queimada', 'Kickball', 'easy'],
  ['Boliche', 'Candlepin', 'easy'],
  ['Sprint', 'Meia-distancia', 'easy'],
  ['Iatismo', 'Vela', 'medium'],
  ['Concurso completo', 'Salto de obstaculos', 'medium'],
  ['Yoga', 'Pilates', 'medium'],
  ['Spinning', 'HIIT', 'medium'],
  ['Aikido', 'Hapkido', 'medium'],
  ['Drag racing', 'NASCAR', 'medium'],
  ['Sumo', 'Luta mongol', 'medium'],
  ['Paraquedismo', 'Salto BASE', 'medium'],
  ['Quadribol', 'Ultimate frisbee', 'medium'],
  ['Medley individual', 'Revezamento', 'medium'],
  ['Handebol', 'Netball', 'medium'],
  ['Roller derby', 'Bandy', 'medium'],
  ['Muay Boran', 'Kalaripayattu', 'hard'],
  ['Hurling', 'Futebol gaelico', 'hard'],
  ['Pato', 'Horseball', 'hard'],
  ['Bocha paralimpica', 'Bocce', 'hard'],
]

// ZH
const V3_FOOD_ZH: V3Triple[] = [
  ['百里香','迷迭香','easy'],
  ['多香果','丁香','easy'],
  ['熏牛肉','牛胸肉','easy'],
  ['肋眼','西冷','easy'],
  ['豚骨拉面','酱油拉面','medium'],
  ['炸猪排','炸肉排','medium'],
  ['梅斯卡尔','龙舌兰','medium'],
  ['金酒','伏特加','medium'],
  ['博士茶','印度香料茶','medium'],
  ['波特酒','雪利酒','medium'],
  ['约洛夫米饭','贝纳钦','medium'],
  ['墨西哥慢炖猪肉','阿尔帕斯托','medium'],
  ['犹太布丁','土豆饼','medium'],
  ['柿子','榅桲','medium'],
  ['波罗伏洛','马苏里拉','medium'],
  ['快炒','煸炒','medium'],
  ['水波煮','慢炖','hard'],
  ['叻沙','炒面','hard'],
  ['酥皮酥盒','小酥盒','hard'],
  ['琼脂','果胶','hard'],
]
const V3_ANIMALS_ZH: V3Triple[] = [
  ['小马','种马','easy'],
  ['蚱蜢','飞蝗','easy'],
  ['喜鹊','松鸦','easy'],
  ['主红雀','蓝松鸦','easy'],
  ['金枪鱼','剑鱼','medium'],
  ['獴','猫鼬','medium'],
  ['海参','海胆','medium'],
  ['考拉','沙袋鼠','medium'],
  ['雪豹','美洲狮','medium'],
  ['猞猁','短尾猫','medium'],
  ['夜莺','燕子','medium'],
  ['信天翁','鹈鹕','medium'],
  ['帝企鹅','王企鹅','medium'],
  ['树懒','食蚁兽','medium'],
  ['笑翠鸟','翠鸟','medium'],
  ['狼獾','渔貂','medium'],
  ['河豚','气鼓鱼','hard'],
  ['长尾鲨','鲭鲨','hard'],
  ['腔棘鱼','肺鱼','hard'],
  ['赛加羚羊','叉角羚','hard'],
]
const V3_PLACES_ZH: V3Triple[] = [
  ['马尼拉','雅加达','easy'],
  ['华沙','布达佩斯','easy'],
  ['上海','北京','easy'],
  ['蒙特利尔','魁北克市','easy'],
  ['卢浮宫','艾尔米塔什','medium'],
  ['时代广场','皮卡迪利广场','medium'],
  ['香榭丽舍','第五大道','medium'],
  ['华尔街','涩谷','medium'],
  ['阿尔及尔','突尼斯','medium'],
  ['芝加哥','底特律','medium'],
  ['香格里拉','卡美洛','medium'],
  ['兰斯','阿维尼翁','medium'],
  ['伯尔尼','苏黎世','medium'],
  ['利物浦','曼彻斯特','medium'],
  ['瓦伦西亚','萨拉戈萨','medium'],
  ['安赫尔瀑布','维多利亚瀑布','medium'],
  ['堪察加','千岛群岛','hard'],
  ['拉萨','达兰萨拉','hard'],
  ['廷巴克图','加奥','hard'],
  ['巴库','第比利斯','hard'],
]
const V3_JOBS_ZH: V3Triple[] = [
  ['副主厨','线厨','easy'],
  ['女服务员','迎宾','easy'],
  ['送货员','卡车司机','easy'],
  ['木工','细木工','easy'],
  ['投资银行家','对冲基金经理','medium'],
  ['整形外科医生','皮肤科医生','medium'],
  ['心理治疗师','生活教练','medium'],
  ['机器学习工程师','数据科学家','medium'],
  ['社会工作者','个案经理','medium'],
  ['执业护士','助理医师','medium'],
  ['文字编辑','校对员','medium'],
  ['房产经纪人','按揭经纪人','medium'],
  ['财富经理','投资组合经理','medium'],
  ['生物学家','生态学家','medium'],
  ['室内设计师','舞台设计师','medium'],
  ['物理治疗师','整脊师','medium'],
  ['选角导演','星探','hard'],
  ['侍酒师','啤酒侍','hard'],
  ['金匠','银匠','hard'],
  ['皮草师','制帽师','hard'],
]
const V3_SPORTS_ZH: V3Triple[] = [
  ['网球','沙滩网球','easy'],
  ['躲避球','踢球','easy'],
  ['保龄球','烛瓶保龄','easy'],
  ['短跑','中距离跑','easy'],
  ['游艇竞赛','帆船','medium'],
  ['三项赛','障碍赛跳跃','medium'],
  ['瑜伽','普拉提','medium'],
  ['动感单车','高强度间歇训练','medium'],
  ['合气道','合气柔术','medium'],
  ['直线加速赛','纳斯卡','medium'],
  ['相扑','蒙古摔跤','medium'],
  ['跳伞','定点跳伞','medium'],
  ['魁地奇','极限飞盘','medium'],
  ['个人混合泳','接力','medium'],
  ['手球','网式篮球','medium'],
  ['轮滑德比','班迪球','medium'],
  ['泰拳古法','卡拉里帕亚图','hard'],
  ['爱尔兰式曲棍球','盖尔式足球','hard'],
  ['帕托','马上篮','hard'],
  ['硬地滚球','地掷球','hard'],
]

// RU
const V3_FOOD_RU: V3Triple[] = [
  ['Тимьян','Розмарин','easy'],
  ['Ямайский перец','Гвоздика','easy'],
  ['Пастрами','Грудинка','easy'],
  ['Рибай','Стриплойн','easy'],
  ['Тонкоцу','Сёю','medium'],
  ['Кацу','Шницель','medium'],
  ['Мескаль','Текила','medium'],
  ['Джин','Водка','medium'],
  ['Ройбуш','Чай масала','medium'],
  ['Портвейн','Херес','medium'],
  ['Джоллоф','Беначин','medium'],
  ['Карнитас','Аль пастор','medium'],
  ['Кугель','Латке','medium'],
  ['Хурма','Айва','medium'],
  ['Проволоне','Моцарелла','medium'],
  ['Стир-фрай','Сотирование','medium'],
  ['Пашот','Томление','hard'],
  ['Лакса','Ми горенг','hard'],
  ['Волован','Буше','hard'],
  ['Агар-агар','Пектин','hard'],
]
const V3_ANIMALS_RU: V3Triple[] = [
  ['Пони','Жеребец','easy'],
  ['Кузнечик','Саранча','easy'],
  ['Сорока','Сойка','easy'],
  ['Кардинал','Голубая сойка','easy'],
  ['Тунец','Рыба-меч','medium'],
  ['Мангуст','Сурикат','medium'],
  ['Морской огурец','Морской ёж','medium'],
  ['Коала','Валлаби','medium'],
  ['Снежный барс','Пума','medium'],
  ['Рысь','Рыжая рысь','medium'],
  ['Соловей','Ласточка','medium'],
  ['Альбатрос','Пеликан','medium'],
  ['Императорский пингвин','Королевский пингвин','medium'],
  ['Ленивец','Муравьед','medium'],
  ['Кукабара','Зимородок','medium'],
  ['Росомаха','Илька','medium'],
  ['Рыба-ёж','Иглобрюх','hard'],
  ['Лисья акула','Акула-мако','hard'],
  ['Латимерия','Двоякодышащая рыба','hard'],
  ['Сайгак','Вилорог','hard'],
]
const V3_PLACES_RU: V3Triple[] = [
  ['Манила','Джакарта','easy'],
  ['Варшава','Будапешт','easy'],
  ['Шанхай','Пекин','easy'],
  ['Монреаль','Квебек','easy'],
  ['Лувр','Эрмитаж','medium'],
  ['Таймс-сквер','Пикадилли','medium'],
  ['Елисейские поля','Пятая авеню','medium'],
  ['Уолл-стрит','Сибуя','medium'],
  ['Алжир','Тунис','medium'],
  ['Чикаго','Детройт','medium'],
  ['Шангри-Ла','Камелот','medium'],
  ['Реймс','Авиньон','medium'],
  ['Берн','Цюрих','medium'],
  ['Ливерпуль','Манчестер','medium'],
  ['Валенсия','Сарагоса','medium'],
  ['Водопад Анхель','Водопад Виктория','medium'],
  ['Камчатка','Курилы','hard'],
  ['Лхаса','Дхарамсала','hard'],
  ['Тимбукту','Гао','hard'],
  ['Баку','Тбилиси','hard'],
]
const V3_JOBS_RU: V3Triple[] = [
  ['Су-шеф','Линейный повар','easy'],
  ['Официантка','Хостес','easy'],
  ['Курьер','Дальнобойщик','easy'],
  ['Плотник','Столяр','easy'],
  ['Инвестбанкир','Управляющий хедж-фондом','medium'],
  ['Пластический хирург','Дерматолог','medium'],
  ['Психотерапевт','Лайф-коуч','medium'],
  ['Инженер ML','Дата-сайентист','medium'],
  ['Социальный работник','Менеджер по делам','medium'],
  ['Медсестра-практик','Ассистент врача','medium'],
  ['Литературный редактор','Корректор','medium'],
  ['Риелтор','Ипотечный брокер','medium'],
  ['Управляющий активами','Портфельный управляющий','medium'],
  ['Биолог','Эколог','medium'],
  ['Дизайнер интерьера','Художник-постановщик','medium'],
  ['Физиотерапевт','Хиропрактик','medium'],
  ['Кастинг-директор','Агент по талантам','hard'],
  ['Сомелье','Чичероне','hard'],
  ['Золотых дел мастер','Серебряных дел мастер','hard'],
  ['Меховщик','Шляпник','hard'],
]
const V3_SPORTS_RU: V3Triple[] = [
  ['Теннис','Пляжный теннис','easy'],
  ['Вышибалы','Кикбол','easy'],
  ['Боулинг','Кэндлпин','easy'],
  ['Спринт','Средние дистанции','easy'],
  ['Яхтинг','Парусный спорт','medium'],
  ['Троеборье','Конкур','medium'],
  ['Йога','Пилатес','medium'],
  ['Сайклинг','HIIT','medium'],
  ['Айкидо','Хапкидо','medium'],
  ['Драг-рейсинг','NASCAR','medium'],
  ['Сумо','Монгольская борьба','medium'],
  ['Парашютизм','Бейсджампинг','medium'],
  ['Квиддич','Алтимат-фризби','medium'],
  ['Комплексное плавание','Эстафета','medium'],
  ['Гандбол','Нетбол','medium'],
  ['Роллер-дерби','Хоккей с мячом','medium'],
  ['Муай Боран','Каларипаятту','hard'],
  ['Хёрлинг','Гэльский футбол','hard'],
  ['Пато','Хорсбол','hard'],
  ['Боччиа','Бочче','hard'],
]

// HI
const V3_FOOD_HI: V3Triple[] = [
  ['थाइम','रोज़मेरी','easy'],
  ['आलस्पाइस','लौंग','easy'],
  ['पास्त्रामी','ब्रिस्केट','easy'],
  ['रिबआई','सरलोइन','easy'],
  ['टोन्कोत्सू','शोयू','medium'],
  ['कात्सू','श्निट्ज़ेल','medium'],
  ['मेज़्कल','टकीला','medium'],
  ['जिन','वोदका','medium'],
  ['रूइबोस','मसाला चाय','medium'],
  ['पोर्ट','शेरी','medium'],
  ['जोलोफ चावल','बेनाचिन','medium'],
  ['कार्निताज़','आल पास्तोर','medium'],
  ['कुगेल','लातकी','medium'],
  ['तेंदू','श्रीफल','medium'],
  ['प्रोवोलोन','मोज़ारेला','medium'],
  ['स्टिर फ्राई','सॉते','medium'],
  ['पोचिंग','सिमरिंग','hard'],
  ['लक्सा','मी गोरेंग','hard'],
  ['वोल-ओ-वेंट','बूशे','hard'],
  ['अगर','पेक्टिन','hard'],
]
const V3_ANIMALS_HI: V3Triple[] = [
  ['टट्टू','घोड़ा','easy'],
  ['टिड्डा','प्रवासी टिड्डी','easy'],
  ['मैगपाई','जे','easy'],
  ['कार्डिनल','ब्लू जे','easy'],
  ['टूना','तलवार मछली','medium'],
  ['नेवला','मीरकैट','medium'],
  ['समुद्री ककड़ी','समुद्री अर्चिन','medium'],
  ['कोआला','वॉलबी','medium'],
  ['हिम तेंदुआ','पहाड़ी शेर','medium'],
  ['लिंक्स','बॉबकैट','medium'],
  ['बुलबुल','अबाबील','medium'],
  ['अल्बाट्रोस','पेलिकन','medium'],
  ['सम्राट पेंगुइन','राजा पेंगुइन','medium'],
  ['स्लॉथ','चींटीखोर','medium'],
  ['कूकाबुरा','किंगफिशर','medium'],
  ['वॉल्वरीन','फिशर','medium'],
  ['पफरफिश','ब्लोफिश','hard'],
  ['थ्रेशर शार्क','माको शार्क','hard'],
  ['सीलाकैंथ','फेफड़े वाली मछली','hard'],
  ['साइगा','प्रोंगहॉर्न','hard'],
]
const V3_PLACES_HI: V3Triple[] = [
  ['मनीला','जकार्ता','easy'],
  ['वारसॉ','बुडापेस्ट','easy'],
  ['शंघाई','बीजिंग','easy'],
  ['मॉन्ट्रियल','क्यूबेक सिटी','easy'],
  ['लूव्र','हर्मिटेज','medium'],
  ['टाइम्स स्क्वायर','पिकाडिली सर्कस','medium'],
  ['शांज़ेलीज़े','फिफ्थ एवेन्यू','medium'],
  ['वॉल स्ट्रीट','शिबुया','medium'],
  ['अल्जीयर्स','ट्यूनिस','medium'],
  ['शिकागो','डेट्रॉइट','medium'],
  ['शांगरी-ला','कैमलॉट','medium'],
  ['रेम्स','अविन्यों','medium'],
  ['बर्न','ज़्यूरिख','medium'],
  ['लिवरपूल','मैनचेस्टर','medium'],
  ['वालेंसिया','ज़ारागोज़ा','medium'],
  ['एंजेल जलप्रपात','विक्टोरिया जलप्रपात','medium'],
  ['कमचटका','कुरील द्वीप','hard'],
  ['ल्हासा','धर्मशाला','hard'],
  ['टिम्बकटू','गाओ','hard'],
  ['बाकू','त्बिलिसी','hard'],
]
const V3_JOBS_HI: V3Triple[] = [
  ['सूस शेफ','लाइन कुक','easy'],
  ['वेट्रेस','होस्टेस','easy'],
  ['डिलीवरी ड्राइवर','ट्रक ड्राइवर','easy'],
  ['बढ़ई','जॉइनर','easy'],
  ['निवेश बैंकर','हेज फंड प्रबंधक','medium'],
  ['प्लास्टिक सर्जन','त्वचा विशेषज्ञ','medium'],
  ['थेरेपिस्ट','लाइफ कोच','medium'],
  ['ML इंजीनियर','डेटा वैज्ञानिक','medium'],
  ['सामाजिक कार्यकर्ता','केस मैनेजर','medium'],
  ['नर्स प्रैक्टिशनर','फिजिशियन असिस्टेंट','medium'],
  ['कॉपी एडिटर','प्रूफरीडर','medium'],
  ['रियल एस्टेट एजेंट','गिरवी ब्रोकर','medium'],
  ['वेल्थ मैनेजर','पोर्टफोलियो मैनेजर','medium'],
  ['जीवविज्ञानी','पारिस्थितिकीविद्','medium'],
  ['इंटीरियर डिज़ाइनर','सेट डिज़ाइनर','medium'],
  ['फिजिकल थेरेपिस्ट','कायरोप्रैक्टर','medium'],
  ['कास्टिंग डायरेक्टर','टैलेंट एजेंट','hard'],
  ['सोमेलियर','सिसरोन','hard'],
  ['स्वर्णकार','रजतकार','hard'],
  ['फर्रीयर','हैटमेकर','hard'],
]
const V3_SPORTS_HI: V3Triple[] = [
  ['टेनिस','बीच टेनिस','easy'],
  ['डॉजबॉल','किकबॉल','easy'],
  ['बॉलिंग','कैंडलपिन','easy'],
  ['स्प्रिंट','मध्यम दूरी','easy'],
  ['यॉटिंग','नौकायन','medium'],
  ['इवेंटिंग','शो जंपिंग','medium'],
  ['योग','पिलेट्स','medium'],
  ['स्पिन क्लास','एचआईआईटी','medium'],
  ['ऐकिडो','हैपकिडो','medium'],
  ['ड्रैग रेसिंग','नास्कर','medium'],
  ['सूमो','मंगोलियन कुश्ती','medium'],
  ['स्काइडाइविंग','बेस जंपिंग','medium'],
  ['क्विडिच','अल्टीमेट फ्रिसबी','medium'],
  ['व्यक्तिगत मेडली','रिले','medium'],
  ['हैंडबॉल','नेटबॉल','medium'],
  ['रोलर डर्बी','बैंडी','medium'],
  ['मुय बोरान','कलरिपयट्टू','hard'],
  ['हर्लिंग','गेलिक फुटबॉल','hard'],
  ['पातो','हॉर्सबॉल','hard'],
  ['बॉचिया','बोक्से','hard'],
]

// ── Per-locale translatable pair tables ─────────────────────────────────────
const TR: Record<string, { food: V3Triple[]; animals: V3Triple[]; places: V3Triple[]; jobs: V3Triple[]; sports: V3Triple[] }> = {
  en: { food: V3_FOOD_EN, animals: V3_ANIMALS_EN, places: V3_PLACES_EN, jobs: V3_JOBS_EN, sports: V3_SPORTS_EN },
  fr: { food: V3_FOOD_FR, animals: V3_ANIMALS_FR, places: V3_PLACES_FR, jobs: V3_JOBS_FR, sports: V3_SPORTS_FR },
  es: { food: V3_FOOD_ES, animals: V3_ANIMALS_ES, places: V3_PLACES_ES, jobs: V3_JOBS_ES, sports: V3_SPORTS_ES },
  de: { food: V3_FOOD_DE, animals: V3_ANIMALS_DE, places: V3_PLACES_DE, jobs: V3_JOBS_DE, sports: V3_SPORTS_DE },
  ar: { food: V3_FOOD_AR, animals: V3_ANIMALS_AR, places: V3_PLACES_AR, jobs: V3_JOBS_AR, sports: V3_SPORTS_AR },
  it: { food: V3_FOOD_IT, animals: V3_ANIMALS_IT, places: V3_PLACES_IT, jobs: V3_JOBS_IT, sports: V3_SPORTS_IT },
  pt: { food: V3_FOOD_PT, animals: V3_ANIMALS_PT, places: V3_PLACES_PT, jobs: V3_JOBS_PT, sports: V3_SPORTS_PT },
  zh: { food: V3_FOOD_ZH, animals: V3_ANIMALS_ZH, places: V3_PLACES_ZH, jobs: V3_JOBS_ZH, sports: V3_SPORTS_ZH },
  ru: { food: V3_FOOD_RU, animals: V3_ANIMALS_RU, places: V3_PLACES_RU, jobs: V3_JOBS_RU, sports: V3_SPORTS_RU },
  hi: { food: V3_FOOD_HI, animals: V3_ANIMALS_HI, places: V3_PLACES_HI, jobs: V3_JOBS_HI, sports: V3_SPORTS_HI },
}

// ── Build per-locale V3 packs ───────────────────────────────────────────────
function buildV3ForLocale(loc: string): V3PairData[] {
  const tr = TR[loc]
  if (!tr) return []
  return [
    ...v3p('food',        loc, tr.food),
    ...v3p('animals',     loc, tr.animals),
    ...v3p('places',      loc, tr.places),
    ...v3p('jobs',        loc, tr.jobs),
    ...v3p('sports',      loc, tr.sports),
    ...v3p('mangas',      loc, V3_MANGAS),
    ...v3p('celebrities', loc, V3_CELEBRITIES),
    ...v3p('movies',      loc, V3_MOVIES),
    ...v3p('music',       loc, V3_MUSIC),
    ...v3p('history',     loc, V3_HISTORY),
    ...v3p('tech',        loc, V3_TECH),
  ]
}

export const ENGLISH_V3_PAIRS:    V3PairData[] = buildV3ForLocale('en')
export const FRENCH_V3_PAIRS:     V3PairData[] = buildV3ForLocale('fr')
export const SPANISH_V3_PAIRS:    V3PairData[] = buildV3ForLocale('es')
export const GERMAN_V3_PAIRS:     V3PairData[] = buildV3ForLocale('de')
export const ARABIC_V3_PAIRS:     V3PairData[] = buildV3ForLocale('ar')
export const ITALIAN_V3_PAIRS:    V3PairData[] = buildV3ForLocale('it')
export const PORTUGUESE_V3_PAIRS: V3PairData[] = buildV3ForLocale('pt')
export const CHINESE_V3_PAIRS:    V3PairData[] = buildV3ForLocale('zh')
export const RUSSIAN_V3_PAIRS:    V3PairData[] = buildV3ForLocale('ru')
export const INDIAN_V3_PAIRS:     V3PairData[] = buildV3ForLocale('hi')

export const V3_PAIRS_BY_LOCALE: Record<string, V3PairData[]> = {
  en: ENGLISH_V3_PAIRS,
  fr: FRENCH_V3_PAIRS,
  es: SPANISH_V3_PAIRS,
  de: GERMAN_V3_PAIRS,
  ar: ARABIC_V3_PAIRS,
  it: ITALIAN_V3_PAIRS,
  pt: PORTUGUESE_V3_PAIRS,
  zh: CHINESE_V3_PAIRS,
  ru: RUSSIAN_V3_PAIRS,
  hi: INDIAN_V3_PAIRS,
}

export const V3_PAIRS: V3PairData[] = V3_LOCALES.flatMap((loc) => buildV3ForLocale(loc))
