/**
 * V4 expansion — 20 additional tricky word pairs per category per locale.
 *
 * Follows the V3 convention: invariant pools (MANGAS, CELEBRITIES, MOVIES,
 * MUSIC, HISTORY, TECH) share pairs across all 10 locales; translatable
 * pools (FOOD, ANIMALS, PLACES, JOBS, SPORTS) are per-locale, index-aligned.
 *
 * Difficulty mix per pool: 4 easy, 12 medium, 4 hard.
 *
 * Imported by seed.ts (DB seeding) and scripts/generate-offline-words.mjs
 * (offline pass-and-play generation).
 */

type V4Triple = [string, string] | [string, string, string]

export type V4PairData = {
  wordA: string
  wordB: string
  category: string
  locale: string
}

const V4_LOCALES = ['en', 'fr', 'es', 'de', 'ar', 'it', 'pt', 'zh', 'ru', 'hi'] as const

const v4p = (cat: string, loc: string, ts: V4Triple[]): V4PairData[] =>
  ts.map(([a, b]) => ({ wordA: a, wordB: b, category: cat, locale: loc }))

// ── INVARIANT POOLS (same pairs across all 10 locales) ──────────────────────

const V4_MANGAS: V4Triple[] = [
  ['Pikachu', 'Eevee', 'easy'],
  ['Doraemon', 'Crayon Shin-chan', 'easy'],
  ['Yu-Gi-Oh', 'Beyblade', 'easy'],
  ['Sailor Moon', 'Madoka Magica', 'easy'],
  ['Iruka', 'Konohamaru', 'medium'],
  ['Pain', 'Obito', 'medium'],
  ['Mihawk', 'Crocodile', 'medium'],
  ['Marineford', 'Onigashima', 'medium'],
  ['Hokage', 'Mizukage', 'medium'],
  ['Cell', 'Buu', 'medium'],
  ['Yujiro', 'Baki', 'medium'],
  ['Stand', 'Hamon', 'medium'],
  ['Quincy', 'Arrancar', 'medium'],
  ['Vagabond', 'Vinland Saga', 'medium'],
  ['Toriko', 'Komatsu', 'medium'],
  ['Eustass Kid', 'Trafalgar Law', 'medium'],
  ['Domain Expansion', 'Reverse Cursed Technique', 'hard'],
  ['One for All', 'All for One', 'hard'],
  ['Conqueror Haki', 'Observation Haki', 'hard'],
  ['Madara', 'Hashirama', 'hard'],
]

const V4_CELEBRITIES: V4Triple[] = [
  ['Marshmello', 'Deadmau5', 'easy'],
  ['Karol G', 'Rosalia', 'easy'],
  ['Pep Guardiola', 'Jurgen Klopp', 'easy'],
  ['Wiz Khalifa', 'Tyga', 'easy'],
  ['Cole Sprouse', 'Dylan Sprouse', 'medium'],
  ['Heath Ledger', 'Jared Leto', 'medium'],
  ['Tyler Perry', 'Spike Lee', 'medium'],
  ['Adam Sandler', 'Kevin James', 'medium'],
  ['Matthew McConaughey', 'Woody Harrelson', 'medium'],
  ['Jennifer Aniston', 'Courteney Cox', 'medium'],
  ['Steph Curry', 'Klay Thompson', 'medium'],
  ['Joe Montana', 'Tom Brady', 'medium'],
  ['Hugh Grant', 'Colin Firth', 'medium'],
  ['Bill Gates', 'Steve Jobs', 'medium'],
  ['Mac Miller', 'Kid Cudi', 'medium'],
  ['Liam Gallagher', 'Noel Gallagher', 'medium'],
  ['Andrei Tarkovsky', 'Bela Tarr', 'hard'],
  ['Bjork', 'Kate Bush', 'hard'],
  ['Lars Ulrich', 'James Hetfield', 'hard'],
  ['Ennio Morricone', 'John Williams', 'hard'],
]

const V4_MOVIES: V4Triple[] = [
  ['Pirates of the Caribbean', 'Treasure Planet', 'easy'],
  ['Karate Kid', 'Cobra Kai', 'easy'],
  ['Tomb Raider', 'Indiana Jones', 'easy'],
  ['The Mask', 'Ace Ventura', 'easy'],
  ['Skyfall', 'Casino Royale', 'medium'],
  ['Catch Me If You Can', 'The Wolf of Wall Street', 'medium'],
  ['American Beauty', 'American History X', 'medium'],
  ['Slumdog Millionaire', 'The Lunchbox', 'medium'],
  ['Lost in Translation', 'Her', 'medium'],
  ['Cloud Atlas', 'The Fountain', 'medium'],
  ['Snatch', 'Lock Stock', 'medium'],
  ['Donnie Darko', 'Mulholland Drive', 'medium'],
  ['Mystic River', 'Million Dollar Baby', 'medium'],
  ['Gangs of New York', 'The Aviator', 'medium'],
  ['Stand By Me', 'The Goonies', 'medium'],
  ['Pans Labyrinth', 'The Devils Backbone', 'medium'],
  ['Eraserhead', 'Tetsuo', 'hard'],
  ['Persona', 'Cries and Whispers', 'hard'],
  ['Yi Yi', 'A Brighter Summer Day', 'hard'],
  ['Cinema Paradiso', 'The Postman', 'hard'],
]

const V4_MUSIC: V4Triple[] = [
  ['Beatles', 'Rolling Stones', 'easy'],
  ['Britney Spears', 'Christina Aguilera', 'easy'],
  ['Backstreet Boys', 'NSYNC', 'easy'],
  ['Maroon 5', 'OneRepublic', 'easy'],
  ['Imagine Dragons', 'Twenty One Pilots', 'medium'],
  ['Linkin Park', 'Limp Bizkit', 'medium'],
  ['The Chemical Brothers', 'The Prodigy', 'medium'],
  ['Drum Kit', 'Drum Machine', 'medium'],
  ['Cymbals', 'Hi-Hat', 'medium'],
  ['Microphone', 'Megaphone', 'medium'],
  ['Aerosmith', 'Guns N Roses', 'medium'],
  ['Pink Floyd', 'Led Zeppelin', 'medium'],
  ['Mahler', 'Wagner', 'medium'],
  ['Cumbia', 'Vallenato', 'medium'],
  ['Fado', 'Flamenco', 'medium'],
  ['Dembow', 'Reggaeton', 'medium'],
  ['Atonality', 'Serialism', 'hard'],
  ['Polyrhythm', 'Cross-Rhythm', 'hard'],
  ['Choro', 'Forro', 'hard'],
  ['Tabla', 'Mridangam', 'hard'],
]

const V4_HISTORY: V4Triple[] = [
  ['George Washington', 'Thomas Jefferson', 'easy'],
  ['Joan of Arc', 'Charles VII', 'easy'],
  ['Mark Antony', 'Brutus', 'easy'],
  ['Spartacus', 'Crassus', 'easy'],
  ['Stalin', 'Khrushchev', 'medium'],
  ['Mao Zedong', 'Deng Xiaoping', 'medium'],
  ['Akbar', 'Aurangzeb', 'medium'],
  ['Lorenzo de Medici', 'Cosimo de Medici', 'medium'],
  ['Battle of Stalingrad', 'Battle of Kursk', 'medium'],
  ['Battle of Midway', 'Battle of Coral Sea', 'medium'],
  ['Bay of Pigs', 'Cuban Missile Crisis', 'medium'],
  ['Tutankhamun', 'Ramses II', 'medium'],
  ['William the Conqueror', 'Harold Godwinson', 'medium'],
  ['Hammurabi', 'Nebuchadnezzar', 'medium'],
  ['Anne Frank', 'Oskar Schindler', 'medium'],
  ['Frederick the Great', 'Maria Theresa', 'medium'],
  ['Treaty of Brest-Litovsk', 'Treaty of Lausanne', 'hard'],
  ['Council of Nicaea', 'Council of Trent', 'hard'],
  ['Ashoka', 'Chandragupta Maurya', 'hard'],
  ['Hongwu', 'Yongle', 'hard'],
]

const V4_TECH: V4Triple[] = [
  ['Siri', 'Alexa', 'easy'],
  ['Excel', 'Google Sheets', 'easy'],
  ['Word', 'Google Docs', 'easy'],
  ['Photoshop', 'GIMP', 'easy'],
  ['Java', 'C++', 'medium'],
  ['JavaScript', 'TypeScript', 'medium'],
  ['Angular', 'Ember', 'medium'],
  ['MySQL', 'MariaDB', 'medium'],
  ['SQLite', 'Realm', 'medium'],
  ['Bash', 'Zsh', 'medium'],
  ['Vim', 'Emacs', 'medium'],
  ['VS Code', 'IntelliJ', 'medium'],
  ['Heroku', 'Vercel', 'medium'],
  ['Cloudflare', 'Akamai', 'medium'],
  ['Cassandra', 'DynamoDB', 'medium'],
  ['Datadog', 'New Relic', 'medium'],
  ['Erlang', 'Elixir', 'hard'],
  ['Haskell', 'OCaml', 'hard'],
  ['gRPC', 'Thrift', 'hard'],
  ['Nix', 'Guix', 'hard'],
]

// ── TRANSLATABLE POOLS (per-locale, index-aligned) ──────────────────────────

// EN
const V4_FOOD_EN: V4Triple[] = [
  ['Honey', 'Maple Syrup', 'easy'],
  ['Lemon', 'Lime', 'easy'],
  ['Olive', 'Avocado', 'easy'],
  ['Sandwich', 'Wrap', 'easy'],
  ['Pad Thai', 'Drunken Noodles', 'medium'],
  ['Mac and Cheese', 'Cacio e Pepe', 'medium'],
  ['Caesar Salad', 'Cobb Salad', 'medium'],
  ['Hot Pot', 'Shabu Shabu', 'medium'],
  ['Sake', 'Soju', 'medium'],
  ['Bourbon', 'Rye Whiskey', 'medium'],
  ['Negroni', 'Manhattan', 'medium'],
  ['Mole', 'Adobo', 'medium'],
  ['Tom Yum', 'Tom Kha', 'medium'],
  ['Roasting', 'Baking', 'medium'],
  ['Saffron', 'Turmeric', 'medium'],
  ['Almond', 'Hazelnut', 'medium'],
  ['Sous Vide', 'Confit', 'hard'],
  ['Beurre Blanc', 'Hollandaise', 'hard'],
  ['Cassoulet', 'Choucroute', 'hard'],
  ['Bouillabaisse', 'Buridda', 'hard'],
]
const V4_ANIMALS_EN: V4Triple[] = [
  ['Cow', 'Bull', 'easy'],
  ['Pig', 'Boar', 'easy'],
  ['Goat', 'Ram', 'easy'],
  ['Husky', 'Malamute', 'easy'],
  ['Stoat', 'Ermine', 'medium'],
  ['Cuttlefish', 'Nautilus', 'medium'],
  ['Coral', 'Sea Anemone', 'medium'],
  ['Krill', 'Plankton', 'medium'],
  ['Quokka', 'Bandicoot', 'medium'],
  ['Dingo', 'Tasmanian Devil', 'medium'],
  ['Kangaroo', 'Wallaroo', 'medium'],
  ['Kiwi', 'Cassowary', 'medium'],
  ['Mantis', 'Stick Insect', 'medium'],
  ['Cicada', 'Katydid', 'medium'],
  ['Mamba', 'Krait', 'medium'],
  ['Liger', 'Tigon', 'medium'],
  ['Aye-aye', 'Tarsier', 'hard'],
  ['Tuatara', 'Komodo Dragon', 'hard'],
  ['Coati', 'Kinkajou', 'hard'],
  ['Bilby', 'Numbat', 'hard'],
]
const V4_PLACES_EN: V4Triple[] = [
  ['Berlin', 'Munich', 'easy'],
  ['Madrid', 'Lisbon', 'easy'],
  ['Rio de Janeiro', 'Sao Paulo', 'easy'],
  ['Bangkok', 'Ho Chi Minh City', 'easy'],
  ['Helsinki', 'Tallinn', 'medium'],
  ['Bucharest', 'Sofia', 'medium'],
  ['Riyadh', 'Doha', 'medium'],
  ['Tehran', 'Baghdad', 'medium'],
  ['Tashkent', 'Almaty', 'medium'],
  ['Buenos Aires', 'Montevideo', 'medium'],
  ['Acapulco', 'Tulum', 'medium'],
  ['Marseille', 'Genoa', 'medium'],
  ['Black Forest', 'Bavarian Alps', 'medium'],
  ['Pisa', 'Florence', 'medium'],
  ['Vatican City', 'Monaco', 'medium'],
  ['Windsor Castle', 'Edinburgh Castle', 'medium'],
  ['Ulan Bator', 'Vladivostok', 'hard'],
  ['Banjul', 'Conakry', 'hard'],
  ['Suva', 'Apia', 'hard'],
  ['Paramaribo', 'Georgetown', 'hard'],
]
const V4_JOBS_EN: V4Triple[] = [
  ['Driver', 'Chauffeur', 'easy'],
  ['Cashier', 'Teller', 'easy'],
  ['Cleaner', 'Janitor', 'easy'],
  ['Soldier', 'Marine', 'easy'],
  ['Nephrologist', 'Urologist', 'medium'],
  ['Endocrinologist', 'Hematologist', 'medium'],
  ['Civil Engineer', 'Structural Engineer', 'medium'],
  ['DevOps Engineer', 'Site Reliability Engineer', 'medium'],
  ['Recruiter', 'Headhunter', 'medium'],
  ['Tax Advisor', 'Financial Planner', 'medium'],
  ['Conservator', 'Restorer', 'medium'],
  ['Anchor', 'Correspondent', 'medium'],
  ['Author', 'Ghostwriter', 'medium'],
  ['Travel Agent', 'Tour Guide', 'medium'],
  ['Foley Artist', 'Sound Designer', 'medium'],
  ['Brewmaster', 'Distiller', 'medium'],
  ['Apothecary', 'Herbalist', 'hard'],
  ['Cooper', 'Cobbler', 'hard'],
  ['Calligrapher', 'Typesetter', 'hard'],
  ['Auctioneer', 'Appraiser', 'hard'],
]
const V4_SPORTS_EN: V4Triple[] = [
  ['Frisbee', 'Boomerang', 'easy'],
  ['Skating', 'Roller Skating', 'easy'],
  ['Stickball', 'Kickball', 'easy'],
  ['Volleyball', 'Beach Volleyball', 'easy'],
  ['Beach Soccer', 'Indoor Soccer', 'medium'],
  ['Snorkeling', 'Scuba Diving', 'medium'],
  ['Spearfishing', 'Free Diving', 'medium'],
  ['Sandboarding', 'Sledding', 'medium'],
  ['Trikke', 'Segway', 'medium'],
  ['Equestrian Vaulting', 'Dressage', 'medium'],
  ['Speed Climbing', 'Lead Climbing', 'medium'],
  ['Synchronized Swimming', 'Artistic Swimming', 'medium'],
  ['Aerial Silks', 'Trapeze', 'medium'],
  ['Water Skiing', 'Wakeboarding', 'medium'],
  ['Slacklining', 'Tightrope Walking', 'medium'],
  ['Tug of War', 'Caber Toss', 'medium'],
  ['Pelota Vasca', 'Frontenis', 'hard'],
  ['Buzkashi', 'Kok-Boru', 'hard'],
  ['Calcio Storico', 'Cuju', 'hard'],
  ['Glima', 'Schwingen', 'hard'],
]

// FR
const V4_FOOD_FR: V4Triple[] = [
  ['Miel', 'Sirop d erable', 'easy'],
  ['Citron', 'Citron vert', 'easy'],
  ['Olive', 'Avocat', 'easy'],
  ['Sandwich', 'Wrap', 'easy'],
  ['Pad Thai', 'Nouilles ivres', 'medium'],
  ['Mac and Cheese', 'Cacio e Pepe', 'medium'],
  ['Salade Cesar', 'Salade Cobb', 'medium'],
  ['Hot Pot', 'Shabu Shabu', 'medium'],
  ['Sake', 'Soju', 'medium'],
  ['Bourbon', 'Whisky de seigle', 'medium'],
  ['Negroni', 'Manhattan', 'medium'],
  ['Mole', 'Adobo', 'medium'],
  ['Tom Yum', 'Tom Kha', 'medium'],
  ['Rotir', 'Cuire au four', 'medium'],
  ['Safran', 'Curcuma', 'medium'],
  ['Amande', 'Noisette', 'medium'],
  ['Sous vide', 'Confit', 'hard'],
  ['Beurre blanc', 'Hollandaise', 'hard'],
  ['Cassoulet', 'Choucroute', 'hard'],
  ['Bouillabaisse', 'Buridda', 'hard'],
]
const V4_ANIMALS_FR: V4Triple[] = [
  ['Vache', 'Taureau', 'easy'],
  ['Cochon', 'Sanglier', 'easy'],
  ['Chevre', 'Belier', 'easy'],
  ['Husky', 'Malamute', 'easy'],
  ['Hermine', 'Belette d hiver', 'medium'],
  ['Seiche', 'Nautile', 'medium'],
  ['Corail', 'Anemone de mer', 'medium'],
  ['Krill', 'Plancton', 'medium'],
  ['Quokka', 'Bandicoot', 'medium'],
  ['Dingo', 'Diable de Tasmanie', 'medium'],
  ['Kangourou', 'Wallaroo', 'medium'],
  ['Kiwi', 'Casoar', 'medium'],
  ['Mante religieuse', 'Phasme', 'medium'],
  ['Cigale', 'Sauterelle verte', 'medium'],
  ['Mamba', 'Bongare', 'medium'],
  ['Ligre', 'Tigron', 'medium'],
  ['Aye-aye', 'Tarsier', 'hard'],
  ['Tuatara', 'Dragon de Komodo', 'hard'],
  ['Coati', 'Kinkajou', 'hard'],
  ['Bilby', 'Numbat', 'hard'],
]
const V4_PLACES_FR: V4Triple[] = [
  ['Berlin', 'Munich', 'easy'],
  ['Madrid', 'Lisbonne', 'easy'],
  ['Rio de Janeiro', 'Sao Paulo', 'easy'],
  ['Bangkok', 'Ho Chi Minh-Ville', 'easy'],
  ['Helsinki', 'Tallinn', 'medium'],
  ['Bucarest', 'Sofia', 'medium'],
  ['Riyad', 'Doha', 'medium'],
  ['Teheran', 'Bagdad', 'medium'],
  ['Tachkent', 'Almaty', 'medium'],
  ['Buenos Aires', 'Montevideo', 'medium'],
  ['Acapulco', 'Tulum', 'medium'],
  ['Marseille', 'Genes', 'medium'],
  ['Foret-Noire', 'Alpes bavaroises', 'medium'],
  ['Pise', 'Florence', 'medium'],
  ['Cite du Vatican', 'Monaco', 'medium'],
  ['Chateau de Windsor', 'Chateau d Edimbourg', 'medium'],
  ['Oulan-Bator', 'Vladivostok', 'hard'],
  ['Banjul', 'Conakry', 'hard'],
  ['Suva', 'Apia', 'hard'],
  ['Paramaribo', 'Georgetown', 'hard'],
]
const V4_JOBS_FR: V4Triple[] = [
  ['Conducteur', 'Chauffeur', 'easy'],
  ['Caissier', 'Guichetier', 'easy'],
  ['Agent d entretien', 'Concierge', 'easy'],
  ['Soldat', 'Marine', 'easy'],
  ['Nephrologue', 'Urologue', 'medium'],
  ['Endocrinologue', 'Hematologue', 'medium'],
  ['Ingenieur civil', 'Ingenieur en structures', 'medium'],
  ['Ingenieur DevOps', 'Ingenieur SRE', 'medium'],
  ['Recruteur', 'Chasseur de tetes', 'medium'],
  ['Conseiller fiscal', 'Planificateur financier', 'medium'],
  ['Conservateur', 'Restaurateur', 'medium'],
  ['Presentateur', 'Correspondant', 'medium'],
  ['Auteur', 'Negre litteraire', 'medium'],
  ['Agent de voyages', 'Guide touristique', 'medium'],
  ['Bruiteur', 'Concepteur sonore', 'medium'],
  ['Maitre brasseur', 'Distillateur', 'medium'],
  ['Apothicaire', 'Herboriste', 'hard'],
  ['Tonnelier', 'Cordonnier', 'hard'],
  ['Calligraphe', 'Typographe', 'hard'],
  ['Commissaire-priseur', 'Estimateur', 'hard'],
]
const V4_SPORTS_FR: V4Triple[] = [
  ['Frisbee', 'Boomerang', 'easy'],
  ['Patinage', 'Roller', 'easy'],
  ['Stickball', 'Kickball', 'easy'],
  ['Volley-ball', 'Beach-volley', 'easy'],
  ['Beach soccer', 'Soccer en salle', 'medium'],
  ['Plongee libre', 'Plongee sous-marine', 'medium'],
  ['Peche au harpon', 'Apnee', 'medium'],
  ['Sandboard', 'Luge', 'medium'],
  ['Trikke', 'Segway', 'medium'],
  ['Voltige equestre', 'Dressage', 'medium'],
  ['Escalade de vitesse', 'Escalade en tete', 'medium'],
  ['Natation synchronisee', 'Natation artistique', 'medium'],
  ['Tissu aerien', 'Trapeze', 'medium'],
  ['Ski nautique', 'Wakeboard', 'medium'],
  ['Slackline', 'Funambulisme', 'medium'],
  ['Tir a la corde', 'Lancer du tronc', 'medium'],
  ['Pelote basque', 'Frontenis', 'hard'],
  ['Bouzkachi', 'Kok-Boru', 'hard'],
  ['Calcio Storico', 'Cuju', 'hard'],
  ['Glima', 'Schwingen', 'hard'],
]

// ES
const V4_FOOD_ES: V4Triple[] = [
  ['Miel', 'Sirope de arce', 'easy'],
  ['Limon', 'Lima', 'easy'],
  ['Aceituna', 'Aguacate', 'easy'],
  ['Sandwich', 'Wrap', 'easy'],
  ['Pad Thai', 'Fideos borrachos', 'medium'],
  ['Mac and Cheese', 'Cacio e Pepe', 'medium'],
  ['Ensalada Cesar', 'Ensalada Cobb', 'medium'],
  ['Olla caliente', 'Shabu Shabu', 'medium'],
  ['Sake', 'Soju', 'medium'],
  ['Bourbon', 'Whisky de centeno', 'medium'],
  ['Negroni', 'Manhattan', 'medium'],
  ['Mole', 'Adobo', 'medium'],
  ['Tom Yum', 'Tom Kha', 'medium'],
  ['Asar', 'Hornear', 'medium'],
  ['Azafran', 'Curcuma', 'medium'],
  ['Almendra', 'Avellana', 'medium'],
  ['Sous vide', 'Confit', 'hard'],
  ['Beurre Blanc', 'Holandesa', 'hard'],
  ['Cassoulet', 'Choucroute', 'hard'],
  ['Bullabesa', 'Buridda', 'hard'],
]
const V4_ANIMALS_ES: V4Triple[] = [
  ['Vaca', 'Toro', 'easy'],
  ['Cerdo', 'Jabali', 'easy'],
  ['Cabra', 'Carnero', 'easy'],
  ['Husky', 'Malamute', 'easy'],
  ['Armino', 'Comadreja invernal', 'medium'],
  ['Sepia', 'Nautilo', 'medium'],
  ['Coral', 'Anemona de mar', 'medium'],
  ['Kril', 'Plancton', 'medium'],
  ['Quokka', 'Bandicut', 'medium'],
  ['Dingo', 'Demonio de Tasmania', 'medium'],
  ['Canguro', 'Wallaroo', 'medium'],
  ['Kiwi', 'Casuario', 'medium'],
  ['Mantis religiosa', 'Insecto palo', 'medium'],
  ['Cigarra', 'Saltamontes verde', 'medium'],
  ['Mamba', 'Krait', 'medium'],
  ['Ligre', 'Tigon', 'medium'],
  ['Aye-aye', 'Tarsero', 'hard'],
  ['Tuatara', 'Dragon de Komodo', 'hard'],
  ['Coati', 'Kinkajou', 'hard'],
  ['Bilby', 'Numbat', 'hard'],
]
const V4_PLACES_ES: V4Triple[] = [
  ['Berlin', 'Munich', 'easy'],
  ['Madrid', 'Lisboa', 'easy'],
  ['Rio de Janeiro', 'Sao Paulo', 'easy'],
  ['Bangkok', 'Ho Chi Minh', 'easy'],
  ['Helsinki', 'Tallin', 'medium'],
  ['Bucarest', 'Sofia', 'medium'],
  ['Riad', 'Doha', 'medium'],
  ['Teheran', 'Bagdad', 'medium'],
  ['Tashkent', 'Almaty', 'medium'],
  ['Buenos Aires', 'Montevideo', 'medium'],
  ['Acapulco', 'Tulum', 'medium'],
  ['Marsella', 'Genova', 'medium'],
  ['Selva Negra', 'Alpes Bavaros', 'medium'],
  ['Pisa', 'Florencia', 'medium'],
  ['Ciudad del Vaticano', 'Monaco', 'medium'],
  ['Castillo de Windsor', 'Castillo de Edimburgo', 'medium'],
  ['Ulan Bator', 'Vladivostok', 'hard'],
  ['Banjul', 'Conakry', 'hard'],
  ['Suva', 'Apia', 'hard'],
  ['Paramaribo', 'Georgetown', 'hard'],
]
const V4_JOBS_ES: V4Triple[] = [
  ['Conductor', 'Chofer', 'easy'],
  ['Cajero', 'Cajero bancario', 'easy'],
  ['Limpiador', 'Conserje', 'easy'],
  ['Soldado', 'Marine', 'easy'],
  ['Nefrologo', 'Urologo', 'medium'],
  ['Endocrinologo', 'Hematologo', 'medium'],
  ['Ingeniero civil', 'Ingeniero estructural', 'medium'],
  ['Ingeniero DevOps', 'Ingeniero SRE', 'medium'],
  ['Reclutador', 'Cazatalentos', 'medium'],
  ['Asesor fiscal', 'Planificador financiero', 'medium'],
  ['Conservador', 'Restaurador', 'medium'],
  ['Presentador', 'Corresponsal', 'medium'],
  ['Autor', 'Escritor fantasma', 'medium'],
  ['Agente de viajes', 'Guia turistico', 'medium'],
  ['Especialista en foley', 'Disenador de sonido', 'medium'],
  ['Maestro cervecero', 'Destilador', 'medium'],
  ['Boticario', 'Herbolario', 'hard'],
  ['Tonelero', 'Zapatero', 'hard'],
  ['Caligrafo', 'Tipografo', 'hard'],
  ['Subastador', 'Tasador', 'hard'],
]
const V4_SPORTS_ES: V4Triple[] = [
  ['Frisbee', 'Bumeran', 'easy'],
  ['Patinaje', 'Patinaje sobre ruedas', 'easy'],
  ['Stickball', 'Kickball', 'easy'],
  ['Voleibol', 'Voley playa', 'easy'],
  ['Futbol playa', 'Futbol sala', 'medium'],
  ['Snorkel', 'Buceo', 'medium'],
  ['Pesca submarina', 'Apnea', 'medium'],
  ['Sandboard', 'Trineo', 'medium'],
  ['Trikke', 'Segway', 'medium'],
  ['Volteo ecuestre', 'Doma clasica', 'medium'],
  ['Escalada de velocidad', 'Escalada en cabeza', 'medium'],
  ['Natacion sincronizada', 'Natacion artistica', 'medium'],
  ['Telas aereas', 'Trapecio', 'medium'],
  ['Esqui acuatico', 'Wakeboard', 'medium'],
  ['Slackline', 'Funambulismo', 'medium'],
  ['Tira y afloja', 'Lanzamiento de tronco', 'medium'],
  ['Pelota vasca', 'Frontenis', 'hard'],
  ['Buzkashi', 'Kok-Boru', 'hard'],
  ['Calcio Storico', 'Cuju', 'hard'],
  ['Glima', 'Schwingen', 'hard'],
]

// DE
const V4_FOOD_DE: V4Triple[] = [
  ['Honig', 'Ahornsirup', 'easy'],
  ['Zitrone', 'Limette', 'easy'],
  ['Olive', 'Avocado', 'easy'],
  ['Sandwich', 'Wrap', 'easy'],
  ['Pad Thai', 'Drunken Noodles', 'medium'],
  ['Mac and Cheese', 'Cacio e Pepe', 'medium'],
  ['Caesar Salat', 'Cobb Salat', 'medium'],
  ['Hot Pot', 'Shabu Shabu', 'medium'],
  ['Sake', 'Soju', 'medium'],
  ['Bourbon', 'Roggenwhisky', 'medium'],
  ['Negroni', 'Manhattan', 'medium'],
  ['Mole', 'Adobo', 'medium'],
  ['Tom Yum', 'Tom Kha', 'medium'],
  ['Braten', 'Backen', 'medium'],
  ['Safran', 'Kurkuma', 'medium'],
  ['Mandel', 'Haselnuss', 'medium'],
  ['Sous Vide', 'Confit', 'hard'],
  ['Beurre Blanc', 'Hollandaise', 'hard'],
  ['Cassoulet', 'Choucroute', 'hard'],
  ['Bouillabaisse', 'Buridda', 'hard'],
]
const V4_ANIMALS_DE: V4Triple[] = [
  ['Kuh', 'Stier', 'easy'],
  ['Schwein', 'Wildschwein', 'easy'],
  ['Ziege', 'Widder', 'easy'],
  ['Husky', 'Malamute', 'easy'],
  ['Hermelin', 'Mauswiesel', 'medium'],
  ['Tintenfisch', 'Nautilus', 'medium'],
  ['Koralle', 'Seeanemone', 'medium'],
  ['Krill', 'Plankton', 'medium'],
  ['Quokka', 'Beuteldachs', 'medium'],
  ['Dingo', 'Tasmanischer Teufel', 'medium'],
  ['Kanguru', 'Wallaroo', 'medium'],
  ['Kiwi', 'Kasuar', 'medium'],
  ['Gottesanbeterin', 'Stabschrecke', 'medium'],
  ['Zikade', 'Laubheuschrecke', 'medium'],
  ['Mamba', 'Krait', 'medium'],
  ['Liger', 'Tigon', 'medium'],
  ['Fingertier', 'Koboldmaki', 'hard'],
  ['Bruckenechse', 'Komodowaran', 'hard'],
  ['Nasenbar', 'Wickelbar', 'hard'],
  ['Bilby', 'Numbat', 'hard'],
]
const V4_PLACES_DE: V4Triple[] = [
  ['Berlin', 'Munchen', 'easy'],
  ['Madrid', 'Lissabon', 'easy'],
  ['Rio de Janeiro', 'Sao Paulo', 'easy'],
  ['Bangkok', 'Ho-Chi-Minh-Stadt', 'easy'],
  ['Helsinki', 'Tallinn', 'medium'],
  ['Bukarest', 'Sofia', 'medium'],
  ['Riad', 'Doha', 'medium'],
  ['Teheran', 'Bagdad', 'medium'],
  ['Taschkent', 'Almaty', 'medium'],
  ['Buenos Aires', 'Montevideo', 'medium'],
  ['Acapulco', 'Tulum', 'medium'],
  ['Marseille', 'Genua', 'medium'],
  ['Schwarzwald', 'Bayerische Alpen', 'medium'],
  ['Pisa', 'Florenz', 'medium'],
  ['Vatikanstadt', 'Monaco', 'medium'],
  ['Schloss Windsor', 'Edinburgh Castle', 'medium'],
  ['Ulan-Bator', 'Wladiwostok', 'hard'],
  ['Banjul', 'Conakry', 'hard'],
  ['Suva', 'Apia', 'hard'],
  ['Paramaribo', 'Georgetown', 'hard'],
]
const V4_JOBS_DE: V4Triple[] = [
  ['Fahrer', 'Chauffeur', 'easy'],
  ['Kassierer', 'Bankschalter', 'easy'],
  ['Reinigungskraft', 'Hausmeister', 'easy'],
  ['Soldat', 'Marine', 'easy'],
  ['Nephrologe', 'Urologe', 'medium'],
  ['Endokrinologe', 'Hamatologe', 'medium'],
  ['Bauingenieur', 'Tragwerksplaner', 'medium'],
  ['DevOps-Ingenieur', 'SRE', 'medium'],
  ['Personalvermittler', 'Headhunter', 'medium'],
  ['Steuerberater', 'Finanzplaner', 'medium'],
  ['Konservator', 'Restaurator', 'medium'],
  ['Moderator', 'Korrespondent', 'medium'],
  ['Autor', 'Ghostwriter', 'medium'],
  ['Reisevermittler', 'Reisefuhrer', 'medium'],
  ['Gerauschemacher', 'Sounddesigner', 'medium'],
  ['Braumeister', 'Brennmeister', 'medium'],
  ['Apotheker', 'Krauterkundiger', 'hard'],
  ['Bottcher', 'Schuster', 'hard'],
  ['Kalligraph', 'Setzer', 'hard'],
  ['Auktionator', 'Gutachter', 'hard'],
]
const V4_SPORTS_DE: V4Triple[] = [
  ['Frisbee', 'Bumerang', 'easy'],
  ['Eislaufen', 'Rollschuhlaufen', 'easy'],
  ['Stickball', 'Kickball', 'easy'],
  ['Volleyball', 'Beachvolleyball', 'easy'],
  ['Beachsoccer', 'Hallenfussball', 'medium'],
  ['Schnorcheln', 'Tauchen', 'medium'],
  ['Speerfischen', 'Apnoetauchen', 'medium'],
  ['Sandboarden', 'Schlitten', 'medium'],
  ['Trikke', 'Segway', 'medium'],
  ['Voltigieren', 'Dressur', 'medium'],
  ['Speedklettern', 'Vorstiegsklettern', 'medium'],
  ['Synchronschwimmen', 'Kunstschwimmen', 'medium'],
  ['Vertikaltuch', 'Trapez', 'medium'],
  ['Wasserski', 'Wakeboarden', 'medium'],
  ['Slackline', 'Seiltanzen', 'medium'],
  ['Tauziehen', 'Baumstammwerfen', 'medium'],
  ['Baskische Pelota', 'Frontenis', 'hard'],
  ['Buzkashi', 'Kok-Boru', 'hard'],
  ['Calcio Storico', 'Cuju', 'hard'],
  ['Glima', 'Schwingen', 'hard'],
]

// AR
const V4_FOOD_AR: V4Triple[] = [
  ['عسل','شراب القيقب','easy'],
  ['ليمون','ليمون أخضر','easy'],
  ['زيتون','أفوكادو','easy'],
  ['ساندويتش','لفافة','easy'],
  ['باد تاي','نودلز سكرانة','medium'],
  ['ماك آند تشيز','كاتشيو إي بيبي','medium'],
  ['سلطة سيزر','سلطة كوب','medium'],
  ['هوت بوت','شابو شابو','medium'],
  ['ساكي','سوجو','medium'],
  ['بوربون','ويسكي الجاودار','medium'],
  ['نيغروني','مانهاتن','medium'],
  ['موليه','أدوبو','medium'],
  ['توم يام','توم خا','medium'],
  ['شواء','خبز','medium'],
  ['زعفران','كركم','medium'],
  ['لوز','بندق','medium'],
  ['سو فيد','كونفي','hard'],
  ['بور بلان','هولندي','hard'],
  ['كاسوليه','شوكروت','hard'],
  ['بويابيس','بوريدا','hard'],
]
const V4_ANIMALS_AR: V4Triple[] = [
  ['بقرة','ثور','easy'],
  ['خنزير','خنزير بري','easy'],
  ['ماعز','كبش','easy'],
  ['هاسكي','مالاميوت','easy'],
  ['قاقم','عرسة شتوية','medium'],
  ['حبار','نوتيلوس','medium'],
  ['مرجان','شقائق البحر','medium'],
  ['كريل','عوالق','medium'],
  ['كوكا','بانديكوت','medium'],
  ['الكلب البري','شيطان تسمانيا','medium'],
  ['كنغر','والارو','medium'],
  ['كيوي','الشبنم','medium'],
  ['فرس النبي','حشرة العصا','medium'],
  ['زيز','جرادة الأشجار','medium'],
  ['مامبا','كرايت','medium'],
  ['ليجر','تيغون','medium'],
  ['آي آي','ترسير','hard'],
  ['تواتارا','تنين الكومودو','hard'],
  ['كواتي','كنكاجو','hard'],
  ['بيلبي','نمبات','hard'],
]
const V4_PLACES_AR: V4Triple[] = [
  ['برلين','ميونخ','easy'],
  ['مدريد','لشبونة','easy'],
  ['ريو دي جانيرو','ساو باولو','easy'],
  ['بانكوك','هو تشي منه','easy'],
  ['هلسنكي','تالين','medium'],
  ['بوخارست','صوفيا','medium'],
  ['الرياض','الدوحة','medium'],
  ['طهران','بغداد','medium'],
  ['طشقند','ألماتي','medium'],
  ['بوينس آيرس','مونتيفيديو','medium'],
  ['أكابولكو','تولوم','medium'],
  ['مرسيليا','جنوة','medium'],
  ['الغابة السوداء','جبال الألب البافارية','medium'],
  ['بيزا','فلورنسا','medium'],
  ['مدينة الفاتيكان','موناكو','medium'],
  ['قلعة وندسور','قلعة إدنبرة','medium'],
  ['أولان باتور','فلاديفوستوك','hard'],
  ['بانجول','كوناكري','hard'],
  ['سوفا','أبيا','hard'],
  ['باراماريبو','جورجتاون','hard'],
]
const V4_JOBS_AR: V4Triple[] = [
  ['سائق','سائق خاص','easy'],
  ['أمين صندوق','صراف بنك','easy'],
  ['عامل تنظيف','حارس مبنى','easy'],
  ['جندي','مارينز','easy'],
  ['طبيب كلى','طبيب مسالك بولية','medium'],
  ['طبيب غدد','طبيب دم','medium'],
  ['مهندس مدني','مهندس إنشاءات','medium'],
  ['مهندس DevOps','مهندس موثوقية','medium'],
  ['موظف توظيف','صائد المواهب','medium'],
  ['مستشار ضرائب','مخطط مالي','medium'],
  ['أمين متحف','مرمم','medium'],
  ['مذيع','مراسل','medium'],
  ['مؤلف','كاتب شبح','medium'],
  ['وكيل سفر','مرشد سياحي','medium'],
  ['فنان مؤثرات صوتية','مصمم صوت','medium'],
  ['صانع جعة','مقطر','medium'],
  ['عطار','معالج بالأعشاب','hard'],
  ['صانع براميل','إسكافي','hard'],
  ['خطاط','منضد طباعة','hard'],
  ['مزايد','مقيم','hard'],
]
const V4_SPORTS_AR: V4Triple[] = [
  ['فريسبي','بوميرانغ','easy'],
  ['تزلج','تزلج بالعجلات','easy'],
  ['كرة العصا','كرة الركل','easy'],
  ['كرة الطائرة','كرة طائرة شاطئية','easy'],
  ['كرة قدم شاطئية','كرة قدم داخلية','medium'],
  ['غطس بأنبوب','غوص','medium'],
  ['صيد بالحربة','غوص حر','medium'],
  ['تزلج رمال','تزلج زلاجة','medium'],
  ['تريك','سيغواي','medium'],
  ['بهلوانية الخيل','ترويض الخيل','medium'],
  ['تسلق سرعة','تسلق رئيسي','medium'],
  ['سباحة منسقة','سباحة فنية','medium'],
  ['أقمشة هوائية','تراپيز','medium'],
  ['تزلج على الماء','وكبورد','medium'],
  ['سلاكلاين','مشي على الحبل','medium'],
  ['شد الحبل','رمي الجذع','medium'],
  ['كرة الباسك','فرونتنيس','hard'],
  ['بوزكاشي','كوك بورو','hard'],
  ['كالتشو ستوريكو','كوجو','hard'],
  ['غليما','شفنغن','hard'],
]

// IT
const V4_FOOD_IT: V4Triple[] = [
  ['Miele', 'Sciroppo d acero', 'easy'],
  ['Limone', 'Lime', 'easy'],
  ['Oliva', 'Avocado', 'easy'],
  ['Sandwich', 'Wrap', 'easy'],
  ['Pad Thai', 'Drunken Noodles', 'medium'],
  ['Mac and Cheese', 'Cacio e Pepe', 'medium'],
  ['Insalata Cesare', 'Insalata Cobb', 'medium'],
  ['Hot Pot', 'Shabu Shabu', 'medium'],
  ['Sake', 'Soju', 'medium'],
  ['Bourbon', 'Whisky di segale', 'medium'],
  ['Negroni', 'Manhattan', 'medium'],
  ['Mole', 'Adobo', 'medium'],
  ['Tom Yum', 'Tom Kha', 'medium'],
  ['Arrostire', 'Cuocere al forno', 'medium'],
  ['Zafferano', 'Curcuma', 'medium'],
  ['Mandorla', 'Nocciola', 'medium'],
  ['Sous Vide', 'Confit', 'hard'],
  ['Beurre Blanc', 'Olandese', 'hard'],
  ['Cassoulet', 'Choucroute', 'hard'],
  ['Bouillabaisse', 'Buridda', 'hard'],
]
const V4_ANIMALS_IT: V4Triple[] = [
  ['Mucca', 'Toro', 'easy'],
  ['Maiale', 'Cinghiale', 'easy'],
  ['Capra', 'Ariete', 'easy'],
  ['Husky', 'Malamute', 'easy'],
  ['Ermellino', 'Donnola invernale', 'medium'],
  ['Seppia', 'Nautilo', 'medium'],
  ['Corallo', 'Anemone di mare', 'medium'],
  ['Krill', 'Plancton', 'medium'],
  ['Quokka', 'Bandicoot', 'medium'],
  ['Dingo', 'Diavolo della Tasmania', 'medium'],
  ['Canguro', 'Wallaroo', 'medium'],
  ['Kiwi', 'Casuario', 'medium'],
  ['Mantide religiosa', 'Insetto stecco', 'medium'],
  ['Cicala', 'Cavalletta verde', 'medium'],
  ['Mamba', 'Krait', 'medium'],
  ['Ligre', 'Tigon', 'medium'],
  ['Aye-aye', 'Tarsio', 'hard'],
  ['Tuatara', 'Drago di Komodo', 'hard'],
  ['Coati', 'Cercoletto', 'hard'],
  ['Bilby', 'Numbat', 'hard'],
]
const V4_PLACES_IT: V4Triple[] = [
  ['Berlino', 'Monaco di Baviera', 'easy'],
  ['Madrid', 'Lisbona', 'easy'],
  ['Rio de Janeiro', 'San Paolo', 'easy'],
  ['Bangkok', 'Ho Chi Minh', 'easy'],
  ['Helsinki', 'Tallinn', 'medium'],
  ['Bucarest', 'Sofia', 'medium'],
  ['Riad', 'Doha', 'medium'],
  ['Teheran', 'Baghdad', 'medium'],
  ['Tashkent', 'Almaty', 'medium'],
  ['Buenos Aires', 'Montevideo', 'medium'],
  ['Acapulco', 'Tulum', 'medium'],
  ['Marsiglia', 'Genova', 'medium'],
  ['Foresta Nera', 'Alpi Bavaresi', 'medium'],
  ['Pisa', 'Firenze', 'medium'],
  ['Citta del Vaticano', 'Principato di Monaco', 'medium'],
  ['Castello di Windsor', 'Castello di Edimburgo', 'medium'],
  ['Ulan Bator', 'Vladivostok', 'hard'],
  ['Banjul', 'Conakry', 'hard'],
  ['Suva', 'Apia', 'hard'],
  ['Paramaribo', 'Georgetown', 'hard'],
]
const V4_JOBS_IT: V4Triple[] = [
  ['Autista', 'Chauffeur', 'easy'],
  ['Cassiere', 'Sportellista', 'easy'],
  ['Addetto pulizie', 'Custode', 'easy'],
  ['Soldato', 'Marine', 'easy'],
  ['Nefrologo', 'Urologo', 'medium'],
  ['Endocrinologo', 'Ematologo', 'medium'],
  ['Ingegnere civile', 'Ingegnere strutturale', 'medium'],
  ['Ingegnere DevOps', 'Ingegnere SRE', 'medium'],
  ['Reclutatore', 'Cacciatore di teste', 'medium'],
  ['Consulente fiscale', 'Pianificatore finanziario', 'medium'],
  ['Conservatore', 'Restauratore', 'medium'],
  ['Conduttore', 'Corrispondente', 'medium'],
  ['Autore', 'Ghostwriter', 'medium'],
  ['Agente di viaggio', 'Guida turistica', 'medium'],
  ['Rumorista', 'Sound designer', 'medium'],
  ['Mastro birraio', 'Distillatore', 'medium'],
  ['Speziale', 'Erborista', 'hard'],
  ['Bottaio', 'Calzolaio', 'hard'],
  ['Calligrafo', 'Tipografo', 'hard'],
  ['Banditore', 'Perito stimatore', 'hard'],
]
const V4_SPORTS_IT: V4Triple[] = [
  ['Frisbee', 'Boomerang', 'easy'],
  ['Pattinaggio', 'Pattinaggio a rotelle', 'easy'],
  ['Stickball', 'Kickball', 'easy'],
  ['Pallavolo', 'Beach volley', 'easy'],
  ['Beach soccer', 'Calcio a 5', 'medium'],
  ['Snorkeling', 'Immersioni', 'medium'],
  ['Pesca subacquea', 'Apnea', 'medium'],
  ['Sandboard', 'Slittino ricreativo', 'medium'],
  ['Trikke', 'Segway', 'medium'],
  ['Volteggio equestre', 'Dressage', 'medium'],
  ['Arrampicata di velocita', 'Arrampicata Lead', 'medium'],
  ['Nuoto sincronizzato', 'Nuoto artistico', 'medium'],
  ['Tessuti aerei', 'Trapezio', 'medium'],
  ['Sci nautico', 'Wakeboard', 'medium'],
  ['Slackline', 'Funambolismo', 'medium'],
  ['Tiro alla fune', 'Lancio del tronco', 'medium'],
  ['Pelota basca', 'Frontenis', 'hard'],
  ['Buzkashi', 'Kok-Boru', 'hard'],
  ['Calcio storico', 'Cuju', 'hard'],
  ['Glima', 'Schwingen', 'hard'],
]

// PT
const V4_FOOD_PT: V4Triple[] = [
  ['Mel', 'Xarope de bordo', 'easy'],
  ['Limao', 'Lima', 'easy'],
  ['Azeitona', 'Abacate', 'easy'],
  ['Sanduiche', 'Wrap', 'easy'],
  ['Pad Thai', 'Macarrao bebado', 'medium'],
  ['Mac and Cheese', 'Cacio e Pepe', 'medium'],
  ['Salada Cesar', 'Salada Cobb', 'medium'],
  ['Hot Pot', 'Shabu Shabu', 'medium'],
  ['Sake', 'Soju', 'medium'],
  ['Bourbon', 'Whisky de centeio', 'medium'],
  ['Negroni', 'Manhattan', 'medium'],
  ['Mole', 'Adobo', 'medium'],
  ['Tom Yum', 'Tom Kha', 'medium'],
  ['Assar', 'Cozer no forno', 'medium'],
  ['Acafrao', 'Curcuma', 'medium'],
  ['Amendoa', 'Avela', 'medium'],
  ['Sous Vide', 'Confit', 'hard'],
  ['Beurre Blanc', 'Holandesa', 'hard'],
  ['Cassoulet', 'Choucroute', 'hard'],
  ['Bouillabaisse', 'Buridda', 'hard'],
]
const V4_ANIMALS_PT: V4Triple[] = [
  ['Vaca', 'Touro', 'easy'],
  ['Porco', 'Javali', 'easy'],
  ['Cabra', 'Carneiro', 'easy'],
  ['Husky', 'Malamute', 'easy'],
  ['Arminho', 'Doninha de inverno', 'medium'],
  ['Choco', 'Nautilo', 'medium'],
  ['Coral', 'Anemona-do-mar', 'medium'],
  ['Krill', 'Plancton', 'medium'],
  ['Quokka', 'Bandicoot', 'medium'],
  ['Dingo', 'Diabo da Tasmania', 'medium'],
  ['Canguru', 'Wallaroo', 'medium'],
  ['Kiwi', 'Casuar', 'medium'],
  ['Louva-a-deus', 'Bicho-pau', 'medium'],
  ['Cigarra', 'Esperanca', 'medium'],
  ['Mamba', 'Krait', 'medium'],
  ['Ligre', 'Tigon', 'medium'],
  ['Aye-aye', 'Tarsio', 'hard'],
  ['Tuatara', 'Dragao de Komodo', 'hard'],
  ['Quati', 'Jupara', 'hard'],
  ['Bilby', 'Numbat', 'hard'],
]
const V4_PLACES_PT: V4Triple[] = [
  ['Berlim', 'Munique', 'easy'],
  ['Madri', 'Lisboa', 'easy'],
  ['Rio de Janeiro', 'Sao Paulo', 'easy'],
  ['Bangcoc', 'Ho Chi Minh', 'easy'],
  ['Helsinque', 'Tallinn', 'medium'],
  ['Bucareste', 'Sofia', 'medium'],
  ['Riade', 'Doha', 'medium'],
  ['Teera', 'Bagda', 'medium'],
  ['Tashkent', 'Almaty', 'medium'],
  ['Buenos Aires', 'Montevideu', 'medium'],
  ['Acapulco', 'Tulum', 'medium'],
  ['Marselha', 'Genova', 'medium'],
  ['Floresta Negra', 'Alpes Bavaros', 'medium'],
  ['Pisa', 'Florenca', 'medium'],
  ['Vaticano', 'Monaco', 'medium'],
  ['Castelo de Windsor', 'Castelo de Edimburgo', 'medium'],
  ['Ulan Bator', 'Vladivostoque', 'hard'],
  ['Banjul', 'Conacri', 'hard'],
  ['Suva', 'Apia', 'hard'],
  ['Paramaribo', 'Georgetown', 'hard'],
]
const V4_JOBS_PT: V4Triple[] = [
  ['Motorista', 'Chofer', 'easy'],
  ['Caixa', 'Caixa bancario', 'easy'],
  ['Faxineiro', 'Zelador', 'easy'],
  ['Soldado', 'Fuzileiro', 'easy'],
  ['Nefrologista', 'Urologista', 'medium'],
  ['Endocrinologista', 'Hematologista', 'medium'],
  ['Engenheiro civil', 'Engenheiro estrutural', 'medium'],
  ['Engenheiro DevOps', 'Engenheiro SRE', 'medium'],
  ['Recrutador', 'Cacador de talentos', 'medium'],
  ['Consultor fiscal', 'Planejador financeiro', 'medium'],
  ['Conservador', 'Restaurador', 'medium'],
  ['Apresentador', 'Correspondente', 'medium'],
  ['Autor', 'Escritor fantasma', 'medium'],
  ['Agente de viagens', 'Guia turistico', 'medium'],
  ['Foley artist', 'Designer de som', 'medium'],
  ['Mestre cervejeiro', 'Destilador', 'medium'],
  ['Boticario', 'Herbalista', 'hard'],
  ['Tanoeiro', 'Sapateiro', 'hard'],
  ['Caligrafo', 'Tipografo', 'hard'],
  ['Leiloeiro', 'Avaliador', 'hard'],
]
const V4_SPORTS_PT: V4Triple[] = [
  ['Frisbee', 'Bumerangue', 'easy'],
  ['Patinacao', 'Patins inline', 'easy'],
  ['Stickball', 'Kickball', 'easy'],
  ['Voleibol', 'Volei de praia', 'easy'],
  ['Futebol de praia', 'Futebol de salao', 'medium'],
  ['Snorkel', 'Mergulho', 'medium'],
  ['Pesca subaquatica', 'Mergulho livre', 'medium'],
  ['Sandboard', 'Trenó', 'medium'],
  ['Trikke', 'Segway', 'medium'],
  ['Volteio equestre', 'Adestramento', 'medium'],
  ['Escalada de velocidade', 'Escalada de guia', 'medium'],
  ['Nado sincronizado', 'Nado artistico', 'medium'],
  ['Tecidos acrobaticos', 'Trapezio', 'medium'],
  ['Esqui aquatico', 'Wakeboard', 'medium'],
  ['Slackline', 'Equilibrismo', 'medium'],
  ['Cabo de guerra', 'Lancamento de tronco', 'medium'],
  ['Pelota basca', 'Frontenis', 'hard'],
  ['Buzkashi', 'Kok-Boru', 'hard'],
  ['Calcio Storico', 'Cuju', 'hard'],
  ['Glima', 'Schwingen', 'hard'],
]

// ZH
const V4_FOOD_ZH: V4Triple[] = [
  ['蜂蜜','枫糖浆','easy'],
  ['柠檬','青柠','easy'],
  ['橄榄','牛油果','easy'],
  ['三明治','卷饼','easy'],
  ['泰式炒河粉','醉酒河粉','medium'],
  ['芝士通心粉','黑椒奶酪意面','medium'],
  ['凯撒沙拉','科布沙拉','medium'],
  ['火锅','涮涮锅','medium'],
  ['清酒','烧酒','medium'],
  ['波本威士忌','黑麦威士忌','medium'],
  ['尼格罗尼','曼哈顿鸡尾酒','medium'],
  ['莫莱酱','阿斗波酱','medium'],
  ['冬阴功','冬阴椰奶汤','medium'],
  ['烘烤','焙烤','medium'],
  ['藏红花','姜黄','medium'],
  ['杏仁','榛子','medium'],
  ['低温慢煮','油封','hard'],
  ['白黄油酱','荷兰酱','hard'],
  ['卡苏莱','酸菜炖肉','hard'],
  ['马赛鱼汤','利古里亚鱼汤','hard'],
]
const V4_ANIMALS_ZH: V4Triple[] = [
  ['母牛','公牛','easy'],
  ['猪','野猪','easy'],
  ['山羊','公羊','easy'],
  ['哈士奇','阿拉斯加雪橇犬','easy'],
  ['白鼬','冬季黄鼬','medium'],
  ['乌贼','鹦鹉螺','medium'],
  ['珊瑚','海葵','medium'],
  ['磷虾','浮游生物','medium'],
  ['短尾矮袋鼠','袋狸','medium'],
  ['澳洲野犬','袋獾','medium'],
  ['袋鼠','沙袋鼠','medium'],
  ['几维鸟','鹤鸵','medium'],
  ['螳螂','竹节虫','medium'],
  ['蝉','纺织娘','medium'],
  ['曼巴蛇','环蛇','medium'],
  ['狮虎','虎狮','medium'],
  ['指猴','眼镜猴','hard'],
  ['楔齿蜥','科莫多巨蜥','hard'],
  ['南美浣熊','蜜熊','hard'],
  ['兔耳袋狸','袋食蚁兽','hard'],
]
const V4_PLACES_ZH: V4Triple[] = [
  ['柏林','慕尼黑','easy'],
  ['马德里','里斯本','easy'],
  ['里约热内卢','圣保罗','easy'],
  ['曼谷','胡志明市','easy'],
  ['赫尔辛基','塔林','medium'],
  ['布加勒斯特','索非亚','medium'],
  ['利雅得','多哈','medium'],
  ['德黑兰','巴格达','medium'],
  ['塔什干','阿拉木图','medium'],
  ['布宜诺斯艾利斯','蒙得维的亚','medium'],
  ['阿卡普尔科','图卢姆','medium'],
  ['马赛','热那亚','medium'],
  ['黑森林','巴伐利亚阿尔卑斯山','medium'],
  ['比萨','佛罗伦萨','medium'],
  ['梵蒂冈','摩纳哥','medium'],
  ['温莎城堡','爱丁堡城堡','medium'],
  ['乌兰巴托','符拉迪沃斯托克','hard'],
  ['班珠尔','科纳克里','hard'],
  ['苏瓦','阿皮亚','hard'],
  ['帕拉马里博','乔治敦','hard'],
]
const V4_JOBS_ZH: V4Triple[] = [
  ['司机','私人司机','easy'],
  ['收银员','银行柜员','easy'],
  ['清洁工','看门人','easy'],
  ['士兵','海军陆战队员','easy'],
  ['肾脏科医生','泌尿科医生','medium'],
  ['内分泌医生','血液科医生','medium'],
  ['土木工程师','结构工程师','medium'],
  ['DevOps工程师','SRE工程师','medium'],
  ['招聘专员','猎头','medium'],
  ['税务顾问','理财规划师','medium'],
  ['文物保管员','修复师','medium'],
  ['主播','驻外记者','medium'],
  ['作家','代笔','medium'],
  ['旅行社代理','导游','medium'],
  ['拟音师','声音设计师','medium'],
  ['酿酒师','蒸馏师','medium'],
  ['药剂师','草药师','hard'],
  ['制桶匠','补鞋匠','hard'],
  ['书法家','排版师','hard'],
  ['拍卖师','评估师','hard'],
]
const V4_SPORTS_ZH: V4Triple[] = [
  ['飞盘','回旋镖','easy'],
  ['滑冰','轮滑','easy'],
  ['街头棒球','踢球','easy'],
  ['排球','沙滩排球','easy'],
  ['沙滩足球','室内足球','medium'],
  ['浮潜','水肺潜水','medium'],
  ['鱼叉捕鱼','自由潜水','medium'],
  ['沙板','雪橇','medium'],
  ['踏板车','赛格威','medium'],
  ['马术体操','盛装舞步','medium'],
  ['速度攀岩','先锋攀岩','medium'],
  ['花样游泳','艺术游泳','medium'],
  ['空中绸缎','空中飞人','medium'],
  ['滑水','尾波滑水','medium'],
  ['绳索行走','走钢丝','medium'],
  ['拔河','掷木','medium'],
  ['巴斯克回力球','西班牙回力球','hard'],
  ['布兹卡西','叼羊','hard'],
  ['佛罗伦萨足球','蹴鞠','hard'],
  ['冰岛摔跤','瑞士摔跤','hard'],
]

// RU
const V4_FOOD_RU: V4Triple[] = [
  ['Мёд','Кленовый сироп','easy'],
  ['Лимон','Лайм','easy'],
  ['Оливка','Авокадо','easy'],
  ['Сэндвич','Ролл','easy'],
  ['Пад тай','Пьяная лапша','medium'],
  ['Макароны с сыром','Качо э пепе','medium'],
  ['Салат Цезарь','Салат Кобб','medium'],
  ['Хого','Сябу-сябу','medium'],
  ['Сакэ','Соджу','medium'],
  ['Бурбон','Ржаной виски','medium'],
  ['Негрони','Манхэттен','medium'],
  ['Моле','Адобо','medium'],
  ['Том ям','Том кха','medium'],
  ['Жарка','Запекание','medium'],
  ['Шафран','Куркума','medium'],
  ['Миндаль','Фундук','medium'],
  ['Су-вид','Конфи','hard'],
  ['Бер блан','Голландез','hard'],
  ['Кассуле','Шукрут','hard'],
  ['Буйабес','Буридда','hard'],
]
const V4_ANIMALS_RU: V4Triple[] = [
  ['Корова','Бык','easy'],
  ['Свинья','Кабан','easy'],
  ['Коза','Баран','easy'],
  ['Хаски','Маламут','easy'],
  ['Горностай','Зимний горностай','medium'],
  ['Каракатица','Наутилус','medium'],
  ['Коралл','Морская анемона','medium'],
  ['Криль','Планктон','medium'],
  ['Квокка','Бандикут','medium'],
  ['Динго','Тасманский дьявол','medium'],
  ['Кенгуру','Уоллару','medium'],
  ['Киви','Казуар','medium'],
  ['Богомол','Палочник','medium'],
  ['Цикада','Кузнечик древесный','medium'],
  ['Мамба','Крайт','medium'],
  ['Лигр','Тигон','medium'],
  ['Айе-айе','Долгопят','hard'],
  ['Туатара','Комодский варан','hard'],
  ['Коати','Кинкажу','hard'],
  ['Билби','Намбат','hard'],
]
const V4_PLACES_RU: V4Triple[] = [
  ['Берлин','Мюнхен','easy'],
  ['Мадрид','Лиссабон','easy'],
  ['Рио-де-Жанейро','Сан-Паулу','easy'],
  ['Бангкок','Хошимин','easy'],
  ['Хельсинки','Таллин','medium'],
  ['Бухарест','София','medium'],
  ['Эр-Рияд','Доха','medium'],
  ['Тегеран','Багдад','medium'],
  ['Ташкент','Алматы','medium'],
  ['Буэнос-Айрес','Монтевидео','medium'],
  ['Акапулько','Тулум','medium'],
  ['Марсель','Генуя','medium'],
  ['Шварцвальд','Баварские Альпы','medium'],
  ['Пиза','Флоренция','medium'],
  ['Ватикан','Монако','medium'],
  ['Виндзорский замок','Эдинбургский замок','medium'],
  ['Улан-Батор','Владивосток','hard'],
  ['Банжул','Конакри','hard'],
  ['Сува','Апиа','hard'],
  ['Парамарибо','Джорджтаун','hard'],
]
const V4_JOBS_RU: V4Triple[] = [
  ['Водитель','Шофёр','easy'],
  ['Кассир','Банковский кассир','easy'],
  ['Уборщик','Дворник','easy'],
  ['Солдат','Морпех','easy'],
  ['Нефролог','Уролог','medium'],
  ['Эндокринолог','Гематолог','medium'],
  ['Инженер-строитель','Инженер-конструктор','medium'],
  ['DevOps инженер','SRE инженер','medium'],
  ['Рекрутер','Хедхантер','medium'],
  ['Налоговый консультант','Финансовый планировщик','medium'],
  ['Хранитель','Реставратор','medium'],
  ['Ведущий','Корреспондент','medium'],
  ['Автор','Литературный негр','medium'],
  ['Турагент','Гид','medium'],
  ['Фоли-артист','Звукорежиссёр','medium'],
  ['Пивовар','Винокур','medium'],
  ['Аптекарь','Травник','hard'],
  ['Бочар','Сапожник','hard'],
  ['Каллиграф','Наборщик','hard'],
  ['Аукционист','Оценщик','hard'],
]
const V4_SPORTS_RU: V4Triple[] = [
  ['Фрисби','Бумеранг','easy'],
  ['Катание на коньках','Роликовые коньки','easy'],
  ['Стикбол','Кикбол','easy'],
  ['Волейбол','Пляжный волейбол','easy'],
  ['Пляжный футбол','Мини-футбол','medium'],
  ['Сноркелинг','Дайвинг','medium'],
  ['Подводная охота','Фридайвинг','medium'],
  ['Сэндбординг','Санки','medium'],
  ['Триккинг','Сегвей','medium'],
  ['Вольтижировка','Выездка','medium'],
  ['Скоростное скалолазание','Лазание с нижней страховкой','medium'],
  ['Синхронное плавание','Артистическое плавание','medium'],
  ['Воздушные полотна','Трапеция','medium'],
  ['Водные лыжи','Вейкбординг','medium'],
  ['Слэклайн','Канатоходство','medium'],
  ['Перетягивание каната','Метание бревна','medium'],
  ['Баскская пелота','Фронтенис','hard'],
  ['Бузкаши','Кок-бору','hard'],
  ['Кальчо Сторико','Цуцзюй','hard'],
  ['Глима','Швинген','hard'],
]

// HI
const V4_FOOD_HI: V4Triple[] = [
  ['शहद','मेपल सिरप','easy'],
  ['नींबू','हरा नींबू','easy'],
  ['ज़ैतून','एवोकाडो','easy'],
  ['सैंडविच','रैप','easy'],
  ['पैड थाई','ड्रंकन नूडल्स','medium'],
  ['मैक एंड चीज़','कैसियो ए पेपे','medium'],
  ['सीज़र सलाद','कॉब सलाद','medium'],
  ['हॉट पॉट','शबू शबू','medium'],
  ['साके','सोजू','medium'],
  ['बर्बन','राय व्हिस्की','medium'],
  ['नेग्रोनी','मैनहट्टन','medium'],
  ['मोले','अदोबो','medium'],
  ['टॉम यम','टॉम खा','medium'],
  ['भूनना','सेंकना','medium'],
  ['केसर','हल्दी','medium'],
  ['बादाम','हेज़लनट','medium'],
  ['सूस वी','कन्फी','hard'],
  ['ब्यूर ब्लैंक','हॉलैंडेज़','hard'],
  ['कैसुले','शूक्रूट','hard'],
  ['बूयाबेस','बुरिड्डा','hard'],
]
const V4_ANIMALS_HI: V4Triple[] = [
  ['गाय','सांड','easy'],
  ['सूअर','जंगली सूअर','easy'],
  ['बकरी','मेढ़ा','easy'],
  ['हस्की','मलमुट','easy'],
  ['स्टोट','शीतकालीन नेवला','medium'],
  ['कटलफिश','नॉटिलस','medium'],
  ['मूंगा','समुद्री एनीमोन','medium'],
  ['क्रिल','प्लवक','medium'],
  ['क्वोक्का','बैंडिकूट','medium'],
  ['डिंगो','तस्मानियाई शैतान','medium'],
  ['कंगारू','वालारू','medium'],
  ['कीवी','कैसोवरी','medium'],
  ['मेंटिस','छड़ी कीट','medium'],
  ['सिकाडा','कैटिडिड','medium'],
  ['मांबा','क्रेट','medium'],
  ['लाइगर','टाइगन','medium'],
  ['आय-आय','टार्सियर','hard'],
  ['तुआतारा','कोमोडो ड्रैगन','hard'],
  ['कोआटी','किंकाजू','hard'],
  ['बिल्बी','नंबत','hard'],
]
const V4_PLACES_HI: V4Triple[] = [
  ['बर्लिन','म्यूनिख','easy'],
  ['मैड्रिड','लिस्बन','easy'],
  ['रियो डी जनेरियो','साओ पाउलो','easy'],
  ['बैंकॉक','हो ची मिन्ह','easy'],
  ['हेलसिंकी','तालिन','medium'],
  ['बुखारेस्ट','सोफिया','medium'],
  ['रियाद','दोहा','medium'],
  ['तेहरान','बगदाद','medium'],
  ['ताशकंद','अल्माटी','medium'],
  ['ब्यूनस आयर्स','मोंटेवीडियो','medium'],
  ['अकापुल्को','तुलुम','medium'],
  ['मार्सिले','जेनोआ','medium'],
  ['ब्लैक फॉरेस्ट','बवेरियन आल्प्स','medium'],
  ['पीसा','फ्लोरेंस','medium'],
  ['वेटिकन सिटी','मोनाको','medium'],
  ['विंडसर कैसल','एडिनबर्ग कैसल','medium'],
  ['उलान बातर','व्लादिवोस्तोक','hard'],
  ['बंजुल','कोनाक्री','hard'],
  ['सुवा','अपिया','hard'],
  ['पारामारिबो','जॉर्जटाउन','hard'],
]
const V4_JOBS_HI: V4Triple[] = [
  ['ड्राइवर','शोफर','easy'],
  ['कैशियर','बैंक टेलर','easy'],
  ['सफाईकर्मी','चौकीदार','easy'],
  ['सैनिक','मरीन','easy'],
  ['नेफ्रोलॉजिस्ट','यूरोलॉजिस्ट','medium'],
  ['एंडोक्रिनोलॉजिस्ट','हेमेटोलॉजिस्ट','medium'],
  ['सिविल इंजीनियर','स्ट्रक्चरल इंजीनियर','medium'],
  ['DevOps इंजीनियर','SRE इंजीनियर','medium'],
  ['भर्तीकर्ता','हेडहंटर','medium'],
  ['कर सलाहकार','वित्तीय योजनाकार','medium'],
  ['संरक्षक','पुनरुद्धारक','medium'],
  ['एंकर','संवाददाता','medium'],
  ['लेखक','भूत लेखक','medium'],
  ['ट्रैवल एजेंट','टूर गाइड','medium'],
  ['फॉली कलाकार','साउंड डिज़ाइनर','medium'],
  ['ब्रूमास्टर','डिस्टिलर','medium'],
  ['एपोथेकेरी','हर्बलिस्ट','hard'],
  ['कूपर','मोची','hard'],
  ['सुलेखक','टाइपसेटर','hard'],
  ['नीलामकर्ता','मूल्यांकनकर्ता','hard'],
]
const V4_SPORTS_HI: V4Triple[] = [
  ['फ्रिसबी','बूमरैंग','easy'],
  ['स्केटिंग','रोलर स्केटिंग','easy'],
  ['स्टिकबॉल','किकबॉल','easy'],
  ['वॉलीबॉल','बीच वॉलीबॉल','easy'],
  ['बीच सॉकर','इनडोर सॉकर','medium'],
  ['स्नॉर्केलिंग','स्कूबा डाइविंग','medium'],
  ['भाला मछली पकड़ना','फ्री डाइविंग','medium'],
  ['सैंडबोर्डिंग','स्लेजिंग','medium'],
  ['ट्रिक्के','सेगवे','medium'],
  ['घुड़सवारी कलाबाज़ी','ड्रेसेज','medium'],
  ['स्पीड क्लाइंबिंग','लीड क्लाइंबिंग','medium'],
  ['सिंक्रनाइज़्ड स्विमिंग','कलात्मक तैराकी','medium'],
  ['एरियल सिल्क्स','ट्रैपीज़','medium'],
  ['वॉटर स्कीइंग','वेकबोर्डिंग','medium'],
  ['स्लैकलाइनिंग','रस्सी पर चलना','medium'],
  ['रस्साकशी','केबर टॉस','medium'],
  ['पेलोता वास्का','फ्रंटेनिस','hard'],
  ['बुज़काशी','कोक-बोरू','hard'],
  ['काल्चो स्टोरिको','कुजू','hard'],
  ['ग्लीमा','श्विंगन','hard'],
]

// ── Per-locale translatable pair tables ─────────────────────────────────────
const TR: Record<string, { food: V4Triple[]; animals: V4Triple[]; places: V4Triple[]; jobs: V4Triple[]; sports: V4Triple[] }> = {
  en: { food: V4_FOOD_EN, animals: V4_ANIMALS_EN, places: V4_PLACES_EN, jobs: V4_JOBS_EN, sports: V4_SPORTS_EN },
  fr: { food: V4_FOOD_FR, animals: V4_ANIMALS_FR, places: V4_PLACES_FR, jobs: V4_JOBS_FR, sports: V4_SPORTS_FR },
  es: { food: V4_FOOD_ES, animals: V4_ANIMALS_ES, places: V4_PLACES_ES, jobs: V4_JOBS_ES, sports: V4_SPORTS_ES },
  de: { food: V4_FOOD_DE, animals: V4_ANIMALS_DE, places: V4_PLACES_DE, jobs: V4_JOBS_DE, sports: V4_SPORTS_DE },
  ar: { food: V4_FOOD_AR, animals: V4_ANIMALS_AR, places: V4_PLACES_AR, jobs: V4_JOBS_AR, sports: V4_SPORTS_AR },
  it: { food: V4_FOOD_IT, animals: V4_ANIMALS_IT, places: V4_PLACES_IT, jobs: V4_JOBS_IT, sports: V4_SPORTS_IT },
  pt: { food: V4_FOOD_PT, animals: V4_ANIMALS_PT, places: V4_PLACES_PT, jobs: V4_JOBS_PT, sports: V4_SPORTS_PT },
  zh: { food: V4_FOOD_ZH, animals: V4_ANIMALS_ZH, places: V4_PLACES_ZH, jobs: V4_JOBS_ZH, sports: V4_SPORTS_ZH },
  ru: { food: V4_FOOD_RU, animals: V4_ANIMALS_RU, places: V4_PLACES_RU, jobs: V4_JOBS_RU, sports: V4_SPORTS_RU },
  hi: { food: V4_FOOD_HI, animals: V4_ANIMALS_HI, places: V4_PLACES_HI, jobs: V4_JOBS_HI, sports: V4_SPORTS_HI },
}

// ── Build per-locale V4 packs ───────────────────────────────────────────────
function buildV4ForLocale(loc: string): V4PairData[] {
  const tr = TR[loc]
  if (!tr) return []
  return [
    ...v4p('food',        loc, tr.food),
    ...v4p('animals',     loc, tr.animals),
    ...v4p('places',      loc, tr.places),
    ...v4p('jobs',        loc, tr.jobs),
    ...v4p('sports',      loc, tr.sports),
    ...v4p('mangas',      loc, V4_MANGAS),
    ...v4p('celebrities', loc, V4_CELEBRITIES),
    ...v4p('movies',      loc, V4_MOVIES),
    ...v4p('music',       loc, V4_MUSIC),
    ...v4p('history',     loc, V4_HISTORY),
    ...v4p('tech',        loc, V4_TECH),
  ]
}

export const ENGLISH_V4_PAIRS:    V4PairData[] = buildV4ForLocale('en')
export const FRENCH_V4_PAIRS:     V4PairData[] = buildV4ForLocale('fr')
export const SPANISH_V4_PAIRS:    V4PairData[] = buildV4ForLocale('es')
export const GERMAN_V4_PAIRS:     V4PairData[] = buildV4ForLocale('de')
export const ARABIC_V4_PAIRS:     V4PairData[] = buildV4ForLocale('ar')
export const ITALIAN_V4_PAIRS:    V4PairData[] = buildV4ForLocale('it')
export const PORTUGUESE_V4_PAIRS: V4PairData[] = buildV4ForLocale('pt')
export const CHINESE_V4_PAIRS:    V4PairData[] = buildV4ForLocale('zh')
export const RUSSIAN_V4_PAIRS:    V4PairData[] = buildV4ForLocale('ru')
export const INDIAN_V4_PAIRS:     V4PairData[] = buildV4ForLocale('hi')

export const V4_PAIRS_BY_LOCALE: Record<string, V4PairData[]> = {
  en: ENGLISH_V4_PAIRS,
  fr: FRENCH_V4_PAIRS,
  es: SPANISH_V4_PAIRS,
  de: GERMAN_V4_PAIRS,
  ar: ARABIC_V4_PAIRS,
  it: ITALIAN_V4_PAIRS,
  pt: PORTUGUESE_V4_PAIRS,
  zh: CHINESE_V4_PAIRS,
  ru: RUSSIAN_V4_PAIRS,
  hi: INDIAN_V4_PAIRS,
}

export const V4_PAIRS: V4PairData[] = V4_LOCALES.flatMap((loc) => buildV4ForLocale(loc))
