apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: red-handed-ingress
  namespace: red-handed
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: red-handed-compress@kubernetescrd
spec:
  tls:
    - hosts:
        - redhanded.yourdomain.com
        - api.redhanded.yourdomain.com
      secretName: red-handed-tls
  rules:
    - host: redhanded.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
    - host: api.redhanded.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3001
